import Flapjack.HolRef
import Flapjack.Compiler.Backend.BackendCommon
import Flapjack.Pancake.PanLang
import Flapjack.Pancake.PanLang.Shape
import Flapjack.Pancake.PanLang.Exp
import Flapjack.Pancake.PanLang.Prog
import Flapjack.Pancake.PanLang.Decl
import Flapjack.Display
import Flapjack.Ffi
import Flapjack.LoopFfi
import Flapjack.PanItreeFfi
import Flapjack.PanItreeTracePrefix
import Flapjack.PanItreeLtree
import Flapjack.PanHProgStore
import Flapjack.PanHProg
import Flapjack.PanHProgLoad
import Flapjack.PanHProgReturn
import Flapjack.PanHProgRaise
import Flapjack.PanHProgExtCall
import Flapjack.PanHProgStoreByte
import Flapjack.PanHProgStore32
import Flapjack.PanHProgPrimitive
import Flapjack.PanSetGlobal
import Flapjack.PanSemSetGlobal
import Flapjack.PanSemSetKvar
import Flapjack.PanSemLookupKvar
import Flapjack.PanSemIsValidValue
import Flapjack.PanSemWriteBytearray
import Flapjack.PanItreeEvaluate
import Flapjack.PanExt
import Flapjack.PanHHandleCallRet
import Flapjack.PanHHandleDecCallRet
import Flapjack.PanHProgDecCall
import Flapjack.PanHProgCall
import Flapjack.CrepExitLoop
import Flapjack.CrepFixClock
import Flapjack.CrepShMemLoad
import Flapjack.CrepShMemOp
import Flapjack.CrepShMemStore
import Flapjack.CrepMemLoad
import Flapjack.PanBst
import Flapjack.PanBStateUpdates
import Flapjack.PanBStateEmptyLocals
import Flapjack.PanEmptyLocals
import Flapjack.PanNbOp
import Flapjack.PanSetKvar
import Flapjack.PanShMemLoad
import Flapjack.PanShMemStore
import Flapjack.PanEval
import Flapjack.Pancake.Semantics.PanSem
import Flapjack.Pancake.Semantics.PanSem.TotalMeasureIf
import Flapjack.Pancake.Semantics.PanSem.LookupCode
import Flapjack.Pancake.Semantics.PanSem.TotalSteps
import Flapjack.Pancake.Semantics.PanSem.ValueHOL
import Flapjack.Pancake.Semantics.PanSem.StateExact
import Flapjack.Pancake.Semantics.PanSem.StateExactFiniteMap
import Flapjack.Pancake.Semantics.PanSem.EvaluateFinite
import Flapjack.Pancake.Semantics.PanSem.LocalUpdatesExact
import Flapjack.Pancake.Semantics.PanSem.IsValidValueExact
import Flapjack.Pancake.Semantics.PanSem.DecExact
import Flapjack.Pancake.Semantics.PanSem.AssignPrimitiveExact
import Flapjack.Pancake.Semantics.PanSem.ReturnRaiseExact
import Flapjack.Pancake.Semantics.PanSem.EvalExact
import Flapjack.Pancake.Semantics.PanSem.StoreExact
import Flapjack.Pancake.Semantics.PanSem.TickShMemExact
import Flapjack.Pancake.Semantics.PanSem.ExtCallExact
import Flapjack.Pancake.Semantics.PanSem.DecCallExact
import Flapjack.Pancake.Semantics.PanSem.CallExact
import Flapjack.Pancake.Semantics.PanSem.ControlExact
import Flapjack.Pancake.Semantics.PanSem.EvaluateDeclsExact
import Flapjack.Pancake.Semantics.PanSem.ClockExact
import Flapjack.Pancake.Semantics.PanSem.StateSimpExact
import Flapjack.Pancake.Semantics.PanSem.StateDefsExact
import Flapjack.Pancake.Semantics.PanSem.StateExactFinite
import Flapjack.Pancake.Semantics.PanSem.MemByteAssembly
import Flapjack.Pancake.Semantics.PanSem.MemLoad32Alt
import Flapjack.Pancake.Semantics.PanSem.MemStore32Alt
import Flapjack.Pancake.Semantics.PanSem.ByteRoundtrip
import Flapjack.Pancake.Semantics.PanSem.MemLoadHOL
import Flapjack.Pancake.Semantics.PanProps.MemByteArray
import Flapjack.Pancake.Semantics.PanSem.ShMemExact
import Flapjack.Pancake.Semantics.PanSem.DeclContextExact
import Flapjack.Pancake.Semantics.PanProps.EvalInvariant
import Flapjack.Pancake.Semantics.ByteAlignBridge
import Flapjack.Pancake.Semantics.LoopProps
import Flapjack.PanObservationalSemantics
import Flapjack.PanHHandleCallRet
import Flapjack.PanMrec
import Flapjack.PanHProgDec
import Flapjack.PanHProgSeq
import Flapjack.PanHProgCond
import Flapjack.PanHProgStoreMem
import Flapjack.PanHProgAssign
import Flapjack.PanHProgWhile
import Flapjack.Pancake.PanSimp
import Flapjack.PanLocalised
import Flapjack.Pancake.Proofs.PanSimp.Evaluate
import Flapjack.PanSimpLocalised
import Flapjack.Pancake.PanStructs
import Flapjack.Pancake.Proofs.PanStructs.CompileCorrect
import Flapjack.Pancake.PanGlobals
import Flapjack.Pancake.PanGlobalsByteRanged
import Flapjack.Pancake.Proofs.PanGlobals
import Flapjack.Pancake.Proofs.PanToCrep.EvaluateCases
import Flapjack.Pancake.Proofs.PanToCrep.TotalEvaluateCases
import Flapjack.Pancake.Proofs.PanToCrep
import Flapjack.Pancake.Proofs.PanToCrep.Primop
import Flapjack.Pancake.Proofs.PanToCrep.CompileProgParams
import Flapjack.Pipeline
import Flapjack.RiscV.PipelineDiagnostics
import Flapjack.RiscV.CorrectnessTraps
import Flapjack.RiscV.RegisterRelabel
import Flapjack.RiscV.RegisterTransfer
import Flapjack.RiscV.InstructionRelabel
import Flapjack.RiscV.InstructionCommutation
import Flapjack.RiscV.InstructionDataCommutation
import Flapjack.RiscV.CorrectnessBackendRegisterMap
import Flapjack.RiscV.CorrectnessParallelMove
import Flapjack.FlatCorrectness
import Flapjack.Tests
import Flapjack.Pancake.PanStatic
import Flapjack.Parser
import Flapjack.Parser.ByteRanged
import Flapjack.Parser.ConversionByteRanged
import Flapjack.Parser.GrammarByteRanged
import Flapjack.Parser.LocaliseByteRanged
import Flapjack.Parser.ParseTopDecsByteRanged
import Flapjack.Pancake.CrepLang
import Flapjack.Pancake.CrepLang.Exp
import Flapjack.Pancake.CrepLang.Prog
import Flapjack.Pancake.Semantics.CrepProps
import Flapjack.Pancake.WordConvs
import Flapjack.Pancake.PanToCrep
import Flapjack.CrepeCompileExpVariables
import Flapjack.CompileParamVarsBounds
import Flapjack.CrepeContextBounds
import Flapjack.Pancake.PanToCrep.Compile
import Flapjack.Pancake.PanToCrep.ExpHdlExact
import Flapjack.Pancake.Proofs.CrepArith
import Flapjack.Pancake.Proofs.CrepInline
import Flapjack.CompileFunctionDistinct
import Flapjack.Semantics
import Flapjack.CrepeSemantics
import Flapjack.CrepeGlobalAddress
import Flapjack.Pancake.Semantics.CrepSem
import Flapjack.Pancake.Semantics.CrepSem.LookupCode
import Flapjack.Pancake.Semantics.CrepSem.StateExact
import Flapjack.PanToCrepCorrectnessBoundary
import Flapjack.PanToCrepExceptionRelation
import Flapjack.PanToCrepMaxList
import Flapjack.PanValueFlatten
import Flapjack.FiniteMap
import Flapjack.CrepeExtCallInversion
import Flapjack.CrepeExpressionStability
import Flapjack.CrepeShapeInversion
import Flapjack.PanShapeMatches
import Flapjack.PanValueShapeInversion
import Flapjack.CrepeDistinctLists
import Flapjack.CrepeAllocationNameLemmas
import Flapjack.CompileParamVarsRelation
import Flapjack.CompileParamVarsSlotBounds
import Flapjack.PanValues
import Flapjack.PanValueEvaluatorStability
import Flapjack.PanSteppedSemantics
import Flapjack.PanMemory
import Flapjack.PanValueFfiFuel
import Flapjack.PanValueFfiClockSemantics
import Flapjack.PanValueFfiClockFuel
import Flapjack.PanValueFfiClockCorrectness
import Flapjack.PanValueFfiClockShift
import Flapjack.PanValueFfiEventMonotonicity
import Flapjack.PanValueFfiClockProjection
import Flapjack.PanCost
import Flapjack.RiscV.Model
import Flapjack.RiscV.Encoding
import Flapjack.RiscV.CorrectnessEncoding
import Flapjack.RiscV.PanMemory
import Flapjack.RiscV.Allocator
import Flapjack.RiscV.RegAlloc
import Flapjack.RiscV.Heuristics
import Flapjack.RiscV.SpillCosts
import Flapjack.RiscV.HeuristicDriver
import Flapjack.RiscV.HeuristicStackPipeline
import Flapjack.RiscV.CorrectnessHeuristicStack
import Flapjack.RiscV.CorrectnessGraphLocations
import Flapjack.RiscV.LinearScan
import Flapjack.RiscV.LinearScanSource
import Flapjack.RiscV.LinearScanDriver
import Flapjack.RiscV.OracleAllocator
import Flapjack.RiscV.AllocatorCorrectness
import Flapjack.RiscV.CorrectnessSsa
import Flapjack.RiscV.CorrectnessGraphCoverage
import Flapjack.RiscV.CorrectnessLongDiv
import Flapjack.RiscV.AllocatorBridgeCorrectness
import Flapjack.RiscV.CorrectnessColour
import Flapjack.RiscV.CorrectnessSsaColour
import Flapjack.RiscV.AllocatorDriver
import Flapjack.RiscV.CakeRegAlloc
import Flapjack.RiscV.WordToStack
import Flapjack.RiscV.LongDivRuntime
import Flapjack.RiscV.CorrectnessColourConditional
import Flapjack.RiscV.Backend
import Flapjack.RiscV.CorrectnessBackend
import Flapjack.RiscV.StepCorrectness
import Flapjack.RiscV.CorrectnessCondition
import Flapjack.RiscV.CorrectnessCode
import Flapjack.RiscV.CorrectnessConditional
import Flapjack.RiscV.Calls
import Flapjack.RiscV.CorrectnessWordToStack
import Flapjack.RiscV.CorrectnessSpill
import Flapjack.RiscV.CorrectnessStackParallelMove
import Flapjack.RiscV.CorrectnessStackFunctionEntry
import Flapjack.RiscV.CorrectnessStackFunctionSpill
import Flapjack.RiscV.CorrectnessAllocatorStack
import Flapjack.RiscV.CorrectnessAllocatorStackDecomposition
import Flapjack.RiscV.CorrectnessAllocatorStackContract
import Flapjack.RiscV.CorrectnessStackParallelMoveAcyclic
import Flapjack.RiscV.CorrectnessStackParallelMoveEvaluator
import Flapjack.RiscV.CorrectnessStackRemoveDynamic
import Flapjack.RiscV.CorrectnessStackRemoveBitmap
import Flapjack.RiscV.CorrectnessStack
import Flapjack.RiscV.CorrectnessFfiMachine
import Flapjack.RiscV.CorrectnessStack
import Flapjack.RiscV.Ffi
import Flapjack.RiscV.ExactFfi
import Flapjack.RiscV.Link
import Flapjack.WordSemantics
import Flapjack.Pancake.LoopLang
import Flapjack.NatDedup
import Flapjack.Pancake.CrepToLoop
import Flapjack.Pancake.CrepToLoop.Optimise
import Flapjack.Pancake.CrepToLoop.StateRel
import Flapjack.Pancake.LoopLive
/- The context-aware Crep-to-Loop correctness file is being updated alongside
   the faithful `findLoopVar` lowering and is intentionally not in this
   umbrella until its old identity-map assumptions are repaired. -/
import Flapjack.LoopSemantics
import Flapjack.Word
import Flapjack.Stack
import Flapjack.Compiler.Backend.StackLang
import Flapjack.Compiler.Backend.StackLang.Prog
import Flapjack.Compiler.Backend.StackCarrier
import Flapjack.Basis.Pure.MlString
import Flapjack.Compiler.Backend.MlStringBridge
import Flapjack.Compiler.Backend.StackProps
import Flapjack.Compiler.Backend.RegAlloc
import Flapjack.Misc.AppList
import Flapjack.Misc.Sptree
import Flapjack.Compiler.Backend.LabLang
import Flapjack.Compiler.Backend.LabSem
import Flapjack.Compiler.Backend.LabProps
import Flapjack.Compiler.Backend.StackNames
import Flapjack.Compiler.Backend.StackRemove
import Flapjack.Compiler.Backend.StackAlloc
import Flapjack.Compiler.Backend.WordToStack
import Flapjack.Compiler.Backend.WordToStackRegFormat
import Flapjack.RiscV.CakeAllocatorBitsBridge
import Flapjack.StackAlloc
import Flapjack.StackAlloc.Runtime
import Flapjack.StackAlloc.Machine
import Flapjack.RiscV.CorrectnessWordToStack
import Flapjack.StackAlloc.FrameMachine
import Flapjack.StackAlloc.CollectorSemantics
import Flapjack.StackAlloc.Correctness
import Flapjack.StackAlloc.BitmapSemantics
import Flapjack.StackRemove
import Flapjack.Lab
import Flapjack.RiscV.Lab
import Flapjack.RiscV.LabDiagnostics
import Flapjack.RiscV.WordDiagnostics
import Flapjack.FfiHOL
import Flapjack.FfiBridge

/-!
# Flapjack in Lean

The library currently contains the first Lean representation of Flapjack's
front-end language. The source of truth used while porting is the CakeML HOL
development in `cakeml/pancake`.
-/
