import Flapjack.Pancake.Semantics.CrepSem.TotalEval

/-! Regression cases for the restricted total Crep Assign clause. The direct
   HOL rows are generated by `scripts/hol-probes/crep_assign_eval_probeScript.sml`.
-/

namespace Flapjack.Test.CrepSemTotalAssignParity

open Flapjack

def sampleState : CrepHolState (BitVec 64) Unit :=
  { locals := fun name => if name == 0 then some (.word 7) else none
    globals := fun _ => none
    code := fun _ => none
    memory := fun _ => .word 0
    memaddrs := fun _ => false
    shMemaddrs := fun _ => false
    clock := 5
    bigEndian := false
    ffi := natCrepRuntimeFfiState
    baseAddress := 0
    topAddress := 100 }

def assignOracleRowsMatch : Bool :=
  let state := sampleState
  let overwrite := match evalCrepClockProg (.assignLocal 0 (.const 9)) state with
    | (none, post) => post.locals 0 == some (.word 9) &&
        post.locals 1 == none && post.clock == state.clock &&
        post.globals 0 == state.globals 0 && post.memory 0 == state.memory 0 &&
        post.baseAddress == state.baseAddress && post.topAddress == state.topAddress
    | _ => false
  let missingDestination :=
    match evalCrepClockProg (.assignLocal 1 (.const 9)) state with
    | (some .error, post) => post.locals 0 == state.locals 0 &&
        post.locals 1 == state.locals 1 && post.clock == state.clock
    | _ => false
  let badExpression :=
    match evalCrepClockProg (.assignLocal 0 (.var 9)) state with
    | (some .error, post) => post.locals 0 == state.locals 0 &&
        post.clock == state.clock
    | _ => false
  overwrite && missingDestination && badExpression

#guard assignOracleRowsMatch

theorem assignSuccessIsHolSetVar (state : CrepHolState (BitVec 64) Unit)
    (name : Nat) (value : CrepExp (BitVec 64))
    (wordLab : PanWordLab (BitVec 64))
    (hvalue : evalCrepHolExpWordLab state value = some wordLab)
    (hbound : ∃ old, state.locals name = some old) :
    evalCrepClockProg (.assignLocal name value) state =
      (none, setCrepHolVarW name wordLab state) :=
  evalCrepClockProg_assign_success name value state wordLab hvalue hbound

theorem assignExpressionErrorKeepsFullState
    (state : CrepHolState (BitVec 64) Unit)
    (name : Nat) (value : CrepExp (BitVec 64))
    (hvalue : evalCrepHolExpWordLab state value = none) :
    evalCrepClockProg (.assignLocal name value) state = (some .error, state) :=
  evalCrepClockProg_assign_error name value state hvalue

theorem assignMissingDestinationKeepsFullState
    (state : CrepHolState (BitVec 64) Unit)
    (name : Nat) (value : CrepExp (BitVec 64))
    (wordLab : PanWordLab (BitVec 64))
    (hvalue : evalCrepHolExpWordLab state value = some wordLab)
    (hmissing : state.locals name = none) :
    evalCrepClockProg (.assignLocal name value) state = (some .error, state) :=
  evalCrepClockProg_assign_missing name value state wordLab hvalue hmissing

def runChecks : IO Bool := do
  if assignOracleRowsMatch then
    IO.println "PASS total Crep HOL Assign overwrite and Error clauses match direct oracle"
  else
    IO.println "FAIL total Crep HOL Assign overwrite and Error clauses match direct oracle"
  pure assignOracleRowsMatch

end Flapjack.Test.CrepSemTotalAssignParity
