import Flapjack.Pancake.Semantics.CrepSem.TotalEval

/-! Regression cases for the first total Crep evaluator slice. The HOL oracle
   rows are generated by `scripts/hol-probes/crep_clock_leaf_eval_probeScript.sml`.
-/

namespace Flapjack.Test.CrepSemTotalClockLeavesParity

open Flapjack

def sampleState (clock : Nat) : CrepHolState (BitVec 64) Unit :=
  { locals := fun name => if name == 0 then some (.word 7) else none
    globals := fun _ => none
    code := fun _ => none
    memory := fun _ => .word 0
    memaddrs := fun _ => false
    shMemaddrs := fun _ => false
    clock := clock
    bigEndian := false
    ffi := natCrepRuntimeFfiState
    baseAddress := 0
    topAddress := 100 }

def ifOracleRowsMatch : Bool :=
  let state := sampleState 5
  let trueBranch : CrepClockProg 64 :=
    .ite (.const 5) (.leaf (.breakAt 3)) (.leaf .skip)
  let falseBranch : CrepClockProg 64 :=
    .ite (.const 0) (.leaf (.breakAt 3)) (.leaf (.continueAt 4))
  let errorBranch : CrepClockProg 64 :=
    .ite (.var 9) (.leaf .skip) (.leaf (.breakAt 5))
  let nestedBranch : CrepClockProg 64 :=
    .ite (.const 1)
      (.ite (.const 0) (.leaf .skip) (.leaf (.breakAt 6)))
      (.leaf (.continueAt 4))
  let trueOk := match evalCrepClockProg trueBranch state with
    | (some (.break 3), post) => post.clock == 5 && post.locals 0 == some (.word 7)
    | _ => false
  let falseOk := match evalCrepClockProg falseBranch state with
    | (some (.continue 4), post) => post.clock == 5
    | _ => false
  let errorOk := match evalCrepClockProg errorBranch state with
    | (some .error, post) => post.clock == 5 && post.locals 0 == some (.word 7)
    | _ => false
  let nestedOk := match evalCrepClockProg nestedBranch state with
    | (some (.break 6), post) => post.clock == 5
    | _ => false
  trueOk && falseOk && errorOk && nestedOk

#guard ifOracleRowsMatch

theorem skipFullState (state : CrepHolState (BitVec 64) Unit) :
    evalCrepClockLeaf .skip state = (none, state) :=
  evalCrepClockLeaf_skip state

theorem breakFullState (state : CrepHolState (BitVec 64) Unit) :
    evalCrepClockLeaf (.breakAt 3) state =
      (some (.break 3), state) :=
  evalCrepClockLeaf_break 3 state

theorem continueFullState (state : CrepHolState (BitVec 64) Unit) :
    evalCrepClockLeaf (.continueAt 2) state =
      (some (.continue 2), state) :=
  evalCrepClockLeaf_continue 2 state

theorem tickZeroFullState (state : CrepHolState (BitVec 64) Unit)
    (hclock : state.clock = 0) :
    evalCrepClockLeaf .tick state =
      (some .timeOut, emptyCrepHolLocals state) :=
  evalCrepClockLeaf_tick_zero state hclock

theorem tickPositiveFullState (state : CrepHolState (BitVec 64) Unit)
    (hclock : state.clock ≠ 0) :
    evalCrepClockLeaf .tick state = (none, decCrepHolClock state) :=
  evalCrepClockLeaf_tick_positive state hclock

def holOracleRowsMatch : Bool :=
  let state := sampleState 5
  let zero := sampleState 0
  let skipOk := match evalCrepClockLeaf .skip state with
    | (none, post) => post.clock == 5 && post.locals 0 == some (.word 7)
    | _ => false
  let breakOk := match evalCrepClockLeaf (.breakAt 1) state with
    | (some (.break 1), post) => post.clock == 5
    | _ => false
  let continueOk := match evalCrepClockLeaf (.continueAt 2) state with
    | (some (.continue 2), post) => post.clock == 5
    | _ => false
  let tickZeroOk := match evalCrepClockLeaf .tick zero with
    | (some .timeOut, post) => post.clock == 0 && post.locals 0 == none
    | _ => false
  let tickPositiveOk := match evalCrepClockLeaf .tick state with
    | (none, post) => post.clock == 4 && post.locals 0 == some (.word 7)
    | _ => false
  skipOk && breakOk && continueOk && tickZeroOk && tickPositiveOk

#guard holOracleRowsMatch

def runChecks : IO Bool := do
  if holOracleRowsMatch then
    IO.println "PASS total Crep HOL clock leaves match direct Skip/Break/Continue/Tick oracle"
  else
    IO.println "FAIL total Crep HOL clock leaves match direct Skip/Break/Continue/Tick oracle"
  if ifOracleRowsMatch then
    IO.println "PASS total Crep HOL If true/false/error/nested clauses match direct oracle"
  else
    IO.println "FAIL total Crep HOL If true/false/error/nested clauses match direct oracle"
  pure (holOracleRowsMatch && ifOracleRowsMatch)

end Flapjack.Test.CrepSemTotalClockLeavesParity
