import Flapjack.Pancake.Semantics.CrepSem.TotalEval

/-! Regression cases for the restricted total Crep evaluator. The HOL oracle
   rows are generated by `scripts/hol-probes/crep_clock_leaf_eval_probeScript.sml`.
-/

namespace Flapjack.Test.CrepSemTotalClockLeavesParity

open Flapjack

def sampleState (clock : Nat) : CrepHolState (BitVec 64) Unit :=
  { locals := fun name => if name == 0 then some (.word 7) else none
    globals := fun _ => none
    code := fun _ => none
    memory := fun _ => .word 0
    memaddrs := fun _ => false
    shMemaddrs := fun _ => false
    clock := clock
    bigEndian := false
    ffi := natCrepRuntimeFfiState
    baseAddress := 0
    topAddress := 100 }

def ifOracleRowsMatch : Bool :=
  let state := sampleState 5
  let trueBranch : CrepClockProg 64 :=
    .ite (.const 5) (.leaf (.breakAt 3)) (.leaf .skip)
  let falseBranch : CrepClockProg 64 :=
    .ite (.const 0) (.leaf (.breakAt 3)) (.leaf (.continueAt 4))
  let errorBranch : CrepClockProg 64 :=
    .ite (.var 9) (.leaf .skip) (.leaf (.breakAt 5))
  let nestedBranch : CrepClockProg 64 :=
    .ite (.const 1)
      (.ite (.const 0) (.leaf .skip) (.leaf (.breakAt 6)))
      (.leaf (.continueAt 4))
  let trueOk := match evalCrepClockProg trueBranch state with
    | (some (.break 3), post) => post.clock == 5 && post.locals 0 == some (.word 7)
    | _ => false
  let falseOk := match evalCrepClockProg falseBranch state with
    | (some (.continue 4), post) => post.clock == 5
    | _ => false
  let errorOk := match evalCrepClockProg errorBranch state with
    | (some .error, post) => post.clock == 5 && post.locals 0 == some (.word 7)
    | _ => false
  let nestedOk := match evalCrepClockProg nestedBranch state with
    | (some (.break 6), post) => post.clock == 5
    | _ => false
  trueOk && falseOk && errorOk && nestedOk

def seqOracleRowsMatch : Bool :=
  let state := sampleState 5
  let zero := sampleState 0
  let normalOk := match evalCrepClockProg
      (.seq (.leaf .skip) (.leaf (.breakAt 7))) state with
    | (some (.break 7), post) => post.clock == 5
    | _ => false
  let controlOk := match evalCrepClockProg
      (.seq (.leaf (.breakAt 8)) (.leaf .tick)) state with
    | (some (.break 8), post) => post.clock == 5
    | _ => false
  let tickOk := match evalCrepClockProg
      (.seq (.leaf .tick) (.leaf .skip)) state with
    | (none, post) => post.clock == 4 && post.locals 0 == some (.word 7)
    | _ => false
  let timeoutOk := match evalCrepClockProg
      (.seq (.leaf .tick) (.leaf .skip)) zero with
    | (some .timeOut, post) => post.clock == 0 && post.locals 0 == none
    | _ => false
  let raisedClock := { state with clock := 7 }
  let clampOk :=
    (fixCrepHolClockW state
      ((none : Option (CrepResultHOL (BitVec 64) FfiFinalEvent)), raisedClock)).2.clock == 5
  normalOk && controlOk && tickOk && timeoutOk && clampOk

def returnOracleRowsMatch : Bool :=
  let state := sampleState 5
  let wordOk := match evalCrepClockProg
      (.returnValues [.const 9]) state with
    | (some (.return [.word 9]), post) =>
        post.clock == 5 && post.locals 0 == none
    | _ => false
  let emptyOk := match evalCrepClockProg (.returnValues []) state with
    | (some (.return []), post) => post.clock == 5 && post.locals 0 == none
    | _ => false
  let errorOk := match evalCrepClockProg (.returnValues [.var 9]) state with
    | (some .error, post) => post.clock == 5 && post.locals 0 == some (.word 7)
    | _ => false
  wordOk && emptyOk && errorOk

def raiseOracleRowMatches : Bool :=
  let state := sampleState 5
  match evalCrepClockProg (.raiseException 9) state with
  | (some (.exception 9), post) =>
      post.clock == 5 && post.locals 0 == none && post.globals 0 == none &&
        post.memory 0 == .word 0 && post.baseAddress == 0 && post.topAddress == 100
  | _ => false

def decOracleRowsMatch : Bool :=
  let state := sampleState 5
  let shadowOk := match evalCrepClockProg
      (.decLocal 0 (.const 9) (.leaf .skip)) state with
    | (none, post) => post.clock == 5 && post.locals 0 == some (.word 7)
    | _ => false
  let newOk := match evalCrepClockProg
      (.decLocal 1 (.const 9) (.leaf .skip)) state with
    | (none, post) => post.clock == 5 && post.locals 1 == none &&
        post.locals 0 == some (.word 7)
    | _ => false
  let errorOk := match evalCrepClockProg
      (.decLocal 0 (.var 9) (.leaf .skip)) state with
    | (some .error, post) => post.clock == 5 && post.locals 0 == some (.word 7)
    | _ => false
  shadowOk && newOk && errorOk

#guard ifOracleRowsMatch
#guard seqOracleRowsMatch
#guard returnOracleRowsMatch
#guard raiseOracleRowMatches
#guard decOracleRowsMatch

theorem skipFullState (state : CrepHolState (BitVec 64) Unit) :
    evalCrepClockLeaf .skip state = (none, state) :=
  evalCrepClockLeaf_skip state

theorem breakFullState (state : CrepHolState (BitVec 64) Unit) :
    evalCrepClockLeaf (.breakAt 3) state =
      (some (.break 3), state) :=
  evalCrepClockLeaf_break 3 state

theorem continueFullState (state : CrepHolState (BitVec 64) Unit) :
    evalCrepClockLeaf (.continueAt 2) state =
      (some (.continue 2), state) :=
  evalCrepClockLeaf_continue 2 state

theorem tickZeroFullState (state : CrepHolState (BitVec 64) Unit)
    (hclock : state.clock = 0) :
    evalCrepClockLeaf .tick state =
      (some .timeOut, emptyCrepHolLocals state) :=
  evalCrepClockLeaf_tick_zero state hclock

theorem tickPositiveFullState (state : CrepHolState (BitVec 64) Unit)
    (hclock : state.clock ≠ 0) :
    evalCrepClockLeaf .tick state = (none, decCrepHolClock state) :=
  evalCrepClockLeaf_tick_positive state hclock

def holOracleRowsMatch : Bool :=
  let state := sampleState 5
  let zero := sampleState 0
  let skipOk := match evalCrepClockLeaf .skip state with
    | (none, post) => post.clock == 5 && post.locals 0 == some (.word 7)
    | _ => false
  let breakOk := match evalCrepClockLeaf (.breakAt 1) state with
    | (some (.break 1), post) => post.clock == 5
    | _ => false
  let continueOk := match evalCrepClockLeaf (.continueAt 2) state with
    | (some (.continue 2), post) => post.clock == 5
    | _ => false
  let tickZeroOk := match evalCrepClockLeaf .tick zero with
    | (some .timeOut, post) => post.clock == 0 && post.locals 0 == none
    | _ => false
  let tickPositiveOk := match evalCrepClockLeaf .tick state with
    | (none, post) => post.clock == 4 && post.locals 0 == some (.word 7)
    | _ => false
  skipOk && breakOk && continueOk && tickZeroOk && tickPositiveOk

#guard holOracleRowsMatch

def runChecks : IO Bool := do
  if holOracleRowsMatch then
    IO.println "PASS total Crep HOL clock leaves match direct Skip/Break/Continue/Tick oracle"
  else
    IO.println "FAIL total Crep HOL clock leaves match direct Skip/Break/Continue/Tick oracle"
  if ifOracleRowsMatch then
    IO.println "PASS total Crep HOL If true/false/error/nested clauses match direct oracle"
  else
    IO.println "FAIL total Crep HOL If true/false/error/nested clauses match direct oracle"
  if seqOracleRowsMatch then
    IO.println "PASS total Crep HOL Seq fix_clock normal/control/timeout clauses match direct oracle"
  else
    IO.println "FAIL total Crep HOL Seq fix_clock normal/control/timeout clauses match direct oracle"
  if returnOracleRowsMatch then
    IO.println "PASS total Crep HOL Return values/empty/error clauses match direct oracle"
  else
    IO.println "FAIL total Crep HOL Return values/empty/error clauses match direct oracle"
  if raiseOracleRowMatches then
    IO.println "PASS total Crep HOL Raise exception/empty-locals clause matches direct oracle"
  else
    IO.println "FAIL total Crep HOL Raise exception/empty-locals clause matches direct oracle"
  if decOracleRowsMatch then
    IO.println "PASS total Crep HOL Dec bind/restore/error clauses match direct oracle"
  else
    IO.println "FAIL total Crep HOL Dec bind/restore/error clauses match direct oracle"
  pure (holOracleRowsMatch && ifOracleRowsMatch && seqOracleRowsMatch &&
    returnOracleRowsMatch && raiseOracleRowMatches && decOracleRowsMatch)

end Flapjack.Test.CrepSemTotalClockLeavesParity
