import Flapjack.LoopSemantics
import Flapjack.RiscV.Model

/-!
# Source parity for Pancake `loopSem$eval`

The reference is `cakeml/pancake/semantics/loopSemScript.sml:71-93`
(`eval_def`).  Expected observations are transcribed from the checked-in
HOL-EVAL fixture `scripts/hol-probes/loop_sem_eval_probe.out`, generated by
`loop_sem_eval_probeScript.sml`.  The source-shaped evaluator also checks the
intermediate list evaluation needed by n-ary `Op` expressions.
-/

namespace Flapjack.Test.LoopEvalParity

open Flapjack
open Flapjack.RiscV

abbrev ProbeWord := RiscV.Word 8

def word (value : Nat) : ProbeWord := BitVec.ofNat 8 value

def probeState : LoopState ProbeWord :=
  { locals := fun name => if name == 2 then some (word 7) else none
    globals := fun address => if address == word 3 then some (word 9) else none
    memory := fun address => if address == word 3 then some (word 11) else none }

def eval (expression : LoopExp ProbeWord) : Option ProbeWord :=
  evalLoopExpSource probeState (word 4) (word 100) expression

def originalConst : Option ProbeWord := some (word 7)
def originalVarHit : Option ProbeWord := some (word 7)
def originalVarMiss : Option ProbeWord := none
def originalLookupHit : Option ProbeWord := some (word 9)
def originalLookupMiss : Option ProbeWord := none
def originalLoadHit : Option ProbeWord := some (word 11)
def originalLoadMiss : Option ProbeWord := none
def originalAddThree : Option ProbeWord := some (word 6)
def originalAndEmpty : Option ProbeWord := some (word 255)
def originalSubBadArity : Option ProbeWord := none
def originalRor : Option ProbeWord := some (word 192)
def originalShiftOutOfRange : Option ProbeWord := none
def originalBaseAddr : Option ProbeWord := some (word 4)
def originalTopAddr : Option ProbeWord := some (word 100)

def checks : List (String × Bool) := [
  ("eval Const", eval (.const (word 7)) == originalConst),
  ("eval Var hit", eval (.var 2) == originalVarHit),
  ("eval Var miss", eval (.var 3) == originalVarMiss),
  ("eval Lookup hit", eval (.lookup (word 3)) == originalLookupHit),
  ("eval Lookup miss", eval (.lookup (word 4)) == originalLookupMiss),
  ("eval Load hit", eval (.load (.const (word 3))) == originalLoadHit),
  ("eval Load miss", eval (.load (.const (word 4))) == originalLoadMiss),
  ("eval n-ary Add intermediate computation",
    eval (.op .add [.const (word 1), .const (word 2), .const (word 3)]) ==
      originalAddThree),
  ("eval empty And identity", eval (.op .and []) == originalAndEmpty),
  ("eval Sub rejects non-pair", eval (.op .sub [.const (word 7)]) ==
      originalSubBadArity),
  ("eval RotateRight", eval (.shift .ror (.const (word 129)) (.const (word 1))) ==
      originalRor),
  ("eval rejects out-of-range shift", eval (.shift .lsl (.const (word 1))
      (.const (word 8))) == originalShiftOutOfRange),
  ("eval BaseAddr", eval .baseAddr == originalBaseAddr),
  ("eval TopAddr", eval .topAddr == originalTopAddr)
]

def runChecks : IO Bool := do
  let results ← checks.mapM fun (name, passed) => do
    if passed then
      IO.println s!"PASS {name}"
    else
      IO.println s!"FAIL {name}"
    pure passed
  pure (results.all id)

#guard eval (.const (word 7)) == originalConst
#guard eval (.var 2) == originalVarHit
#guard eval (.var 3) == originalVarMiss
#guard eval (.lookup (word 3)) == originalLookupHit
#guard eval (.lookup (word 4)) == originalLookupMiss
#guard eval (.load (.const (word 3))) == originalLoadHit
#guard eval (.load (.const (word 4))) == originalLoadMiss
#guard eval (.op .add [.const (word 1), .const (word 2), .const (word 3)]) ==
  originalAddThree
#guard eval (.op .and []) == originalAndEmpty
#guard eval (.op .sub [.const (word 7)]) == originalSubBadArity
#guard eval (.shift .ror (.const (word 129)) (.const (word 1))) == originalRor
#guard eval (.shift .lsl (.const (word 1)) (.const (word 8))) ==
  originalShiftOutOfRange
#guard eval .baseAddr == originalBaseAddr
#guard eval .topAddr == originalTopAddr

end Flapjack.Test.LoopEvalParity
