import Flapjack.LoopFfi

/-!
# Original-domain parity for `loopSem$sh_mem_load`

Reference: `cakeml/pancake/semantics/loopSemScript.sml:198-215`.
Expected source observations are checked in at
`scripts/hol-probes/loop_sem_sh_mem_load_probe.out`, generated by
`loop_sem_sh_mem_load_probeScript.sml`.  CakeML's source word codec prints the
returned byte as an unreduced `set_byte` term in HOL; the Lean byte codec
normalizes that same value to `3` for comparison.
-/

namespace Flapjack.Test.LoopShMemLoadParity

open Flapjack

def returningState (shared : Bool) : LoopFfiState Nat Unit :=
  { locals := fun _ => none
    globals := fun _ => none
    memory := fun _ => none
    memaddrs := fun _ => true
    shMemaddrs := fun _ => shared
    byteAlign := id
    clock := 10
    bigEndian := false
    baseAddress := 0
    topAddress := 0
    ffi :=
      { oracle := fun _ state _ bytes => .returned state bytes
        state := ()
        ioEvents := [] }
    wordToBytes := fun value _ => [UInt8.ofNat value]
    wordOfBytes := fun _ bytes => bytes.head?.getD 0 |>.toNat
    valueToNat := id }

def returnLoad : Bool :=
  match loopFfiShMemLoad (returningState true) 1 3 0 with
  | (.normal state, _) =>
      state.locals 1 == some 3 && state.ffi.ioEvents.length == 1
  | _ => false

def missingLocalInserts : Bool :=
  match loopFfiShMemLoad (returningState true) 1 3 0 with
  | (.normal state, _) => state.locals 1 == some 3
  | _ => false

def alignedPayloadOriginal : Bool :=
  let state := { returningState true with
    byteAlign := fun _ => 0
    shMemaddrs := fun address => address == 0 }
  match loopFfiShMemLoad state 1 3 1 with
  | (.normal state, _) => state.locals 1 == some 3
  | _ => false

def domainError : Bool :=
  match loopFfiShMemLoad (returningState false) 1 3 0 with
  | (.error _, _) => true
  | _ => false

def finalState : LoopFfiState Nat Unit :=
  { returningState true with
    locals := fun name => if name == 1 then some 9 else none
    ffi :=
      { (returningState true).ffi with
        oracle := fun _ _ _ _ => .final .failed } }

def finalClearsLocals : Bool :=
  match loopFfiShMemLoad (finalState) 1 3 0 with
  | (.finalFfi state _, _) => state.locals 1 == none
  | _ => false

#guard returnLoad
#guard missingLocalInserts
#guard alignedPayloadOriginal
#guard domainError
#guard finalClearsLocals

def runChecks : IO Bool := do
  let checks : List (String × Bool) := [
    ("sh_mem_load returns a word and records the FFI event", returnLoad),
    ("sh_mem_load inserts a missing destination local", missingLocalInserts),
    ("sh_mem_load checks aligned domain but sends original address", alignedPayloadOriginal),
    ("sh_mem_load rejects an unmapped shared address", domainError),
    ("sh_mem_load clears locals on final FFI", finalClearsLocals)]
  let results ← checks.mapM fun (name, passed) => do
    if passed then
      IO.println s!"PASS {name}"
    else
      IO.println s!"FAIL {name}"
    pure passed
  pure (results.all id)

end Flapjack.Test.LoopShMemLoadParity
