import Flapjack.LoopPrimop
import Flapjack.Test.OriginalPancakeProbes

/-!
# Original-domain parity for `loop_primop`

The expected observations are transcribed from
`scripts/hol-probes/loop_sem_primop_probe.out`, generated by direct HOL-EVAL
of `loopSemScript.sml:242-252`.  This test exercises the faithful RISC-V word
instance, including both carry behavior and the original rejection cases.
-/

namespace Flapjack.Test.LoopPrimopParity

open Flapjack Flapjack.RiscV

def originalValidNoCarry : Option (List (Word 64)) :=
  some [BitVec.ofNat 64 7, BitVec.ofNat 64 0]

def originalValidCarry : Option (List (Word 64)) :=
  some [BitVec.ofNat 64 0, BitVec.ofNat 64 1]

def originalInvalidArity : Option (List (Word 64)) := none
def originalInvalidNonword : Option (List (Word 64)) := none

def isValidNonCarry : Bool :=
  loopPrimop (width := 64) .addCarry
      [BitVec.ofNat 64 3, BitVec.ofNat 64 4, BitVec.ofNat 64 0] =
    originalValidNoCarry

def isValidCarry : Bool :=
  loopPrimop (width := 64) .addCarry
      [BitVec.ofNat 64 (2^64 - 1), BitVec.ofNat 64 0, BitVec.ofNat 64 1] =
    originalValidCarry

def isInvalidArity : Bool :=
  loopPrimop (width := 64) .addCarry
      [BitVec.ofNat 64 3, BitVec.ofNat 64 4] = originalInvalidArity

def isInvalidOtherPrimitive : Bool :=
  loopPrimop (width := 64) .addCarry [] = originalInvalidNonword

#guard isValidNonCarry
#guard isValidCarry
#guard isInvalidArity
#guard isInvalidOtherPrimitive

def runChecks : IO Bool := do
  let checks :=
    [ ("Loop loop_primop valid AddCarry without carry", isValidNonCarry)
      , ("Loop loop_primop valid AddCarry with carry", isValidCarry)
      , ("Loop loop_primop rejects wrong arity", isInvalidArity)
      , ("Loop loop_primop rejects malformed arguments", isInvalidOtherPrimitive) ]
  let results ← checks.mapM fun (name, ok) => do
    if ok then
      IO.println s!"PASS {name}"
      pure true
    else
      IO.println s!"FAIL {name}"
      pure false
  pure (results.all id)

end Flapjack.Test.LoopPrimopParity
