import Flapjack.LoopAnalysis

/-!
# Original-domain parity for `locals_touched`

`loopLocalsTouched` is the Lean port of
`cakeml/pancake/loopLangScript.sml:77-88`.  The expected observations are
from `scripts/hol-probes/loop_lang_locals_touched_probe.out`, generated by
`loop_lang_locals_touched_probeScript.sml`; this keeps the test anchored to
the original HOL definition rather than to a second Lean implementation.
-/

namespace Flapjack.Test.LoopLocalsTouchedParity

open Flapjack

def originalConst : List Nat := []
def originalVar : List Nat := [3]
def originalLoadVar : List Nat := [4]
def originalOpNested : List Nat := [2, 4]
def originalBaseAddr : List Nat := []

def probeConst : LoopExp Nat := .const 7
def probeVar : LoopExp Nat := .var 3
def probeLoadVar : LoopExp Nat := .load (.var 4)
def probeOpNested : LoopExp Nat :=
  .op .add [.var 2, .load (.var 4), .const 7]
def probeBaseAddr : LoopExp Nat := .baseAddr

#guard loopLocalsTouched probeConst == originalConst
#guard loopLocalsTouched probeVar == originalVar
#guard loopLocalsTouched probeLoadVar == originalLoadVar
#guard loopLocalsTouched probeOpNested == originalOpNested
#guard loopLocalsTouched probeBaseAddr == originalBaseAddr

def check (name : String) (actual expected : List Nat) : IO Bool := do
  if actual == expected then
    IO.println s!"PASS {name}"
    pure true
  else
    IO.println s!"FAIL {name}: expected {repr expected}, got {repr actual}"
    pure false

def runChecks : IO Bool := do
  let results ← [
    check "locals_touched const" (loopLocalsTouched probeConst) originalConst,
    check "locals_touched var" (loopLocalsTouched probeVar) originalVar,
    check "locals_touched load" (loopLocalsTouched probeLoadVar) originalLoadVar,
    check "locals_touched nested op"
      (loopLocalsTouched probeOpNested) originalOpNested,
    check "locals_touched base address"
      (loopLocalsTouched probeBaseAddr) originalBaseAddr ].mapM id
  pure (results.all id)

end Flapjack.Test.LoopLocalsTouchedParity
