import Flapjack.LoopSetVars

/-!
# Original-domain parity for `set_var`

The original definition is
`cakeml/pancake/semantics/loopSemScript.sml:108-110`:
`set_var v x s = s with locals := insert v x s.locals`.
The expected observations are direct HOL-EVAL results from
`scripts/hol-probes/loop_sem_set_var_probeScript.sml`, checked in at
`scripts/hol-probes/loop_sem_set_var_probe.out` and regenerated by
`scripts/hol-probes/regenerate.sh`.
-/

namespace Flapjack.Test.LoopSetVarParity

open Flapjack

def originalProbeSource : String :=
  "cakeml/pancake/semantics/loopSemScript.sml:108-110 (set_var_def)"

def originalNew : Option (List Nat) := some [5]
def originalOverwrite : Option (List Nat) := some [5]
def originalSibling : Option (List Nat) := some [7]
def originalMissing : Option (List Nat) := none

def emptyLocals : Nat → Option Nat := fun _ => none

def read (locals : Nat → Option Nat) (names : List Nat) : Option (List Nat) :=
  loopReadLocals locals names

#guard originalProbeSource ==
  "cakeml/pancake/semantics/loopSemScript.sml:108-110 (set_var_def)"
#guard read (loopSetVar emptyLocals 3 5) [3] == originalNew
#guard read (loopSetVar (fun key => if key == 3 then some 1 else none) 3 5) [3] ==
  originalOverwrite
#guard read (loopSetVar (fun key => if key == 4 then some 7 else none) 3 5) [4] ==
  originalSibling
#guard read (loopSetVar emptyLocals 3 5) [5] == originalMissing

def runChecks : IO Bool := do
  let checks :=
    [ ("Loop set_var inserts a new local",
        read (loopSetVar emptyLocals 3 5) [3] == originalNew),
      ("Loop set_var overwrites an existing local",
        read (loopSetVar (fun key => if key == 3 then some 1 else none) 3 5) [3] ==
          originalOverwrite),
      ("Loop set_var preserves a sibling local",
        read (loopSetVar (fun key => if key == 4 then some 7 else none) 3 5) [4] ==
          originalSibling),
      ("Loop set_var leaves a missing local absent",
        read (loopSetVar emptyLocals 3 5) [5] == originalMissing) ]
  let results ← checks.mapM fun (name, ok) => do
    if ok then
      IO.println s!"PASS {name}"
      pure true
    else
      IO.println s!"FAIL {name}"
      pure false
  pure (results.all id)

end Flapjack.Test.LoopSetVarParity
