import Flapjack.LoopStateResult

/-!
# Original-domain parity for `loopSem$cut_state`

Reference: `cakeml/pancake/semantics/loopSemScript.sml:182-186`.
The expected observations are transcribed from
`scripts/hol-probes/loop_sem_cut_state_probe.out`, generated by
`loop_sem_cut_state_probeScript.sml`.  The `LoopMachineState` model preserves
all non-local state fields; this test compares the restricted local map and
the `NONE` failure for a missing live local.
-/

namespace Flapjack.Test.LoopCutStateParity

open Flapjack

def probeState (locals : Nat → Option LoopWordLoc) : LoopMachineState Nat :=
  { locals := locals
    globals := fun _ => none
    memory := fun _ => none
    mdomain := fun _ => false
    shMdomain := fun _ => false
    clock := 7
    code := []
    be := false
    ffi := 0
    baseAddr := 4
    topAddr := 100 }

def populatedLocals : Nat → Option LoopWordLoc
  | 1 => some (.word 5)
  | 2 => some (.word 7)
  | 3 => some (.word 9)
  | _ => none

def hit : Bool :=
  (cutLoopState [1, 2] (probeState populatedLocals)).map
      (fun state => (state.locals 1, state.locals 2, state.locals 3)) ==
    some (some (.word 5), some (.word 7), none)

def missingLive : Bool :=
  (cutLoopState [1, 3] (probeState (fun name =>
    if name == 1 then some (.word 5) else none))).isNone

def emptyLive : Bool :=
  (cutLoopState [] (probeState (fun name =>
    if name == 1 then some (.word 5) else none))).map
      (fun state => state.locals 1) == some none

def locPreserved : Bool :=
  (cutLoopState [1] (probeState (fun name =>
    if name == 1 then some (.loc 9 0)
    else if name == 2 then some (.word 7) else none))).map
      (fun state => state.locals 1) == some (some (.loc 9 0))

#guard hit
#guard missingLive
#guard emptyLive
#guard locPreserved

def runChecks : IO Bool := do
  let checks : List (String × Bool) := [
    ("cut_state keeps each live local and removes siblings", hit),
    ("cut_state rejects a missing live local", missingLive),
    ("cut_state accepts an empty live set", emptyLive),
    ("cut_state preserves a non-word live local", locPreserved)]
  let results ← checks.mapM fun (name, passed) => do
    if passed then
      IO.println s!"PASS {name}"
    else
      IO.println s!"FAIL {name}"
    pure passed
  pure (results.all id)

end Flapjack.Test.LoopCutStateParity
