import Flapjack.LoopAnalysis

/-!
# Original-domain parity for `assigned_vars`

`loopAssignedVars` is the Lean counterpart of
`cakeml/pancake/loopLangScript.sml:94-115`.  Expected observations are from
the checked-in HOL probe output generated by
`loop_lang_assigned_vars_probeScript.sml`.
-/

namespace Flapjack.Test.LoopAssignedVarsParity

open Flapjack

def originalSkip : List Nat := []
def originalAssign : List Nat := [7]
def originalSequence : List Nat := [7, 8]
def originalLongDiv : List Nat := [1, 2]
def originalLoadByte : List Nat := [9]

def probeSkip : LoopProg Nat := .skip
def probeAssign : LoopProg Nat := .assign 7 (.const 1)
def probeSequence : LoopProg Nat :=
  .seq (.assign 7 (.const 1)) (.load32 0 8)
def probeLongDiv : LoopProg Nat := .arith (.longDiv 1 2 3 4 5)
def probeLoadByte : LoopProg Nat := .loadByte 4 9

#guard loopAssignedVars probeSkip == originalSkip
#guard loopAssignedVars probeAssign == originalAssign
#guard loopAssignedVars probeSequence == originalSequence
#guard loopAssignedVars probeLongDiv == originalLongDiv
#guard loopAssignedVars probeLoadByte == originalLoadByte

/-! Cake `crep_to_loopProofScript.sml:355` `assigned_vars_MAPi_Assign`. -/

def probeAssignNames : LoopProg Nat :=
  loopNestedSeq (loopAssignNames (loopTempNames 3 3) (.const 0))

theorem loopAssignedVars_loopTempNames_fixture :
    loopAssignedVars probeAssignNames = [3, 4, 5] :=
  loopAssignedVars_loopTempNames 3 3 (.const 0)

/-! Cake `crep_to_loopProofScript.sml:1562` `assigned_vars_nested_seq_assign`. -/

def probeAssignPairs : LoopProg Nat :=
  loopNestedSeq (loopAssignPairs [3, 4, 5] [.const 0, .const 1, .const 2])

theorem loopAssignedVars_loopAssignPairs_fixture :
    loopAssignedVars probeAssignPairs = [3, 4, 5] :=
  loopAssignedVars_loopAssignPairs [3, 4, 5] [.const 0, .const 1, .const 2]
    (by decide)

/-! Cake `crep_to_loopProofScript.sml:342` `cut_sets_MAPi_Assign`. -/

theorem loopCutSets_loopAssignPairs_fixture :
    loopCutSets [9] probeAssignPairs = [3, 4, 5, 9] :=
  loopCutSets_loopAssignPairs [9] [3, 4, 5] [.const 0, .const 1, .const 2]
    (by decide)

/-! Cake `crep_to_loopProofScript.sml:368` `survives_MAPi_Assign`. -/

theorem loopSurvives_loopAssignPairs_fixture :
    loopSurvives 3 probeAssignPairs :=
  loopSurvives_loopAssignPairs 3 [3, 4, 5] [.const 0, .const 1, .const 2]
    (by decide)

def checkBool (name : String) (value : Bool) : IO Bool := do
  if value then
    IO.println s!"PASS {name}"
    pure true
  else
    IO.println s!"FAIL {name}"
    pure false

def survivesStructureGuard : Bool :=
  (loopAssignPairs [3, 4, 5] [.const 0, .const 1, .const 2]).length == 3

/-! Cake `loopPropsScript.sml:719` `survives_nested_seq_intro`. -/

theorem loopSurvives_nestedSeq_append_fixture :
    loopSurvives 3
      (loopNestedSeq
        (([.assign 3 (.const 0)] : List (LoopProg Nat)) ++
          [.assign 4 (.const 1)])) :=
  loopSurvives_nestedSeq_append 3 [.assign 3 (.const 0)]
    [.assign 4 (.const 1)]
    (by simp [loopNestedSeq, loopSurvives])
    (by simp [loopNestedSeq, loopSurvives])

def survivesAppendGuard : Bool :=
  (([.assign 3 (.const 0)] : List (LoopProg Nat)) ++
    ([.assign 4 (.const 1)] : List (LoopProg Nat))).length == 2

/-! Cake `loopPropsScript.sml:767` `cut_sets_nested_seq`. -/

theorem loopCutSets_nestedSeq_append_fixture :
    loopCutSets [9]
        (loopNestedSeq
          (([.assign 3 (.const 0)] : List (LoopProg Nat)) ++
            [.assign 4 (.const 1)])) =
      loopCutSets
        (loopCutSets [9]
          (loopNestedSeq ([.assign 3 (.const 0)] : List (LoopProg Nat))))
        (loopNestedSeq ([.assign 4 (.const 1)] : List (LoopProg Nat))) :=
  loopCutSets_nestedSeq_append [9] [.assign 3 (.const 0)]
    [.assign 4 (.const 1)]

def cutSetsAppendGuard : Bool :=
  loopCutSets [9]
      (loopNestedSeq
        (([.assign 3 (.const 0)] : List (LoopProg Nat)) ++
          [.assign 4 (.const 1)])) ==
    [3, 4, 9]

/-! Cake `loopPropsScript.sml:880` `assigned_vars_nested_seq_split`. -/

theorem loopAssignedVars_nestedSeq_append_fixture :
    loopAssignedVars
        (loopNestedSeq
          (([.assign 3 (.const 0)] : List (LoopProg Nat)) ++
            [.assign 4 (.const 1)])) =
      loopAssignedVars (loopNestedSeq ([.assign 3 (.const 0)] : List (LoopProg Nat))) ++
        loopAssignedVars (loopNestedSeq ([.assign 4 (.const 1)] : List (LoopProg Nat))) :=
  loopAssignedVars_nestedSeq_append [.assign 3 (.const 0)] [.assign 4 (.const 1)]

def assignedVarsSplitGuard : Bool :=
  loopAssignedVars
      (loopNestedSeq
        (([.assign 3 (.const 0)] : List (LoopProg Nat)) ++
          [.assign 4 (.const 1)])) ==
    [3, 4]

def check (name : String) (actual expected : List Nat) : IO Bool := do
  if actual == expected then
    IO.println s!"PASS {name}"
    pure true
  else
    IO.println s!"FAIL {name}: expected {repr expected}, got {repr actual}"
    pure false

def runChecks : IO Bool := do
  let results ← [
    check "assigned_vars skip" (loopAssignedVars probeSkip) originalSkip,
    check "assigned_vars assign" (loopAssignedVars probeAssign) originalAssign,
    check "assigned_vars sequence"
      (loopAssignedVars probeSequence) originalSequence,
    check "assigned_vars long division"
      (loopAssignedVars probeLongDiv) originalLongDiv,
    check "assigned_vars byte load"
      (loopAssignedVars probeLoadByte) originalLoadByte,
    check "assigned_vars MAPi Assign"
      (loopAssignedVars probeAssignNames) [3, 4, 5],
    check "assigned_vars nested_seq Assign"
      (loopAssignedVars probeAssignPairs) [3, 4, 5],
    check "cut_sets MAPi Assign"
      (loopCutSets [9] probeAssignPairs) [3, 4, 5, 9],
    checkBool "survives MAPi Assign" survivesStructureGuard,
    checkBool "survives nested_seq append" survivesAppendGuard,
    checkBool "cut_sets nested_seq append" cutSetsAppendGuard,
    checkBool "assigned_vars nested_seq split" assignedVarsSplitGuard ].mapM id
  pure (results.all id)

end Flapjack.Test.LoopAssignedVarsParity
