import Flapjack.LoopFfi

/-!
# Original-domain parity for `loopSem$sh_mem_store`

Reference: `cakeml/pancake/semantics/loopSemScript.sml:217-243`.
Expected source observations are checked in at
`scripts/hol-probes/loop_sem_sh_mem_store_probe.out`, generated by
`loop_sem_sh_mem_store_probeScript.sml`.  The alignment-sensitive case checks
that the aligned address is used only for the domain guard while the original
address remains in the mapped-write payload.
-/

namespace Flapjack.Test.LoopShMemStoreParity

open Flapjack

def returningState (shared : Bool) : LoopFfiState Nat Unit :=
  { locals := fun _ => none
    globals := fun _ => none
    memory := fun _ => none
    memaddrs := fun _ => true
    shMemaddrs := fun _ => shared
    byteAlign := id
    clock := 10
    bigEndian := false
    baseAddress := 0
    topAddress := 0
    ffi :=
      { oracle := fun _ state _ bytes => .returned state bytes
        state := ()
        ioEvents := [] }
    wordToBytes := fun value _ => [UInt8.ofNat value]
    wordOfBytes := fun _ bytes => bytes.head?.getD 0 |>.toNat
    valueToNat := id }

def storeState : LoopFfiState Nat Unit :=
  { returningState true with
    locals := fun name => if name == 1 then some 7 else none }

def storeZeroWidth : Bool :=
  match loopFfiShMemStore storeState 1 3 0 with
  | (.normal state, _) =>
      state.locals 1 == some 7 && state.ffi.ioEvents.length == 1
  | _ => false

def missingWord : Bool :=
  match loopFfiShMemStore (returningState true) 1 3 0 with
  | (.error _, _) => true
  | _ => false

def domainError : Bool :=
  match loopFfiShMemStore { storeState with shMemaddrs := fun _ => false } 1 3 0 with
  | (.error _, _) => true
  | _ => false

def alignedPayloadOriginal : Bool :=
  let state := { storeState with
    byteAlign := fun _ => 0
    shMemaddrs := fun address => address == 0
    locals := fun name => if name == 1 then some 171 else none }
  match loopFfiShMemStore state 1 3 1 with
  | (.normal state, _) =>
      state.ffi.ioEvents.head?.map (fun event => event.bytes) ==
        some [(UInt8.ofNat 171, UInt8.ofNat 171),
          (UInt8.ofNat 3, UInt8.ofNat 3)]
  | _ => false

def finalState : LoopFfiState Nat Unit :=
  { storeState with
    ffi :=
      { storeState.ffi with
        oracle := fun _ _ _ _ => .final .failed } }

def finalClearsLocals : Bool :=
  match loopFfiShMemStore finalState 1 3 0 with
  | (.finalFfi state _, _) => state.locals 1 == none
  | _ => false

#guard storeZeroWidth
#guard missingWord
#guard domainError
#guard alignedPayloadOriginal
#guard finalClearsLocals

def runChecks : IO Bool := do
  let checks : List (String × Bool) := [
    ("sh_mem_store returns normally and records the FFI event", storeZeroWidth),
    ("sh_mem_store rejects a missing word source", missingWord),
    ("sh_mem_store rejects an unmapped shared address", domainError),
    ("sh_mem_store sends original address bytes after alignment check",
      alignedPayloadOriginal),
    ("sh_mem_store clears locals on final FFI", finalClearsLocals)]
  let results ← checks.mapM fun (name, passed) => do
    if passed then
      IO.println s!"PASS {name}"
    else
      IO.println s!"FAIL {name}"
    pure passed
  pure (results.all id)

end Flapjack.Test.LoopShMemStoreParity
