import Flapjack.LoopAnalysis

/-!
# Original-domain parity for `assigned_vars`

`loopAssignedVars` is the Lean counterpart of
`cakeml/pancake/loopLangScript.sml:94-115`.  Expected observations are from
the checked-in HOL probe output generated by
`loop_lang_assigned_vars_probeScript.sml`.
-/

namespace Flapjack.Test.LoopAssignedVarsParity

open Flapjack

def originalSkip : List Nat := []
def originalAssign : List Nat := [7]
def originalSequence : List Nat := [7, 8]
def originalLongDiv : List Nat := [1, 2]
def originalLoadByte : List Nat := [9]

def probeSkip : LoopProg Nat := .skip
def probeAssign : LoopProg Nat := .assign 7 (.const 1)
def probeSequence : LoopProg Nat :=
  .seq (.assign 7 (.const 1)) (.load32 0 8)
def probeLongDiv : LoopProg Nat := .arith (.longDiv 1 2 3 4 5)
def probeLoadByte : LoopProg Nat := .loadByte 4 9

#guard loopAssignedVars probeSkip == originalSkip
#guard loopAssignedVars probeAssign == originalAssign
#guard loopAssignedVars probeSequence == originalSequence
#guard loopAssignedVars probeLongDiv == originalLongDiv
#guard loopAssignedVars probeLoadByte == originalLoadByte

def check (name : String) (actual expected : List Nat) : IO Bool := do
  if actual == expected then
    IO.println s!"PASS {name}"
    pure true
  else
    IO.println s!"FAIL {name}: expected {repr expected}, got {repr actual}"
    pure false

def runChecks : IO Bool := do
  let results ← [
    check "assigned_vars skip" (loopAssignedVars probeSkip) originalSkip,
    check "assigned_vars assign" (loopAssignedVars probeAssign) originalAssign,
    check "assigned_vars sequence"
      (loopAssignedVars probeSequence) originalSequence,
    check "assigned_vars long division"
      (loopAssignedVars probeLongDiv) originalLongDiv,
    check "assigned_vars byte load"
      (loopAssignedVars probeLoadByte) originalLoadByte ].mapM id
  pure (results.all id)

end Flapjack.Test.LoopAssignedVarsParity
