import Flapjack.LoopStateResult

/-!
# Original-domain parity for `loopSem$cut_res`

Reference: `cakeml/pancake/semantics/loopSemScript.sml:189-197`.
Expected observations are transcribed from
`scripts/hol-probes/loop_sem_cut_res_probe.out`, generated by
`loop_sem_cut_res_probeScript.sml`.  The comparison observes both result and
the relevant local/clock state after restriction, timeout, or decrement.
-/

namespace Flapjack.Test.LoopCutResParity

open Flapjack

def probeState (locals : Nat → Option LoopWordLoc) (clock : Nat) :
    LoopMachineState Nat :=
  { locals := locals
    globals := fun _ => none
    memory := fun _ => none
    mdomain := fun _ => false
    shMdomain := fun _ => false
    clock := clock
    code := []
    be := false
    ffi := 0
    baseAddr := 4
    topAddr := 100 }

def localOne : Nat → Option LoopWordLoc
  | 1 => some (.word 5)
  | _ => none

def localOneTwo : Nat → Option LoopWordLoc
  | 1 => some (.word 5)
  | 2 => some (.word 7)
  | _ => none

def observe (step : Option (LoopMachineResult Nat) × LoopMachineState Nat) :
    Option (LoopMachineResult Nat) × Option LoopWordLoc × Option LoopWordLoc × Nat :=
  (step.1, step.2.locals 1, step.2.locals 2, step.2.clock)

def shortCircuit : Bool :=
  observe (cutLoopResult [1]
    (some (.break 3), probeState (fun _ => none) 7)) ==
    (some (.break 3), none, none, 7)

def missingLive : Bool :=
  observe (cutLoopResult [1, 3]
    (none, probeState localOne 7)) ==
    (some .error, some (.word 5), none, 7)

def timeout : Bool :=
  observe (cutLoopResult [1]
    (none, probeState localOne 0)) ==
    (some .timeOut, none, none, 0)

def decrementAndCut : Bool :=
  observe (cutLoopResult [1]
    (none, probeState localOneTwo 5)) ==
    (none, some (.word 5), none, 4)

#guard shortCircuit
#guard missingLive
#guard timeout
#guard decrementAndCut

def runChecks : IO Bool := do
  let checks : List (String × Bool) := [
    ("cut_res short-circuits an existing result", shortCircuit),
    ("cut_res returns Error when a live local is missing", missingLive),
    ("cut_res clears locals on timeout", timeout),
    ("cut_res restricts locals and decrements clock", decrementAndCut)]
  let results ← checks.mapM fun (name, passed) => do
    if passed then
      IO.println s!"PASS {name}"
    else
      IO.println s!"FAIL {name}"
    pure passed
  pure (results.all id)

end Flapjack.Test.LoopCutResParity
