import Flapjack.Loop

/-!
# Original-domain parity for `nested_seq`

`loopNestedSeq` is the Lean counterpart of
`cakeml/pancake/loopLangScript.sml:72-75`.  Expected observations are from
the checked-in HOL probe generated by `loop_lang_nested_seq_probeScript.sml`.
-/

namespace Flapjack.Test.LoopNestedSeqParity

open Flapjack

def originalEmpty : LoopProg Nat := .skip
def originalOne : LoopProg Nat := .seq .skip .skip
def originalTwo : LoopProg Nat := .seq .tick (.seq .skip .skip)
def originalAssignLoad : LoopProg Nat :=
  .seq (.assign 1 (.const 7)) (.seq (.load32 0 2) .skip)

def probeEmpty : List (LoopProg Nat) := []
def probeOne : List (LoopProg Nat) := [.skip]
def probeTwo : List (LoopProg Nat) := [.tick, .skip]
def probeAssignLoad : List (LoopProg Nat) :=
  [.assign 1 (.const 7), .load32 0 2]

def sameExp : LoopExp Nat → LoopExp Nat → Bool
  | .const actual, .const expected => actual == expected
  | _, _ => false

def sameProg : LoopProg Nat → LoopProg Nat → Bool
  | .skip, .skip => true
  | .tick, .tick => true
  | .seq actualFirst actualSecond, .seq expectedFirst expectedSecond =>
      sameProg actualFirst expectedFirst && sameProg actualSecond expectedSecond
  | .assign actualName actualValue, .assign expectedName expectedValue =>
      actualName == expectedName && sameExp actualValue expectedValue
  | .load32 actualAddress actualDestination,
      .load32 expectedAddress expectedDestination =>
      actualAddress == expectedAddress && actualDestination == expectedDestination
  | _, _ => false

#guard sameProg (loopNestedSeq probeEmpty) originalEmpty
#guard sameProg (loopNestedSeq probeOne) originalOne
#guard sameProg (loopNestedSeq probeTwo) originalTwo
#guard sameProg (loopNestedSeq probeAssignLoad) originalAssignLoad

def check (name : String) (actual expected : LoopProg Nat) : IO Bool := do
  if sameProg actual expected then
    IO.println s!"PASS {name}"
    pure true
  else
    IO.println s!"FAIL {name}: expected {repr expected}, got {repr actual}"
    pure false

def runChecks : IO Bool := do
  let results ← [
    check "nested_seq empty" (loopNestedSeq probeEmpty) originalEmpty,
    check "nested_seq one statement" (loopNestedSeq probeOne) originalOne,
    check "nested_seq two statements" (loopNestedSeq probeTwo) originalTwo,
    check "nested_seq assign/load"
      (loopNestedSeq probeAssignLoad) originalAssignLoad ].mapM id
  pure (results.all id)

end Flapjack.Test.LoopNestedSeqParity
