import Flapjack.RiscV.PanMemory

/-!
# Fixed-width Pancake store parity

The expected memory cells below come directly from
`scripts/hol-probes/pan_fixed_store_probe.out`, generated by evaluating
CakeML's `mem_store_byte_def` and `mem_store_32_def` in
`pancake/semantics/panSemScript.sml:300-342`.

The probe uses a little-endian 64-bit word cell at byte address 8. The byte
store at address 9 changes only the second byte, while the aligned 32-bit
store writes `0x11223344` in little-endian order. Pancake rejects the
out-of-domain byte store and the unaligned 32-bit store.
-/

namespace Flapjack.Test.PanFixedStoreParity

open Flapjack Flapjack.RiscV

def originalProbeSource : String :=
  "cakeml/pancake/semantics/panSemScript.sml:300-342 (mem_store_byte_def/mem_store_32_def)"

def domain : PanMemoryDomain (Word 64) :=
  fun address => address == BitVec.ofNat 64 8

def memory : PanFlatMemory (Word 64) :=
  fun address =>
    if address == BitVec.ofNat 64 8 then
      some (BitVec.ofNat 64 0x0807060504030201)
    else none

def originalByteStoreHit : Option (Word 64) :=
  some (BitVec.ofNat 64 0x080706050403aa01)
def originalByteStoreMiss : Option (Word 64) := none
def originalStore32Hit : Option (Word 64) :=
  some (BitVec.ofNat 64 0x0807060511223344)
def originalStore32Unaligned : Option (Word 64) := none

def byteStoreHit : Option (Word 64) := do
  let updated ← panRiscVStoreByte domain memory
    (BitVec.ofNat 64 8) (BitVec.ofNat 64 9) (BitVec.ofNat 64 0xaa)
  updated (BitVec.ofNat 64 8)

def byteStoreMiss : Option (Word 64) := do
  let updated ← panRiscVStoreByte domain memory
    (BitVec.ofNat 64 8) (BitVec.ofNat 64 16) (BitVec.ofNat 64 0xaa)
  updated (BitVec.ofNat 64 8)

def store32Hit : Option (Word 64) := do
  let updated ← panRiscVStore32 domain memory
    (BitVec.ofNat 64 8) (BitVec.ofNat 64 8) (BitVec.ofNat 64 0x11223344)
  updated (BitVec.ofNat 64 8)

def store32Unaligned : Option (Word 64) := do
  let updated ← panRiscVStore32 domain memory
    (BitVec.ofNat 64 8) (BitVec.ofNat 64 9) (BitVec.ofNat 64 0x11223344)
  updated (BitVec.ofNat 64 8)

#guard originalProbeSource ==
  "cakeml/pancake/semantics/panSemScript.sml:300-342 (mem_store_byte_def/mem_store_32_def)"
#guard byteStoreHit == originalByteStoreHit
#guard byteStoreMiss == originalByteStoreMiss
#guard store32Hit == originalStore32Hit
#guard store32Unaligned == originalStore32Unaligned

end Flapjack.Test.PanFixedStoreParity
