import Flapjack.RiscV.PanMemory

/-!
# Fixed-width Pancake load parity

The expected values below come directly from
`scripts/hol-probes/pan_fixed_load_probe.out`, generated by evaluating
CakeML's `mem_load_byte_def` and `mem_load_32_def` in
`pancake/semantics/panSemScript.sml:86-109`.

The probe uses a little-endian 64-bit word cell at byte address 8. Pancake
rejects the unaligned 32-bit load at address 9 and reads the four bytes at
address 8 as `0x04030201`.
-/

namespace Flapjack.Test.PanFixedLoadParity

open Flapjack Flapjack.RiscV

def originalProbeSource : String :=
  "cakeml/pancake/semantics/panSemScript.sml:86-109 (mem_load_byte_def/mem_load_32_def)"

def domain : PanMemoryDomain (Word 64) :=
  fun address => address == BitVec.ofNat 64 8

def memory : PanFlatMemory (Word 64) :=
  fun address =>
    if address == BitVec.ofNat 64 8 then
      some (BitVec.ofNat 64 0x0807060504030201)
    else none

def originalByteHit : Option (Word 64) := some (BitVec.ofNat 64 2)
def originalByteMiss : Option (Word 64) := none
def originalLoad32Hit : Option (Word 64) := some (BitVec.ofNat 64 0x04030201)
def originalLoad32Unaligned : Option (Word 64) := none

def byteHit : Option (Word 64) :=
  panRiscVReadByte domain memory (BitVec.ofNat 64 8) (BitVec.ofNat 64 9)

def byteMiss : Option (Word 64) :=
  panRiscVReadByte domain memory (BitVec.ofNat 64 8) (BitVec.ofNat 64 16)

def load32Hit : Option (Word 64) :=
  panRiscVRead32 domain memory (BitVec.ofNat 64 8) (BitVec.ofNat 64 8)

def load32Unaligned : Option (Word 64) :=
  panRiscVRead32 domain memory (BitVec.ofNat 64 8) (BitVec.ofNat 64 9)

#guard originalProbeSource ==
  "cakeml/pancake/semantics/panSemScript.sml:86-109 (mem_load_byte_def/mem_load_32_def)"
#guard byteHit == originalByteHit
#guard byteMiss == originalByteMiss
#guard load32Hit == originalLoad32Hit
#guard load32Unaligned == originalLoad32Unaligned

end Flapjack.Test.PanFixedLoadParity
