import Flapjack.PanItreeFfi

/-!
Lean parity checks for `comp_ffi_def` and its three source branches.  The
corresponding direct HOL observations for `Ret`, `Tau`, successful return,
length mismatch, terminal oracle, and `div` branches are pinned in
`scripts/hol-probes/pan_itree_comp_ffi_probe.out`, generated by the
`pan_itree_comp_ffi_probeScript.sml` probe against
`pan_itreeSemScript.sml:1574-1630`; the fixture also checks source `div_Ret`
and `div_Tau` observations.
-/

namespace Flapjack.Test.PanItreeFfiParity

open Flapjack

def sourceProbeCommand : String := "scripts/hol-probes/regenerate.sh"

#guard sourceProbeCommand == "scripts/hol-probes/regenerate.sh"

def returningOracle : FfiOracle Nat := fun _ state _ bytes =>
  .returned (state + 1) bytes

def shortOracle : FfiOracle Nat := fun _ state _ bytes =>
  .returned (state + 1) (bytes.drop 1)

def finalOracle : FfiOracle Nat := fun _ _ _ _ => .final .failed

def returningWorld : PanFfiWorld Nat :=
  { oracle := returningOracle, state := 4 }

def shortWorld : PanFfiWorld Nat :=
  { oracle := shortOracle, state := 4 }

def finalWorld : PanFfiWorld Nat :=
  { oracle := finalOracle, state := 4 }

def returningTree : PanFfiTree (List UInt8) :=
  .vis (.extCall "foo") [1] [2, 3]
    (fun response => match response with
      | .returned bytes => .ret bytes
      | .failed => .ret []
      | .final _ => .ret [])

def shortTree : PanFfiTree (List UInt8) :=
  .vis (.extCall "foo") [1] [2, 3]
    (fun response => match response with
      | .failed => .ret [99]
      | _ => .ret [])

def finalTree : PanFfiTree (List UInt8) :=
  .vis (.extCall "foo") [] []
    (fun response => match response with
      | .final .failed => .ret [7]
      | _ => .ret [])

def observeReturn : Bool :=
  match compFfi 1 returningTree returningWorld with
  | some (.ret bytes, world) => bytes == [2, 3] && world.state == 5
  | _ => false

def observeLengthFailure : Bool :=
  match compFfi 1 shortTree shortWorld with
  | some (.ret bytes, world) => bytes == [99] && world.state == shortWorld.state
  | _ => false

def observeFinal : Bool :=
  match compFfi 1 finalTree finalWorld with
  | some (.ret bytes, world) => bytes == [7] && world.state == finalWorld.state
  | _ => false

def observeTau : Bool :=
  match compFfi 2 (.tau returningTree) returningWorld,
      compFfi 1 returningTree returningWorld with
  | some (.ret left, leftWorld), some (.ret right, rightWorld) =>
      left == right && leftWorld.state == rightWorld.state
  | _, _ => false

theorem retNotDivergent : ¬ panFfiDiv returningWorld (.ret [1]) := by
  exact panFfiDiv_ret returningWorld [1]

theorem tauDivergenceEquation (tree : PanFfiTree Nat) :
    panFfiDiv returningWorld (.tau tree) ↔ panFfiDiv returningWorld tree := by
  exact panFfiDiv_tau returningWorld tree

#guard observeReturn
#guard observeLengthFailure
#guard observeFinal
#guard observeTau

def runChecks : IO Bool := do
  if observeReturn then IO.println "PASS comp_ffi Oracle_return" else IO.println "FAIL comp_ffi Oracle_return"
  if observeLengthFailure then IO.println "PASS comp_ffi length failure" else IO.println "FAIL comp_ffi length failure"
  if observeFinal then IO.println "PASS comp_ffi Oracle_final" else IO.println "FAIL comp_ffi Oracle_final"
  if observeTau then IO.println "PASS comp_ffi Tau" else IO.println "FAIL comp_ffi Tau"
  IO.println "PASS div Ret/Tau equations"
  pure (observeReturn && observeLengthFailure && observeFinal && observeTau)

end Flapjack.Test.PanItreeFfiParity
