import Flapjack.Pancake.PanLang
import Flapjack.Pancake.PanLang.Prog

/-!
# Original-domain parity for `panLang$nested_seq`

The source definition is `cakeml/pancake/panLangScript.sml:211-213`.
The expected observations are generated by
`scripts/hol-probes/pan_lang_nested_seq_probeScript.sml` and checked in next
to that probe.  This test deliberately exercises the source AST, rather than
only the later loop-language copy of the same helper.
-/

namespace Flapjack.Test.PanNestedSeqParity

open Flapjack

def originalEmpty : Prog Nat := .skip
def originalOne : Prog Nat := .seq .skip .skip
def originalTwo : Prog Nat := .seq .tick (.seq .skip .skip)
def originalAssignSeq : Prog Nat :=
  .seq (.assign .local "x" (.const 7))
    (.seq (.assign .local "y" (.const 9)) .skip)

def probeEmpty : List (Prog Nat) := []
def probeOne : List (Prog Nat) := [.skip]
def probeTwo : List (Prog Nat) := [.tick, .skip]
def probeAssignSeq : List (Prog Nat) :=
  [.assign .local "x" (.const 7), .assign .local "y" (.const 9)]

def sameExp : Exp Nat → Exp Nat → Bool
  | .const actual, .const expected => actual == expected
  | _, _ => false

def sameProg : Prog Nat → Prog Nat → Bool
  | .skip, .skip => true
  | .tick, .tick => true
  | .seq actualFirst actualSecond, .seq expectedFirst expectedSecond =>
      sameProg actualFirst expectedFirst && sameProg actualSecond expectedSecond
  | .assign actualKind actualName actualValue,
      .assign expectedKind expectedName expectedValue =>
      actualKind == expectedKind && actualName == expectedName &&
        sameExp actualValue expectedValue
  | _, _ => false

#guard sameProg (nestedSeq probeEmpty) originalEmpty
#guard sameProg (nestedSeq probeOne) originalOne
#guard sameProg (nestedSeq probeTwo) originalTwo
#guard sameProg (nestedSeq probeAssignSeq) originalAssignSeq

def check (name : String) (actual expected : Prog Nat) : IO Bool := do
  if sameProg actual expected then
    IO.println s!"PASS {name}"
    pure true
  else
    IO.println s!"FAIL {name}: expected {repr expected}, got {repr actual}"
    pure false

def checkBool (name : String) (actual : Bool) : IO Bool := do
  if actual then
    IO.println s!"PASS {name}"
    pure true
  else
    IO.println s!"FAIL {name}"
    pure false

/-! Cake's `exp_ids_nested_seq`
    (`cakeml/pancake/proofs/pan_to_wordProofScript.sml:128`). -/

def expIdsProbe : List (Prog Nat) :=
  [.raise "E" (.const 1), .tick, .raise "F" (.const 2)]

theorem expIds_nestedSeq_fixture :
    expIds (nestedSeq expIdsProbe) = (expIdsProbe.map expIds).flatten :=
  expIds_nestedSeq expIdsProbe

def expIdsGuard : Bool :=
  expIds (nestedSeq expIdsProbe) == ["E", "F"]

#eval expIdsGuard
#guard expIdsGuard

/-! Cake's `pan_exps_of_nested_seq`
    (`cakeml/pancake/proofs/pan_to_wordProofScript.sml:1018`). -/

def expsProbe : List (Prog Nat) :=
  [.assign .local "x" (.const 1),
   .while (.var .local "x") (.raise "E" (.const 2))]

theorem expsOf_nestedSeq_fixture :
    expsOf (nestedSeq expsProbe) = (expsProbe.map expsOf).flatten :=
  expsOf_nestedSeq expsProbe

def expsOfGuard : Bool :=
  (expsOf (nestedSeq expsProbe)).length == 3 &&
    (expsProbe.map expsOf).flatten.length == 3

#eval expsOfGuard
#guard expsOfGuard

def runChecks : IO Bool := do
  let results ← [
    check "pan nested_seq empty" (nestedSeq probeEmpty) originalEmpty,
    check "pan nested_seq one statement" (nestedSeq probeOne) originalOne,
    check "pan nested_seq two statements" (nestedSeq probeTwo) originalTwo,
    check "pan nested_seq assign sequence"
      (nestedSeq probeAssignSeq) originalAssignSeq ].mapM id
  let expIdsOk ← checkBool "pan nested_seq exp_ids" expIdsGuard
  let expsOk ← checkBool "pan nested_seq exps_of" expsOfGuard
  pure (results.all id && expIdsOk && expsOk)

/-! ## Exact-carrier parity for `nested_seq` (bead flapjack-4ac.1.31)

`nestedSeqHOL` is the tagged port of `cakeml/pancake/panLangScript.sml:211-213`
over the exact `ProgHOL` carrier.  The guards below replay the four
`pan_lang_nested_seq_probe.out` rows (`empty`, `one`, `two`, `assign_seq`) at
width 8 through the exact definition. -/

private def s (str : String) : Flapjack.Basis.Pure.MlString.MlString :=
  Flapjack.Basis.Pure.MlString.ofString str

private def exactProbeAssignSeq : List (Flapjack.Pancake.PanLang.ProgHOL 8) :=
  [.assign .local (s "x") (.const 7), .assign .local (s "y") (.const 9)]

example :
    Flapjack.Pancake.PanLang.nestedSeqHOL
      ([] : List (Flapjack.Pancake.PanLang.ProgHOL 8)) =
        (.skip : Flapjack.Pancake.PanLang.ProgHOL 8) := rfl
example :
    Flapjack.Pancake.PanLang.nestedSeqHOL [.skip] =
      (.seq .skip .skip : Flapjack.Pancake.PanLang.ProgHOL 8) := rfl
example :
    Flapjack.Pancake.PanLang.nestedSeqHOL [.tick, .skip] =
      (.seq .tick (.seq .skip .skip) : Flapjack.Pancake.PanLang.ProgHOL 8) := rfl
example :
    Flapjack.Pancake.PanLang.nestedSeqHOL exactProbeAssignSeq =
      (.seq (.assign .local (s "x") (.const 7))
        (.seq (.assign .local (s "y") (.const 9)) .skip) :
          Flapjack.Pancake.PanLang.ProgHOL 8) := rfl

example (statements : List (Flapjack.Pancake.PanLang.ProgHOL 8)) :
    Flapjack.Pancake.PanLang.progOfHOL
        (Flapjack.Pancake.PanLang.nestedSeqHOL statements) =
      nestedSeq (statements.map Flapjack.Pancake.PanLang.progOfHOL) :=
  Flapjack.Pancake.PanLang.nestedSeqHOL_progOfHOL statements

example (statements : List (Prog (BitVec 8))) :
    Flapjack.Pancake.PanLang.progToHOL (nestedSeq statements) =
      Flapjack.Pancake.PanLang.nestedSeqHOL
        (statements.map Flapjack.Pancake.PanLang.progToHOL) :=
  Flapjack.Pancake.PanLang.nestedSeqHOL_progToHOL statements

/-! ## Executable routing helper (bead flapjack-4ac.1.31.1)

`nestedSeqCake` is the executable width-indexed helper that builds the nested
sequence through the tagged `nestedSeqHOL` (encode, apply, decode).  On
byte-ranged statements it computes the production `nestedSeq`, so the executed
compiler can route its initializer sequence through the reviewed definition
without changing output. -/

private def prodProbe : List (Prog (BitVec 8)) :=
  [.assign .local "x" (.const 7), .assign .local "y" (.const 9)]

example :
    Flapjack.Pancake.PanLang.nestedSeqCake prodProbe = nestedSeq prodProbe :=
  Flapjack.Pancake.PanLang.nestedSeqCake_eq prodProbe (by
    intro statement hmem
    simp only [prodProbe, List.mem_cons, List.not_mem_nil, or_false] at hmem
    rcases hmem with rfl | rfl
    · refine ⟨?_, ?_⟩
      · decide
      · trivial
    · refine ⟨?_, ?_⟩
      · decide
      · trivial)

example (statements : List (Prog (BitVec 8)))
    (hranged : ∀ statement ∈ statements,
      Flapjack.Pancake.PanLang.ProgByteRanged statement) :
    Flapjack.Pancake.PanLang.nestedSeqCake statements = nestedSeq statements :=
  Flapjack.Pancake.PanLang.nestedSeqCake_eq statements hranged

end Flapjack.Test.PanNestedSeqParity
