import Flapjack.PanStructsAfindi
import Flapjack.Pancake.Semantics.PanProps

namespace Flapjack.Test.PanStructsAfindiParity

/-! Direct parity for `pan_structs$afindi_def`
    (`pan_structsScript.sml:25`). -/
def entries : List (String × Nat) := [("a", 10), ("b", 20), ("c", 30)]

def parityGuard : Bool :=
  (afindi "a" ([] : List (String × Nat)) == none) &&
  (afindi "a" entries == some 0) &&
  (afindi "b" entries == some 1) &&
  (afindi "c" entries == some 2) &&
  (afindi "z" entries == none) &&
  (afindi "a" [("a", 10), ("b", 20), ("a", 30)] == some 0)

#eval parityGuard
#guard parityGuard

/-! Focused regressions for the ported Cake `pan_structs` `afindi` lemmas
    (`afindi_less_length`, `afindi_EL`, `afindi_append`, `afindi_MAP_eq`). -/

theorem afindi_less_length_fixture :
    afindi "b" entries = some 1 → (1 : Nat) < entries.length := by
  intro h
  exact afindi_less_length "b" entries 1 h

/-! Direct HOL-EVAL rows from `pan_structs_afindi_length_probe.out`, generated
from `pan_structsProofScript.sml:345`. The first and last successful matches
both satisfy the strict index bound stated by `afindi_less_length`. -/
def holAfIndiLengthGuard : Bool :=
  (afindi "a" ([ ("a", 10), ("b", 20) ] : List (String × Nat)) == some 0) &&
    (0 < ([ ("a", 10), ("b", 20) ] : List (String × Nat)).length) &&
  (afindi "c" entries == some 2) && (2 < entries.length)

#eval holAfIndiLengthGuard
#guard holAfIndiLengthGuard

theorem afindi_el_fst_fixture : (entries[1]?).map Prod.fst = some "b" := by
  have h : afindi "b" entries = some 1 := by simp [afindi, entries]
  exact afindi_el_fst "b" entries 1 h

/-! Direct HOL-EVAL rows from `pan_structs_afindi_el_probe.out` for first,
middle and last matches. Lean's `getElem?` result records the HOL `EL` index's
validity explicitly; the theorem gives the matching first component. -/
theorem afindi_el_fst_first_fixture : (entries[0]?).map Prod.fst = some "a" := by
  have h : afindi "a" entries = some 0 := by simp [afindi, entries]
  exact afindi_el_fst "a" entries 0 h

theorem afindi_el_fst_last_fixture : (entries[2]?).map Prod.fst = some "c" := by
  have h : afindi "c" entries = some 2 := by simp [afindi, entries]
  exact afindi_el_fst "c" entries 2 h

def holAfIndiElGuard : Bool :=
  (entries[0]?).map Prod.fst == some "a" &&
  (entries[1]?).map Prod.fst == some "b" &&
  (entries[2]?).map Prod.fst == some "c"

#eval holAfIndiElGuard
#guard holAfIndiElGuard

theorem afindi_append_fixture :
    afindi "d" (entries ++ [("d", 40)]) =
      (match afindi "d" entries with
        | none => (afindi "d" [("d", 40)]).map (fun index => index + entries.length)
        | some index => some index) := by
  exact afindi_append "d" entries [("d", 40)]

/-! Direct HOL-EVAL rows from `pan_structs_afindi_append_probe.out` cover a
prefix hit, an offset suffix hit, and an absent key. HOL writes the shifted
index as `LENGTH xs + i`; Lean's theorem uses the commuted `i + xs.length`. -/
def appendPrefix : List (String × Nat) := [("a", 1), ("b", 2)]
def appendSuffix : List (String × Nat) := [("b", 99)]
def suffixPrefix : List (String × Nat) := [("a", 1)]
def suffixEntries : List (String × Nat) := [("b", 2), ("b", 3)]

theorem afindi_append_prefix_hit_fixture :
    afindi "b" (appendPrefix ++ appendSuffix) = some 1 := by
  rw [afindi_append]
  simp [appendPrefix, afindi]

theorem afindi_append_suffix_hit_fixture :
    afindi "b" (suffixPrefix ++ suffixEntries) = some 1 := by
  rw [afindi_append]
  simp [suffixPrefix, suffixEntries, afindi]

theorem afindi_append_missing_fixture :
    afindi "z" (suffixPrefix ++ appendSuffix) = none := by
  rw [afindi_append]
  simp [suffixPrefix, appendSuffix, afindi]

def holAfIndiAppendGuard : Bool :=
  afindi "b" (appendPrefix ++ appendSuffix) == some 1 &&
  afindi "b" (suffixPrefix ++ suffixEntries) == some 1 &&
  afindi "z" (suffixPrefix ++ appendSuffix) == none

#eval holAfIndiAppendGuard
#guard holAfIndiAppendGuard

theorem afindi_append_value_fixture :
    afindi "d" (entries ++ [("d", 40)]) = some 3 := by
  simp [afindi, entries]

theorem afindi_map_eq_fixture :
    afindi "c" (entries.map (fun entry => (entry.1, entry.2 + 1))) =
      afindi "c" entries := by
  exact afindi_map_eq "c" (fun entry => (entry.1, entry.2 + 1)) entries
    (by intro x y _; rfl)

/-! Direct HOL-EVAL rows from `pan_structs_afindi_map_probe.out`, generated by
`pan_structs_afindi_map_probeScript.sml` from
`pan_structsProofScript.sml:356`. The concrete rows exercise both a present
key and an absent key under the theorem's key-preservation premise. -/
def holAfIndiMapGuard : Bool :=
  afindi "c" (entries.map (fun entry => (entry.1, entry.2 + 1))) == afindi "c" entries &&
  afindi "z" (entries.map (fun entry => (entry.1, entry.2 + 1))) == afindi "z" entries

#eval holAfIndiMapGuard
#guard holAfIndiMapGuard

theorem afindi_dropWhile_fixture :
    entries.dropWhile (fun entry => decide ("b" ≠ entry.1)) = entries.drop 1 := by
  rw [afindi_dropWhile]
  simp [afindi, entries]

/-! Direct HOL-EVAL rows from `pan_structs_dropwhile_afindi_probe.out` check
the first hit, a later hit and an absent key against HOL `DROP` and
`dropWhile_afindi`. -/
theorem afindi_dropWhile_first_fixture :
    entries.dropWhile (fun entry => decide ("a" ≠ entry.1)) = entries := by
  rw [afindi_dropWhile]
  simp [afindi, entries]

theorem afindi_dropWhile_missing_fixture :
    entries.dropWhile (fun entry => decide ("z" ≠ entry.1)) = [] := by
  rw [afindi_dropWhile]
  simp [afindi, entries]

def holAfIndiDropWhileGuard : Bool :=
  entries.dropWhile (fun entry => decide ("a" ≠ entry.1)) == entries &&
  entries.dropWhile (fun entry => decide ("b" ≠ entry.1)) == entries.drop 1 &&
  entries.dropWhile (fun entry => decide ("z" ≠ entry.1)) == []

#eval holAfIndiDropWhileGuard
#guard holAfIndiDropWhileGuard

theorem afindi_lookup_fixture :
    entries.lookup "b" = some 20 := by
  rw [afindi_lookup]
  simp [afindi, entries]

/-! Direct HOL-EVAL rows from `pan_structs_alookup_afindi_probe.out` exercise
present, missing and duplicate lookups for `ALOOKUP_eq_afindi`. -/
def duplicateEntries : List (String × Nat) := [("x", 1), ("x", 2)]

theorem afindi_lookup_missing_fixture :
    entries.lookup "z" = none := by
  rw [afindi_lookup]
  simp [afindi, entries]

theorem afindi_lookup_duplicate_fixture :
    duplicateEntries.lookup "x" = some 1 := by
  rw [afindi_lookup]
  simp [afindi, duplicateEntries]

def holALookupAfIndiGuard : Bool :=
  entries.lookup "b" == some 20 &&
  entries.lookup "z" == none &&
  duplicateEntries.lookup "x" == some 1

#eval holALookupAfIndiGuard
#guard holALookupAfIndiGuard
/-! Focused regressions for the ported Cake `pan_structs` `is_wf_shape_drop`
    lemma and its `lookupInfo` helper. -/

def context : StructContext :=
  [("t", { fields := [], size := 0 }),
   ("s", { fields := [("x", Shape.one)], size := 1 })]

theorem lookupInfo_isSome_drop_fixture :
    (lookupInfo "s" (context.drop 1)).isSome = true := by
  simp [context, lookupInfo]

theorem isWfShape_drop_fixture : isWfShape context (.named "s") = true := by
  have h : isWfShape (context.drop 1) (.named "s") = true := by
    simp [context, isWfShape, lookupInfo]
  exact isWfShape_drop context (.named "s") 1 h

/-! Focused regression for the ported Cake `pan_structs` `alookup_drop_helper`
    lemma. -/

theorem lookup_drop_helper_fixture :
    "b" ∉ (entries.take 1).map Prod.fst ∧ List.lookup "b" entries = some 20 :=
  lookup_drop_helper 1 entries "b" 20 (by decide) (by decide)

/-! Focused regression for the ported Cake `pan_structs`
    `map_uncurry_zip_again` lemma. -/

theorem list_zip_map_eq_fixture :
    (([1, 2] : List Nat).zip ([10, 20] : List Nat)).map
        (fun p => (p.1 + 1, p.2 * 2)) = ([2, 3] : List Nat).zip ([20, 40] : List Nat) :=
  list_zip_map_eq (fun n : Nat => n + 1) (fun n : Nat => n * 2) [1, 2] [10, 20] rfl

/-- Parity check for the Cake `UNCURRY_EQ_o_SND` lemma. -/
theorem prod_uncurry_const_eq_comp_snd_fixture :
    Function.uncurry (fun _ : Nat => (fun n : Nat => n + 1)) =
        (fun n : Nat => n + 1) ∘ Prod.snd :=
  prod_uncurry_const_eq_comp_snd (fun n : Nat => n + 1)

/-! Focused regressions for the ported Cake `pan_structs` `alookup_drop_helper`
    specialisation to `lookupInfo` and `size_of_sh_with_ctxt_drop`. -/

theorem lookupInfo_eq_lookup_fixture :
    lookupInfo "b" entries = List.lookup "b" entries :=
  lookupInfo_eq_lookup "b" entries

theorem lookupInfo_drop_helper_fixture :
    lookupInfo "s" context = some { fields := [("x", Shape.one)], size := 1 } :=
  lookupInfo_drop_helper 1 context "s" _ (by simp [context, lookupInfo]) (by decide)

theorem isWfShape_of_mem_fixture : isWfShape context (.named "s") = true :=
  isWfShape_of_mem (context := context) (shapes := [Shape.one, .named "s"])
    (by
      simp [isWfShape.isWfShapeList.eq_def, isWfShape, context, lookupInfo]) (by simp)

theorem shapeSizeWithContext_drop_fixture :
    shapeSizeWithContext (context.drop 1) (.named "s") =
      shapeSizeWithContext context (.named "s") := by
  have h : isWfShape (context.drop 1) (.named "s") = true := by
    simp [context, isWfShape, lookupInfo]
  exact shapeSizeWithContext_drop context (.named "s") 1 h (by decide)

/-! Focused regression for the ported Cake `size_of_sh_with_ctxt_eq`
    (`panPropsScript.sml:184`): for a shape well formed against the empty
    context the context-sensitive size is the context-free `shapeSize`. -/

theorem shapeSizeWithContext_eq_shapeSize_of_isWfShape_fixture :
    shapeSizeWithContext ([] : StructContext)
        (Shape.comb [Shape.one, Shape.one]) =
      Shape.shapeSize (Shape.comb [Shape.one, Shape.one]) :=
  shapeSizeWithContext_eq_shapeSize_of_isWfShape
    (Shape.comb [Shape.one, Shape.one])
    (by simp [isWfShape, isWfShape.isWfShapeList]) ([] : StructContext)

def shapeSizeWithContextGuard : Bool :=
  shapeSizeWithContext ([] : StructContext) (Shape.comb [Shape.one, Shape.one]) ==
    Shape.shapeSize (Shape.comb [Shape.one, Shape.one])

#eval shapeSizeWithContextGuard
#guard shapeSizeWithContextGuard

/-! Focused regression for the ported Cake `dropWhile_eq_cons_IMP`
    (`panPropsScript.sml:74`). -/

theorem dropWhile_eq_cons_imp_fixture :
    ∃ n, n < ([0, 1, 3] : List Nat).length ∧
      ([0, 1, 3] : List Nat)[n]? = some 3 ∧ (decide ((3 : Nat) < 2) = false) ∧
      ([0, 1, 3] : List Nat).drop n = [3] :=
  dropWhileEqConsImp (fun n : Nat => n < 2) [0, 1, 3] 3 [] (by decide)

#check @dropWhileEqConsImp

/-! Focused regression for the ported Cake `ALOOKUP_MAP3`/`ALOOKUP_MAP4`
    (`pan_globalsProofScript.sml:2841`/`:2851`). -/

theorem lookupInfo_map3_fixture :
    lookupInfo "b"
        (([("a", (1, 2)), ("b", (3, 4))] : InfoMap (Nat × Nat)).map
          (fun entry => (entry.1, entry.2.1, entry.2.2 + 1))) =
      (lookupInfo "b" ([("a", (1, 2)), ("b", (3, 4))] : InfoMap (Nat × Nat))).map
        (fun value => (value.1, value.2 + 1)) :=
  lookupInfo_map3 (fun x => x + 1) "b" _

theorem lookupInfo_map4_fixture :
    lookupInfo "b"
        (([("a", (1, 2, 3)), ("b", (4, 5, 6))] : InfoMap (Nat × Nat × Nat)).map
          (fun entry => (entry.1, entry.2.1, entry.2.2.1 + 1, entry.2.2.2))) =
      (lookupInfo "b"
        ([("a", (1, 2, 3)), ("b", (4, 5, 6))] : InfoMap (Nat × Nat × Nat))).map
        (fun value => (value.1, value.2.1 + 1, value.2.2)) :=
  lookupInfo_map4 (fun x => x + 1) "b" _

def lookupInfoMapGuard : Bool :=
  (lookupInfo "b"
      (([("a", (1, 2)), ("b", (3, 4))] : InfoMap (Nat × Nat)).map
        (fun entry => (entry.1, entry.2.1, entry.2.2 + 1))) ==
    some ((3, 5) : Nat × Nat)) &&
  (lookupInfo "z"
      (([("a", (1, 2, 3))] : InfoMap (Nat × Nat × Nat)).map
        (fun entry => (entry.1, entry.2.1, entry.2.2.1 + 1, entry.2.2.2)))).isNone

#eval lookupInfoMapGuard
#guard lookupInfoMapGuard


/-! Cake `pan_structs$compile_shape` / `compile_shapes` and
    `is_wf_shape_compile_shape` (`pan_structsProofScript.sml:298`). -/

def shapeContext : StructContext :=
  [("S", { fields := [("f1", Shape.one), ("f2", Shape.named "T")], size := 2 }),
   ("T", { fields := [("g", Shape.one)], size := 1 })]

def isCompiledS : Shape -> Bool
  | .comb [.one, .comb [.one]] => true
  | _ => false

theorem compileShape_isWfShape_fixture :
    isWfShape shapeContext (compileShape shapeContext (.named "S")) = true :=
  compileShape_isWfShape shapeContext (.named "S")

theorem compileShapes_eq_map_fixture :
    compileShapes shapeContext [Shape.one, Shape.named "S"] =
      [Shape.one, Shape.named "S"].map (compileShape shapeContext) :=
  compileShapes_eq_map shapeContext [Shape.one, Shape.named "S"]

def compileShapeGuard : Bool :=
  isCompiledS (compileShape shapeContext (.named "S")) &&
  isWfShape shapeContext (compileShape shapeContext (.named "S")) &&
  (match compileShape shapeContext (.named "Unknown") with
   | .one => true
   | _ => false)

#eval compileShapeGuard
#guard compileShapeGuard

/-! Cake's `dropWhile_MAP_helper`
    (`cakeml/pancake/proofs/pan_structsProofScript.sml:542`). -/

theorem dropWhile_map_helper_fixture :
    (([0, 1, 2, 3] : List Nat).map Nat.succ).dropWhile (fun n => n < 3) =
      (([0, 1, 2, 3] : List Nat).dropWhile (fun n => n < 2)).map Nat.succ :=
  dropWhile_map_helper (fun n => n < 2) (fun n => n < 3) Nat.succ
    [0, 1, 2, 3] [2, 3] rfl
    (by
      intro x hx
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hx
      rcases hx with rfl | rfl | rfl | rfl <;> decide)

def dropWhileMapGuard : Bool :=
  (([0, 1, 2, 3] : List Nat).map Nat.succ).dropWhile (fun n => n < 3) ==
    [3, 4]

#eval dropWhileMapGuard
#guard dropWhileMapGuard

/-! Cake `pan_structs` `struct_infos_ok` (`pan_structsProofScript.sml:68`) and
    its `_drop`/`_append` consequences (`:169`/`:198`). -/

example : structInfosOk ([] : StructContext) := by
  unfold structInfosOk
  refine ⟨?_, ?_, ?_, ?_⟩ <;> simp

def simpleContext : StructContext :=
  [("S", { fields := [("f", Shape.one)], size := 1 })]

example : structInfosOk simpleContext := by
  unfold structInfosOk
  refine ⟨?_, ?_, ?_, ?_⟩
  · intro entry hentry
    simp [simpleContext] at hentry
    rcases hentry with rfl
    decide
  · simp [simpleContext]
  · intro i name info hget shape hmem
    simp only [simpleContext] at hget
    cases i with
    | zero =>
        simp only [List.getElem?_cons_zero, Option.some.injEq] at hget
        obtain ⟨rfl, rfl⟩ := hget
        simp only [List.map_cons, List.map_nil, List.mem_cons,
          List.not_mem_nil, or_false] at hmem
        rcases hmem with rfl
        simp [isWfShape]
    | succ i =>
        simp only [List.getElem?_cons_succ, List.getElem?_nil] at hget
        simp at hget
  · intro entry hentry
    simp only [simpleContext, List.mem_cons, List.not_mem_nil, or_false] at hentry
    rcases hentry with rfl
    simp only [List.map_cons, List.map_nil]
    simp [shapeSizeWithContext]

theorem structInfosOk_drop_fixture (h : structInfosOk simpleContext) :
    structInfosOk (simpleContext.drop 1) :=
  structInfosOk_drop 1 simpleContext h

theorem structInfosOk_append_fixture (h : structInfosOk (simpleContext ++ [])) :
    structInfosOk ([] : StructContext) :=
  structInfosOk_append simpleContext [] h

/-! Cake's `struct_infos_ok_cons`
    (`cakeml/pancake/proofs/pan_structsProofScript.sml:132`). -/

def consInfo : StructInfo := { fields := [("f", Shape.one)], size := 1 }

example : structInfosOk ((("S" : StructName), consInfo) :: ([] : StructContext)) :=
  structInfosOk_cons [] "S" consInfo
    (by unfold structInfosOk; refine ⟨?_, ?_, ?_, ?_⟩ <;> simp)
    (by decide) (by simp)
    (by
      intro shape hmem
      simp only [consInfo, List.map_cons, List.map_nil, List.mem_cons,
        List.not_mem_nil, or_false] at hmem
      rcases hmem with rfl
      simp [isWfShape])
    (by simp [consInfo, shapeSizeWithContext])


/-! Cake's `map_fst_eq_alookup`
    (`cakeml/pancake/proofs/pan_structsProofScript.sml:278`). -/

def assocXs : List (String × Nat) := [("a", 1), ("b", 2)]

def assocYs : List (String × Nat) := [("a", 3), ("b", 4)]

def assocYsBool : List (String × Bool) := [("a", true), ("b", false)]

theorem map_fst_eq_lookup_fixture :
    ∃ i, afindi "b" assocXs = some i ∧ afindi "b" assocYs = some i ∧
      i < assocXs.length ∧ i < assocYs.length ∧
      (assocXs[i]?).map Prod.snd = some 2 ∧
      (assocYs[i]?).map Prod.snd = assocYs.lookup "b" :=
  map_fst_eq_lookup assocXs assocYs "b" (by decide) (by decide)

theorem map_fst_eq_lookup_different_value_types_fixture :
    ∃ i, afindi "b" assocXs = some i ∧ afindi "b" assocYsBool = some i ∧
      i < assocXs.length ∧ i < assocYsBool.length ∧
      (assocXs[i]?).map Prod.snd = some 2 ∧
      (assocYsBool[i]?).map Prod.snd = assocYsBool.lookup "b" :=
  map_fst_eq_lookup assocXs assocYsBool "b" (by decide) (by decide)

def afindiLookupGuard : Bool :=
  (assocXs.lookup "b" == some 2) &&
    (afindi "b" assocXs == afindi "b" assocYs) &&
    (assocYsBool.lookup "b" == some false) &&
    (afindi "b" assocXs == afindi "b" assocYsBool) &&
    (afindi "b" assocXs == some 1)

#eval afindiLookupGuard
#guard afindiLookupGuard

/-! Cake's `alookup_map_structs_ok`
    (`cakeml/pancake/proofs/pan_structsProofScript.sml:243`). -/

example (info : StructInfo)
    (hlookup : lookupInfo "S" simpleContext = some info)
    (hok : structInfosOk simpleContext) :
    (info.fields.map Prod.fst).Nodup :=
  lookupInfo_fields_nodup "S" simpleContext info hlookup hok

/-! Focused regression for HOL `fields_in_order_reorder_noop`
    (`pan_structsProofScript.sml:218`) using production compilation and field
    selection helpers. -/

def fieldOrderContext : StructPassContext :=
  { structs := [], locals := [], globals := [] }

def fieldOrderExpressions : List (FieldName × Exp Nat) :=
  [("a", .const 10), ("b", .const 20)]

def fieldOrderShapes : List (FieldName × Shape) :=
  [("a", .one), ("b", .comb [.one, .one])]

theorem fields_in_order_reorder_noop_fixture :
    structSelectFields fieldOrderShapes
        (structCompileExp.structCompileFields fieldOrderContext fieldOrderExpressions) =
      [.const 10, .const 20] := by
  simpa [fieldOrderExpressions] using
    fieldsInOrderReorderNoop fieldOrderContext fieldOrderExpressions fieldOrderShapes
      rfl (by decide)


/-! Cake's `mem_lookup_fromalist_some`
    (`cakeml/pancake/proofs/crep_to_loopProofScript.sml:3813`). -/

theorem list_lookup_of_mem_of_nodup_fixture :
    assocXs.lookup "b" = some 2 :=
  list_lookup_of_mem_of_nodup (by decide) (by decide)

def memLookupGuard : Bool :=
  assocXs.lookup "b" == some 2 && assocXs.lookup "a" == some 1

#eval memLookupGuard
#guard memLookupGuard

/-! Cake's `alookup_el_pair_eq_el`
    (`cakeml/pancake/proofs/crep_to_loopProofScript.sml:3921`). -/

theorem getElem_eq_of_lookup_eq_fixture :
    assocXs[1]'(by decide) = ("b", 2) :=
  getElem_eq_of_lookup_eq (by decide) (by decide) (by decide) (by decide)

def alookupElGuard : Bool :=
  (assocXs[1]?).map Prod.snd == some 2

#eval alookupElGuard
#guard alookupElGuard

end Flapjack.Test.PanStructsAfindiParity
