import Flapjack.Parser.Conversion

/-!
# Original-domain parity for `panLang$shape_val`

The source definition is `cakeml/pancake/panLangScript.sml:190-195`.
The expected observations are generated by
`scripts/hol-probes/pan_lang_shape_val_probeScript.sml`.
-/

namespace Flapjack.Test.PanShapeValParity

open Flapjack
open Flapjack.Parser

def zero (_ : Int) : Nat := 0

def sameExp : Exp Nat → Exp Nat → Bool
  | .const actual, .const expected => actual == expected
  | .rStruct actual, .rStruct expected => sameList actual expected
  | _, _ => false
where
  sameList : List (Exp Nat) → List (Exp Nat) → Bool
    | [], [] => true
    | actual :: actuals, expected :: expecteds =>
        sameExp actual expected && sameList actuals expecteds
    | _, _ => false

def oneExpected : Exp Nat := .const 0
def combExpected : Exp Nat := .rStruct [.const 0, .const 0, .const 0]
def namedExpected : Exp Nat := .const 0

#guard sameExp (Flapjack.Pancake.PanLang.shapeValViaHOL zero .one) oneExpected
#guard sameExp (Flapjack.Pancake.PanLang.shapeValViaHOL zero
  (.comb [.one, .named "n", .one])) combExpected
#guard sameExp (Flapjack.Pancake.PanLang.shapeValViaHOL zero
  (.named "n")) namedExpected

def check (name : String) (actual expected : Exp Nat) : IO Bool := do
  if sameExp actual expected then
    IO.println s!"PASS {name}"
    pure true
  else
    IO.println s!"FAIL {name}: expected {repr expected}, got {repr actual}"
    pure false

def runChecks : IO Bool := do
  let results ← [
    check "pan shape_val One" (Flapjack.Pancake.PanLang.shapeValViaHOL zero .one) oneExpected,
    check "pan shape_val Comb"
      (Flapjack.Pancake.PanLang.shapeValViaHOL zero (.comb [.one, .named "n", .one])) combExpected,
    check "pan shape_val Named"
      (Flapjack.Pancake.PanLang.shapeValViaHOL zero (.named "n")) namedExpected ].mapM id
  pure (results.all id)

end Flapjack.Test.PanShapeValParity
