import Flapjack.Language

/-!
# Original-domain parity for `panLang$with_shape`

The source definition is `cakeml/pancake/panLangScript.sml:216-219`.
Expected observations are generated by
`scripts/hol-probes/pan_lang_with_shape_probeScript.sml`.
-/

namespace Flapjack.Test.PanWithShapeParity

open Flapjack

def emptyShapes : List (List Nat) := []
def oneCombNamed : List Shape := [.one, .comb [.one, .one], .named "n"]
def shortShapes : List Shape := [.comb [.one, .one], .one]

#guard withShape ([] : List Shape) [1, 2, 3] == emptyShapes
#guard withShape oneCombNamed [1, 2, 3, 4, 5] ==
  [[1], [2, 3], [4]]
#guard withShape shortShapes [7] == [[7], []]

theorem withShape_length_fixture :
    (withShape oneCombNamed [1, 2, 3, 4]).length = oneCombNamed.length :=
  withShape_length oneCombNamed [1, 2, 3, 4]

theorem length_withShape_eq_shape_fixture :
    oneCombNamed.length = (withShape oneCombNamed [1, 2, 3, 4]).length :=
  length_withShape_eq_shape oneCombNamed [1, 2, 3, 4]
    (by simp [oneCombNamed, Shape.shapeSize])

def lengthGuard : Bool :=
  (withShape oneCombNamed [1, 2, 3, 4]).length == oneCombNamed.length

#eval lengthGuard
#guard lengthGuard

theorem all_distinct_withShape_fixture :
    ((withShape oneCombNamed [1, 2, 3, 4])[1]'(by rw [withShape_length]; decide)).Nodup :=
  all_distinct_withShape oneCombNamed [1, 2, 3, 4] 1 (by decide) (by decide)
    (by simp [oneCombNamed, Shape.shapeSize])

def allDistinctGuard : Bool :=
  ((withShape oneCombNamed [1, 2, 3, 4])[1]'(by rw [withShape_length]; decide)).Nodup

#eval allDistinctGuard
#guard allDistinctGuard

theorem mem_withShape_length_fixture :
    (withShape oneCombNamed [1, 2, 3, 4])[1]'(by rw [withShape_length]; decide) ∈
      withShape oneCombNamed [1, 2, 3, 4] :=
  mem_withShape_length oneCombNamed [1, 2, 3, 4] 1
    (by simp [oneCombNamed, Shape.shapeSize]) (by decide)

theorem mem_of_withShape_mem_fixture :
    (2 : Nat) ∈ ([1, 2, 3, 4] : List Nat) :=
  mem_of_withShape_mem oneCombNamed [1, 2, 3, 4] 1 2
    (by rw [withShape_length]; decide)
    (by simp [oneCombNamed, Shape.shapeSize])
    (by simp [withShape, oneCombNamed, Shape.shapeSize])

theorem withShape_getElem_eq_take_drop_fixture :
    (withShape oneCombNamed [1, 2, 3, 4])[1]'(by rw [withShape_length]; decide) =
      (([1, 2, 3, 4] : List Nat).drop
          (Shape.shapeSize (.comb (oneCombNamed.take 1)))).take
        (Shape.shapeSize (oneCombNamed[1]'(by decide))) :=
  withShape_getElem_eq_take_drop oneCombNamed [1, 2, 3, 4] 1
    (by simp [oneCombNamed, Shape.shapeSize]) (by decide)

def withShapeMembersGuard : Bool :=
  ((withShape oneCombNamed [1, 2, 3, 4])[1]'(by rw [withShape_length]; decide)).all
    (fun value => ([1, 2, 3, 4] : List Nat).contains value)

#eval withShapeMembersGuard
#guard withShapeMembersGuard

def checkAllDistinct (name : String) : IO Bool := do
  if ((withShape oneCombNamed [1, 2, 3, 4])[1]'(by rw [withShape_length]; decide)).Nodup then
    IO.println s!"PASS {name}"
    pure true
  else
    IO.println s!"FAIL {name}"
    pure false

def checkLength (name : String) : IO Bool := do
  if (withShape oneCombNamed [1, 2, 3, 4]).length == oneCombNamed.length then
    IO.println s!"PASS {name}"
    pure true
  else
    IO.println s!"FAIL {name}"
    pure false

def check (name : String) (actual expected : List (List Nat)) : IO Bool := do
  if actual == expected then
    IO.println s!"PASS {name}"
    pure true
  else
    IO.println s!"FAIL {name}: expected {repr expected}, got {repr actual}"
    pure false

def checkMembers (name : String) (actual expected : List Nat) : IO Bool := do
  if actual == expected then
    IO.println s!"PASS {name}"
    pure true
  else
    IO.println s!"FAIL {name}: expected {repr expected}, got {repr actual}"
    pure false

def runChecks : IO Bool := do
  let results ← [
    check "pan with_shape empty" (withShape [] [1, 2, 3]) [],
    check "pan with_shape one/comb/named"
      (withShape oneCombNamed [1, 2, 3, 4, 5]) [[1], [2, 3], [4]],
    check "pan with_shape short input"
      (withShape shortShapes [7]) [[7], []] ].mapM id
  let lengthOk ← checkLength "pan with_shape length"
  let allDistinctOk ← checkAllDistinct "pan all_distinct_with_shape"
  let membershipOk ← checkMembers "pan with_shape membership"
    ((withShape oneCombNamed [1, 2, 3, 4])[1]'(by rw [withShape_length]; decide)) [2, 3]
  pure (results.all id && lengthOk && allDistinctOk && membershipOk)

end Flapjack.Test.PanWithShapeParity
