import Flapjack.RiscV.Encoding.NativeInstruction.Agreement

/-! Finite full-constructor regressions comparing two distinct implementations:
the historical numeric reference encoder `EncodingReference.encodeInstructionWeighted`
and the production route `L3.Encode (nativeInstruction i)`. Each fixture pins one
concrete constructor/operand case of the universal `encodeInstructionWeighted_native`
agreement theorem. These checks do not prove universal encoding agreement or
cross-language equivalence on their own. The universal agreement theorem is
Flapjack-specific infrastructure and intentionally untagged. -/
namespace Flapjack.RiscV
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.add (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.add (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.add (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.add (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.add (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.add (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sub (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sub (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sub (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sub (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sub (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sub (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.addW (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.addW (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.addW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.addW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.addW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.addW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.subW (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.subW (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.subW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.subW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.subW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.subW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.and (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.and (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.and (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.and (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.and (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.and (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.or (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.or (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.or (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.or (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.or (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.or (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.xor (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.xor (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.xor (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.xor (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.xor (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.xor (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.addi (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.addi (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.addi (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.addi (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.addi (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.addi (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.addiW (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.addiW (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.addiW (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.addiW (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.addiW (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.addiW (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.andi (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.andi (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.andi (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.andi (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.andi (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.andi (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.ori (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.ori (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.ori (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.ori (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.ori (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.ori (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.xori (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.xori (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.xori (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.xori (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.xori (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.xori (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.mul (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.mul (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.mul (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.mul (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.mul (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.mul (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.mulW (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.mulW (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.mulW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.mulW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.mulW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.mulW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.mulHU (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.mulHU (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.mulHU (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.mulHU (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.mulHU (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.mulHU (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sll (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sll (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sll (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sll (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sll (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sll (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.srl (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.srl (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.srl (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.srl (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.srl (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.srl (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sra (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sra (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sra (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sra (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sra (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sra (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sllW (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sllW (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sllW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sllW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sllW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sllW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.srlW (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.srlW (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.srlW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.srlW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.srlW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.srlW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sraW (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sraW (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sraW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sraW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sraW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sraW (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.slli (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.slli (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.slli (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.slli (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.slli (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.slli (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.srli (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.srli (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.srli (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.srli (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.srli (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.srli (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.srai (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.srai (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.srai (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.srai (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.srai (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.srai (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.slliW (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.slliW (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.slliW (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.slliW (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.slliW (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.slliW (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.srliW (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.srliW (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.srliW (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.srliW (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.srliW (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.srliW (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sraiW (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.sraiW (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sraiW (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.sraiW (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sraiW (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.sraiW (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.slt (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.slt (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.slt (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.slt (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.slt (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.slt (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.slti (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.slti (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.slti (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.slti (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.slti (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.slti (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sltu (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sltu (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sltu (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sltu (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sltu (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.sltu (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sltiu (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.sltiu (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sltiu (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.sltiu (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.sltiu (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.sltiu (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.lui (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.lui (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.lui (0 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.lui (0 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.lui (0 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.lui (0 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.auipc (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.auipc (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.auipc (0 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.auipc (0 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.auipc (0 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.auipc (0 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.divU (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.divU (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.divU (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.divU (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.divU (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.divU (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.remU (0 : Fin 32) (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.remU (0 : Fin 32) (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.remU (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.remU (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.remU (0 : Fin 32) (31 : Fin 32) (17 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.remU (0 : Fin 32) (31 : Fin 32) (17 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchEq (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchEq (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchEq (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchEq (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchEq (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchEq (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchNe (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchNe (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchNe (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchNe (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchNe (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchNe (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchLt (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchLt (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchLt (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchLt (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchLt (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchLt (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchGe (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchGe (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchGe (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchGe (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchGe (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchGe (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchLtU (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchLtU (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchLtU (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchLtU (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchLtU (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchLtU (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchGeU (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchGeU (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchGeU (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchGeU (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.branchGeU (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.branchGeU (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.jal (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.jal (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.jal (0 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.jal (0 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.jal (0 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.jal (0 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.jalr (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.jalr (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.jalr (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.jalr (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.jalr (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.jalr (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.ecall) = L3.Encode (nativeInstruction (Instruction.ecall)) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.ecall) = L3.Encode (nativeInstruction (Instruction.ecall)) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.ecall) = L3.Encode (nativeInstruction (Instruction.ecall)) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadByte (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.loadByte (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadByte (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.loadByte (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadByte (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.loadByte (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadByteSigned (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.loadByteSigned (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadByteSigned (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.loadByteSigned (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadByteSigned (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.loadByteSigned (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeByte (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.storeByte (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeByte (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.storeByte (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeByte (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.storeByte (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadHalf (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.loadHalf (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadHalf (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.loadHalf (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadHalf (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.loadHalf (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadHalfSigned (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.loadHalfSigned (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadHalfSigned (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.loadHalfSigned (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadHalfSigned (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.loadHalfSigned (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeHalf (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.storeHalf (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeHalf (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.storeHalf (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeHalf (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.storeHalf (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.load32 (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.load32 (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.load32 (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.load32 (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.load32 (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.load32 (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.store32 (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.store32 (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.store32 (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.store32 (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.store32 (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.store32 (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadWord (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.loadWord (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadWord (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.loadWord (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadWord (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.loadWord (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeWord (0 : Fin 32) (0 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.storeWord (0 : Fin 32) (0 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeWord (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.storeWord (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeWord (0 : Fin 32) (31 : Fin 32)) = L3.Encode (nativeInstruction (Instruction.storeWord (0 : Fin 32) (31 : Fin 32))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadWordOffset (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.loadWordOffset (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadWordOffset (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.loadWordOffset (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadWordOffset (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.loadWordOffset (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeWordOffset (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.storeWordOffset (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeWordOffset (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.storeWordOffset (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeWordOffset (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.storeWordOffset (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadByteOffset (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.loadByteOffset (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadByteOffset (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.loadByteOffset (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadByteOffset (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.loadByteOffset (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeByteOffset (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.storeByteOffset (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeByteOffset (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.storeByteOffset (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeByteOffset (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.storeByteOffset (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadHalfOffset (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.loadHalfOffset (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadHalfOffset (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.loadHalfOffset (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.loadHalfOffset (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.loadHalfOffset (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeHalfOffset (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.storeHalfOffset (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeHalfOffset (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.storeHalfOffset (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.storeHalfOffset (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.storeHalfOffset (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.load32Offset (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.load32Offset (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.load32Offset (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.load32Offset (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.load32Offset (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.load32Offset (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.store32Offset (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.store32Offset (0 : Fin 32) (0 : Fin 32) (0 : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.store32Offset (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.store32Offset (0 : Fin 32) (31 : Fin 32) (0xffffffffffffffff : BitVec 64))) := by decide
example : EncodingReference.encodeInstructionWeighted (width := 64) (Instruction.store32Offset (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64)) = L3.Encode (nativeInstruction (Instruction.store32Offset (0 : Fin 32) (31 : Fin 32) (0x8123456789abcdef : BitVec 64))) := by decide

-- Universal statements and proof axioms, independent of the finite fixtures.
example (i : Instruction 64) :
    EncodingReference.encodeInstructionWeighted i = L3.Encode (nativeInstruction i) :=
  encodeInstructionWeighted_native i
example (i : Instruction 64) : encodeInstruction i = L3.Encode (nativeInstruction i) :=
  encodeInstruction_native i
example (is : List (Instruction 64)) :
    encodeInstructions is = is.flatMap
      (fun i => Compiler.Encoders.RiscV.Target.riscvEncode (nativeInstruction i)) :=
  encodeInstructions_native is
#print axioms encodeInstruction_native
#print axioms encodeInstructionWeighted_native
#print axioms encodeInstructionBytes_native
#print axioms encodeInstructions_native

end Flapjack.RiscV
