import Flapjack.HolRef
import Flapjack.Pancake.CrepLang

/-!
Crepe language properties from `cakeml/pancake/semantics/crepPropsScript.sml`.

This module depends on the language definitions and helpers in `CrepLang`;
the language module does not depend on these semantic properties.
-/

namespace Flapjack

universe u

/-! Faithful port of Cake `crepProps$length_load_globals_eq_read_size`
    (`cakeml/pancake/semantics/crepPropsScript.sml:467`). -/
@[hol "cakeml/pancake/semantics/crepPropsScript.sml" "length_load_globals_eq_read_size"]
theorem loadGlobals_length {α : Type u} [OfNat α 1] [Add α]
    (address : α) (count : Nat) :
    (loadGlobals address count).length = count := by
  induction count generalizing address with
  | zero => rfl
  | succ count ih => simp [loadGlobals, ih]

/-! Faithful port of Cake `crepProps$el_load_globals_elem`
    (`cakeml/pancake/semantics/crepPropsScript.sml:474`). -/
@[hol "cakeml/pancake/semantics/crepPropsScript.sml" "el_load_globals_elem"]
theorem loadGlobals_getElem (address count n : Nat) (h : n < count) :
    (loadGlobals address count)[n]? = some (.loadGlob (address + n)) := by
  induction count generalizing address n with
  | zero => simp at h
  | succ count ih =>
      cases n with
      | zero => simp [loadGlobals]
      | succ k =>
          simp only [loadGlobals, List.getElem?_cons_succ]
          rw [ih (address + 1) k (by omega)]
          congr 1
          simp [Nat.add_comm, Nat.add_left_comm]

/-- Faithful port of Cake `crepProps$var_cexp_load_globals_empty`
    (`cakeml/pancake/semantics/crepPropsScript.sml:698`): the loads generated by
    `load_globals` contain no local variables. -/
@[hol "cakeml/pancake/semantics/crepPropsScript.sml" "var_cexp_load_globals_empty"]
theorem loadGlobals_crepExpVars_empty {α : Type u} [OfNat α 1] [Add α]
    (address : α) (count : Nat) :
    (loadGlobals address count).flatMap crepExpVars = [] := by
  induction count generalizing address with
  | zero => simp [loadGlobals]
  | succ count ih => simp [loadGlobals, ih, crepExpVars]

/-! Faithful port of Cake `crepProps$assigned_free_vars_store_globals_empty`
    (`cakeml/pancake/semantics/crepPropsScript.sml:458`). -/
@[hol "cakeml/pancake/semantics/crepPropsScript.sml" "assigned_free_vars_store_globals_empty"]
theorem crepAssignedFreeVars_nestedSeq_storeGlobals {α : Type u}
    [OfNat α 1] [Add α]
    (address : α) (values : List (CrepExp α)) :
    crepAssignedFreeVars (crepNestedSeq (storeGlobals address values)) = [] := by
  induction values generalizing address with
  | nil => simp [storeGlobals, crepNestedSeq, crepAssignedFreeVars]
  | cons value values ih =>
      simp [storeGlobals, crepNestedSeq, crepAssignedFreeVars, ih]

/-! Faithful port of Cake `crepProps$assigned_vars_store_globals_empty`
    (`cakeml/pancake/semantics/crepPropsScript.sml:449`). -/
@[hol "cakeml/pancake/semantics/crepPropsScript.sml" "assigned_vars_store_globals_empty"]
theorem crepAssignedVars_nestedSeq_storeGlobals {α : Type u}
    [OfNat α 1] [Add α]
    (address : α) (values : List (CrepExp α)) :
    crepAssignedVars (crepNestedSeq (storeGlobals address values)) = [] := by
  induction values generalizing address with
  | nil => simp [storeGlobals, crepNestedSeq, crepAssignedVars]
  | cons value values ih =>
      simp [storeGlobals, crepNestedSeq, crepAssignedVars, ih]

end Flapjack
