import Flapjack.RiscV.L3.Defs.ImmediateShift

/-! Evaluated immediate-shift instruction equations (HOL `riscv_step` shift group).

The HOL `riscv_stepScript.sml` `class` evaluator normalises
`dfn'SLLI_def`/`dfn'SRLI_def`/`dfn'SRAI_def` into explicit record-update
equations.  Every write theorem carries the original three hypotheses: the
legality condition `~(ArchBase = 0w /\ word_bit 5 imm)`, the invalid-selector
exclusion `ArchBase <> 1w`, and `rd <> 0w`.  SRLI/SRAI thread the literal second
mode check and use the low32 extension on RV32I.  The companion `X_NOP` theorem,
generated by the `class_rd0` factory through `utilsLib.save_thms`, carries
`rd = 0w` and retains the same legality and invalid-selector hypotheses,
then reduces to the unchanged state; the original companion exists in
the exported `riscv_stepTheory` signature (its name is produced by the factory
rather than written as a literal `val` binding, which is why the reference
checker registers the generated family narrowly). -/
namespace Flapjack.RiscV.L3.Step

open Flapjack.RiscV.L3

@[hol "HOL/examples/l3-machine-code/riscv/step/riscv_stepScript.sml" "SLLI"]
theorem dfnSLLI (rd rs1 : BitVec 5) (imm : BitVec 6) (s : riscv_state)
    (hleg : ¬ ((s.c_MCSR s.procID).mcpuid.ArchBase = 0 ∧ imm.getLsbD 5))
    (harch : (s.c_MCSR s.procID).mcpuid.ArchBase ≠ 1)
    (hrd : rd ≠ 0) :
    «dfn'SLLI» (rd, (rs1, imm)) s =
      { s with
        c_gpr :=
          holUpdate s.procID
            (holUpdate rd
              (if rs1 = 0 then 0 else s.c_gpr s.procID rs1 <<< imm.toNat)
              (s.c_gpr s.procID))
            s.c_gpr } := by
  simp only [«dfn'SLLI», in32BitMode, curArch, architecture, MCSR]
  have hcases : ∀ b : BitVec 2, b = 0 ∨ b = 1 ∨ b = 2 ∨ b = 3 := by decide
  rcases hcases (s.c_MCSR s.procID).mcpuid.ArchBase with h | h | h | h <;>
    simp_all [«write'GPR», «write'gpr», GPR, gpr, beq_iff_eq, ne_eq]
  all_goals by_cases hr : rs1 = 0 <;> simp_all [BitVec.zero_shiftLeft]

@[hol "HOL/examples/l3-machine-code/riscv/step/riscv_stepScript.sml" "SRLI"]
theorem dfnSRLI (rd rs1 : BitVec 5) (imm : BitVec 6) (s : riscv_state)
    (hleg : ¬ ((s.c_MCSR s.procID).mcpuid.ArchBase = 0 ∧ imm.getLsbD 5))
    (harch : (s.c_MCSR s.procID).mcpuid.ArchBase ≠ 1)
    (hrd : rd ≠ 0) :
    «dfn'SRLI» (rd, (rs1, imm)) s =
      { s with
        c_gpr :=
          holUpdate s.procID
            (holUpdate rd
              (if rs1 = 0 then 0
               else if (s.c_MCSR s.procID).mcpuid.ArchBase = 0 then
                 (BitVec.setWidth 64 (holWordExtract 32 31 0 (s.c_gpr s.procID rs1))) >>> imm.toNat
               else s.c_gpr s.procID rs1 >>> imm.toNat)
              (s.c_gpr s.procID))
            s.c_gpr } := by
  simp only [«dfn'SRLI», in32BitMode, curArch, architecture, MCSR]
  have hcases : ∀ b : BitVec 2, b = 0 ∨ b = 1 ∨ b = 2 ∨ b = 3 := by decide
  rcases hcases (s.c_MCSR s.procID).mcpuid.ArchBase with h | h | h | h <;>
    simp_all [«write'GPR», «write'gpr», GPR, gpr, beq_iff_eq, ne_eq]
  all_goals by_cases hr : rs1 = 0 <;> simp_all [holWordExtract, BitVec.zero_ushiftRight]

@[hol "HOL/examples/l3-machine-code/riscv/step/riscv_stepScript.sml" "SRAI"]
theorem dfnSRAI (rd rs1 : BitVec 5) (imm : BitVec 6) (s : riscv_state)
    (hleg : ¬ ((s.c_MCSR s.procID).mcpuid.ArchBase = 0 ∧ imm.getLsbD 5))
    (harch : (s.c_MCSR s.procID).mcpuid.ArchBase ≠ 1)
    (hrd : rd ≠ 0) :
    «dfn'SRAI» (rd, (rs1, imm)) s =
      { s with
        c_gpr :=
          holUpdate s.procID
            (holUpdate rd
              (if rs1 = 0 then 0
               else BitVec.sshiftRight
                 (if (s.c_MCSR s.procID).mcpuid.ArchBase = 0 then
                   BitVec.signExtend 64 (holWordExtract 32 31 0 (s.c_gpr s.procID rs1))
                 else s.c_gpr s.procID rs1) imm.toNat)
              (s.c_gpr s.procID))
            s.c_gpr } := by
  simp only [«dfn'SRAI», in32BitMode, curArch, architecture, MCSR]
  have hcases : ∀ b : BitVec 2, b = 0 ∨ b = 1 ∨ b = 2 ∨ b = 3 := by decide
  rcases hcases (s.c_MCSR s.procID).mcpuid.ArchBase with h | h | h | h <;>
    simp_all [«write'GPR», «write'gpr», GPR, gpr, beq_iff_eq, ne_eq]
  all_goals by_cases hr : rs1 = 0 <;> simp_all [holWordExtract, BitVec.zero_sshiftRight]

@[hol "HOL/examples/l3-machine-code/riscv/step/riscv_stepScript.sml" "SLLI_NOP"]
theorem dfnSLLINop (rd rs1 : BitVec 5) (imm : BitVec 6) (s : riscv_state)
    (hleg : ¬ ((s.c_MCSR s.procID).mcpuid.ArchBase = 0 ∧ imm.getLsbD 5))
    (harch : (s.c_MCSR s.procID).mcpuid.ArchBase ≠ 1)
    (hrd : rd = 0) :
    «dfn'SLLI» (rd, (rs1, imm)) s = s := by
  simp only [«dfn'SLLI», «write'GPR», hrd]
  have hcases : ∀ b : BitVec 2, b = 0 ∨ b = 1 ∨ b = 2 ∨ b = 3 := by decide
  rcases hcases (s.c_MCSR s.procID).mcpuid.ArchBase with h | h | h | h <;>
    simp_all [in32BitMode, curArch, architecture, MCSR, beq_iff_eq, ne_eq]

@[hol "HOL/examples/l3-machine-code/riscv/step/riscv_stepScript.sml" "SRLI_NOP"]
theorem dfnSRLINop (rd rs1 : BitVec 5) (imm : BitVec 6) (s : riscv_state)
    (hleg : ¬ ((s.c_MCSR s.procID).mcpuid.ArchBase = 0 ∧ imm.getLsbD 5))
    (harch : (s.c_MCSR s.procID).mcpuid.ArchBase ≠ 1)
    (hrd : rd = 0) :
    «dfn'SRLI» (rd, (rs1, imm)) s = s := by
  simp only [«dfn'SRLI», «write'GPR», hrd]
  have hcases : ∀ b : BitVec 2, b = 0 ∨ b = 1 ∨ b = 2 ∨ b = 3 := by decide
  rcases hcases (s.c_MCSR s.procID).mcpuid.ArchBase with h | h | h | h <;>
    simp_all [in32BitMode, curArch, architecture, MCSR, beq_iff_eq, ne_eq]

@[hol "HOL/examples/l3-machine-code/riscv/step/riscv_stepScript.sml" "SRAI_NOP"]
theorem dfnSRAINop (rd rs1 : BitVec 5) (imm : BitVec 6) (s : riscv_state)
    (hleg : ¬ ((s.c_MCSR s.procID).mcpuid.ArchBase = 0 ∧ imm.getLsbD 5))
    (harch : (s.c_MCSR s.procID).mcpuid.ArchBase ≠ 1)
    (hrd : rd = 0) :
    «dfn'SRAI» (rd, (rs1, imm)) s = s := by
  simp only [«dfn'SRAI», «write'GPR», hrd]
  have hcases : ∀ b : BitVec 2, b = 0 ∨ b = 1 ∨ b = 2 ∨ b = 3 := by decide
  rcases hcases (s.c_MCSR s.procID).mcpuid.ArchBase with h | h | h | h <;>
    simp_all [in32BitMode, curArch, architecture, MCSR, beq_iff_eq, ne_eq]

end Flapjack.RiscV.L3.Step
