import Flapjack.RiscV.L3.Defs.UpperJump

/-! Evaluated upper-immediate instruction equations (HOL `riscv_step` upper group).

The HOL `riscv_stepScript.sml` `class` evaluator normalises each `dfn'X_def`
upper-immediate clause into an explicit record-update equation.  The
destination-write branch carries the sole hypothesis `rd <> 0w`; the companion
`X_NOP` theorem, generated by the `class_rd0` factory through
`utilsLib.save_thms`, carries `rd = 0w` and reduces to the unchanged state.  The
original companion exists in the exported `riscv_stepTheory` signature (its name
is produced by the factory rather than written out as a literal `val` binding,
which is why the reference checker registers the generated family narrowly).
The two write equations below are transcribed with the original hypothesis and
the exact normal form produced by the HOL evaluator, followed by the `X_NOP`
companions; LUI writes the sign-extended upper immediate and AUIPC adds the
current PC. -/
namespace Flapjack.RiscV.L3.Step

open Flapjack.RiscV.L3

@[hol "HOL/examples/l3-machine-code/riscv/step/riscv_stepScript.sml" "LUI"]
theorem dfnLui (rd : BitVec 5) (imm : BitVec 20) (s : riscv_state) (h : rd ≠ 0) :
    «dfn'LUI» (rd, imm) s =
      { s with
        c_gpr :=
          holUpdate s.procID
            (holUpdate rd
              (BitVec.signExtend 64
                (BitVec.setWidth 32 (imm ++ BitVec.ofNat 12 0)))
              (s.c_gpr s.procID))
            s.c_gpr } := by
  simp only [«dfn'LUI», «write'GPR», «write'gpr»]
  simp_all

@[hol "HOL/examples/l3-machine-code/riscv/step/riscv_stepScript.sml" "AUIPC"]
theorem dfnAuiPC (rd : BitVec 5) (imm : BitVec 20) (s : riscv_state) (h : rd ≠ 0) :
    «dfn'AUIPC» (rd, imm) s =
      { s with
        c_gpr :=
          holUpdate s.procID
            (holUpdate rd
              (s.c_PC s.procID +
                BitVec.signExtend 64
                  (BitVec.setWidth 32 (imm ++ BitVec.ofNat 12 0)))
              (s.c_gpr s.procID))
            s.c_gpr } := by
  simp only [«dfn'AUIPC», «write'GPR», «write'gpr», PC]
  simp_all

@[hol "HOL/examples/l3-machine-code/riscv/step/riscv_stepScript.sml" "LUI_NOP"]
theorem dfnLuiNop (rd : BitVec 5) (imm : BitVec 20) (s : riscv_state) (h : rd = 0) :
    «dfn'LUI» (rd, imm) s = s := by
  simp only [«dfn'LUI», «write'GPR», h]
  simp

@[hol "HOL/examples/l3-machine-code/riscv/step/riscv_stepScript.sml" "AUIPC_NOP"]
theorem dfnAuiPCNop (rd : BitVec 5) (imm : BitVec 20) (s : riscv_state) (h : rd = 0) :
    «dfn'AUIPC» (rd, imm) s = s := by
  simp only [«dfn'AUIPC», «write'GPR», h]
  simp

end Flapjack.RiscV.L3.Step
