load "bossLib"; load "preamble"; load "backendTheory";
open bossLib HolKernel Parse preamble backendTheory;
val _ = show_types := true;
fun emit label th = (print (label ^ "="); print_term (concl th); print "\n");
val _ = emit "config_component_equality_typed" (DB.fetch "backend" "config_component_equality");
val _ = print "source_conf_type=";
val _ = print (type_to_string (type_of ``\(c:backend$config). c.source_conf``));
val _ = print "\n";
val _ = print "clos_conf_type=";
val _ = print (type_to_string (type_of ``\(c:backend$config). c.clos_conf``));
val _ = print "\n";
val _ = print "bvl_conf_type=";
val _ = print (type_to_string (type_of ``\(c:backend$config). c.bvl_conf``));
val _ = print "\n";
val _ = print "data_conf_type=";
val _ = print (type_to_string (type_of ``\(c:backend$config). c.data_conf``));
val _ = print "\n";
val _ = print "word_to_word_conf_type=";
val _ = print (type_to_string (type_of ``\(c:backend$config). c.word_to_word_conf``));
val _ = print "\n";
val _ = print "word_conf_type=";
val _ = print (type_to_string (type_of ``\(c:backend$config). c.word_conf``));
val _ = print "\n";
val _ = print "stack_conf_type=";
val _ = print (type_to_string (type_of ``\(c:backend$config). c.stack_conf``));
val _ = print "\n";
val _ = print "lab_conf_type=";
val _ = print (type_to_string (type_of ``\(c:backend$config). c.lab_conf``));
val _ = print "\n";
val _ = print "symbols_type=";
val _ = print (type_to_string (type_of ``\(c:backend$config). c.symbols``));
val _ = print "\n";
val _ = print "tap_conf_type=";
val _ = print (type_to_string (type_of ``\(c:backend$config). c.tap_conf``));
val _ = print "\n";
val _ = print "exported_type=";
val _ = print (type_to_string (type_of ``\(c:backend$config). c.exported``));
val _ = print "\n";
val _ = print "attach_bitmaps_type=";
val _ = print (type_to_string (type_of ``backend$attach_bitmaps``));
val _ = print "\n";
val _ = emit "attach_bitmaps_def_typed" (DB.fetch "backend" "attach_bitmaps_def");
