load "bossLib"; load "preamble"; load "bvl_to_bviTheory";
open bossLib HolKernel Parse preamble bvl_to_bviTheory;
val _ = show_types := true;
val _ = print "config_component_equality=";
val _ = print_term (concl (DB.fetch "bvl_to_bvi" "config_component_equality"));
val _ = print "\n";
val _ = print "inline_size_limit_type=";
val _ = print (type_to_string (type_of ``\(c:bvl_to_bvi$config). c.inline_size_limit``));
val _ = print "\n";
val _ = print "exp_cut_type=";
val _ = print (type_to_string (type_of ``\(c:bvl_to_bvi$config). c.exp_cut``));
val _ = print "\n";
val _ = print "split_main_at_seq_type=";
val _ = print (type_to_string (type_of ``\(c:bvl_to_bvi$config). c.split_main_at_seq``));
val _ = print "\n";
val _ = print "next_name1_type=";
val _ = print (type_to_string (type_of ``\(c:bvl_to_bvi$config). c.next_name1``));
val _ = print "\n";
val _ = print "next_name2_type=";
val _ = print (type_to_string (type_of ``\(c:bvl_to_bvi$config). c.next_name2``));
val _ = print "\n";
val _ = print "next_name3_type=";
val _ = print (type_to_string (type_of ``\(c:bvl_to_bvi$config). c.next_name3``));
val _ = print "\n";
val _ = print "do_tailrec_type=";
val _ = print (type_to_string (type_of ``\(c:bvl_to_bvi$config). c.do_tailrec``));
val _ = print "\n";
val _ = print "do_tmc_type=";
val _ = print (type_to_string (type_of ``\(c:bvl_to_bvi$config). c.do_tmc``));
val _ = print "\n";
val _ = print "inlines_type=";
val _ = print (type_to_string (type_of ``\(c:bvl_to_bvi$config). c.inlines``));
val _ = print "\n";
val _ = print "bvi_inlines_type=";
val _ = print (type_to_string (type_of ``\(c:bvl_to_bvi$config). c.bvi_inlines``));
val _ = print "\n";
