load "bossLib"; load "preamble"; load "bvl_to_bviTheory";
open bossLib HolKernel Parse preamble bvl_to_bviTheory;
val _ = show_types := true;
fun emit label th = (print (label ^ "="); print_term (concl th); print "\n");
val _ = emit "bvl_num_stubs_def" (DB.fetch "backend_common" "bvl_num_stubs_def");
val _ = emit "bvl_to_bvi_namespaces_def" (DB.fetch "backend_common" "bvl_to_bvi_namespaces_def");
val _ = emit "bvl_num_stub_MOD" (DB.fetch "backend_common" "bvl_num_stub_MOD");
val _ = print "bvl_num_stub_MOD_hypotheses=";
val _ = print (Int.toString (length (hyp (DB.fetch "backend_common" "bvl_num_stub_MOD"))));
val _ = print "\n";
val _ = emit "default_config_def" (DB.fetch "bvl_to_bvi" "default_config_def");
val _ = print "default_config_type=";
val _ = print (type_to_string (type_of ``bvl_to_bvi$default_config``));
val _ = print "\n";
val _ = emit "bvl_stub_count_value" (EVAL ``backend_common$bvl_num_stubs``);
val _ = emit "bvl_namespace_count_value" (EVAL ``backend_common$bvl_to_bvi_namespaces``);
val _ = emit "default_next_name1" (EVAL ``(bvl_to_bvi$default_config).next_name1``);
val _ = emit "default_next_name2" (EVAL ``(bvl_to_bvi$default_config).next_name2``);
val _ = emit "default_next_name3" (EVAL ``(bvl_to_bvi$default_config).next_name3``);
