"""Reject drift in original HOL word-arithmetic (Skip/ADDW/SUBW/ADDIW) captures."""
from pathlib import Path

EXPECTED = [
    'skip_statement=Skip (s :riscv_state) = s.c_Skip s.procID',
    'addw_hypotheses=((s :riscv_state).c_MCSR s.procID).mcpuid.ArchBase ≠ (0w :word2)',
    '((s :riscv_state).c_MCSR s.procID).mcpuid.ArchBase ≠ (1w :word2)',
    '(rd :word5) ≠ (0w :word5)',
    "addw_statement=dfn'ADDW ((rd :word5),(rs1 :word5),(rs2 :word5)) (s :riscv_state) =",
    's with',
    'c_gpr :=',
    '  s.c_gpr⦇',
    '    s.procID ↦',
    '      (s.c_gpr s.procID)⦇',
    '        rd ↦',
    '          (if rs1 = (0w :word5) then',
    '             if rs2 = (0w :word5) then (0w :word64)',
    '             else',
    '               (sw2sw',
    '                  (((31 :num) >< (0 :num)) (s.c_gpr s.procID rs2) :word32) :',
    '                word64)',
    '           else if rs2 = (0w :word5) then',
    '             (sw2sw',
    '                (((31 :num) >< (0 :num)) (s.c_gpr s.procID rs1) :word32) :',
    '              word64)',
    '           else',
    '             (sw2sw',
    '                (((31 :num) >< (0 :num))',
    '                   (s.c_gpr s.procID rs1 + s.c_gpr s.procID rs2) :word32) :',
    '              word64))',
    '      ⦈',
    '  ⦈',
    'subw_hypotheses=((s :riscv_state).c_MCSR s.procID).mcpuid.ArchBase ≠ (0w :word2)',
    '((s :riscv_state).c_MCSR s.procID).mcpuid.ArchBase ≠ (1w :word2)',
    '(rd :word5) ≠ (0w :word5)',
    "subw_statement=dfn'SUBW ((rd :word5),(rs1 :word5),(rs2 :word5)) (s :riscv_state) =",
    's with',
    'c_gpr :=',
    '  s.c_gpr⦇',
    '    s.procID ↦',
    '      (s.c_gpr s.procID)⦇',
    '        rd ↦',
    '          (sw2sw',
    '             ((if rs1 = (0w :word5) then (0w :word32)',
    '               else (((31 :num) >< (0 :num)) (s.c_gpr s.procID rs1) :word32)) −',
    '              if rs2 = (0w :word5) then (0w :word32)',
    '              else (((31 :num) >< (0 :num)) (s.c_gpr s.procID rs2) :word32)) :',
    '           word64)',
    '      ⦈',
    '  ⦈',
    'addiw_hypotheses=((s :riscv_state).c_MCSR s.procID).mcpuid.ArchBase ≠ (0w :word2)',
    '((s :riscv_state).c_MCSR s.procID).mcpuid.ArchBase ≠ (1w :word2)',
    '(rd :word5) ≠ (0w :word5)',
    "addiw_statement=dfn'ADDIW ((rd :word5),(rs1 :word5),(imm :word12)) (s :riscv_state) =",
    's with',
    'c_gpr :=',
    '  s.c_gpr⦇',
    '    s.procID ↦',
    '      (s.c_gpr s.procID)⦇',
    '        rd ↦',
    '          (if rs1 = (0w :word5) then',
    '             (sw2sw (((31 :num) >< (0 :num)) (sw2sw imm :word64) :word32) :',
    '              word64)',
    '           else',
    '             (sw2sw',
    '                (((31 :num) >< (0 :num))',
    '                   (s.c_gpr s.procID rs1 + (sw2sw imm :word64)) :word32) :',
    '              word64))',
    '      ⦈',
    '  ⦈',
    'addw_nop_hypotheses=((s :riscv_state).c_MCSR s.procID).mcpuid.ArchBase ≠ (0w :word2)',
    '((s :riscv_state).c_MCSR s.procID).mcpuid.ArchBase ≠ (1w :word2)',
    '(rd :word5) = (0w :word5)',
    "addw_nop_statement=dfn'ADDW ((rd :word5),(rs1 :word5),(rs2 :word5)) (s :riscv_state) = s",
    'subw_nop_hypotheses=((s :riscv_state).c_MCSR s.procID).mcpuid.ArchBase ≠ (0w :word2)',
    '((s :riscv_state).c_MCSR s.procID).mcpuid.ArchBase ≠ (1w :word2)',
    '(rd :word5) = (0w :word5)',
    "subw_nop_statement=dfn'SUBW ((rd :word5),(rs1 :word5),(rs2 :word5)) (s :riscv_state) = s",
    'addiw_nop_hypotheses=((s :riscv_state).c_MCSR s.procID).mcpuid.ArchBase ≠ (0w :word2)',
    '((s :riscv_state).c_MCSR s.procID).mcpuid.ArchBase ≠ (1w :word2)',
    '(rd :word5) = (0w :word5)',
    "addiw_nop_statement=dfn'ADDIW ((rd :word5),(rs1 :word5),(imm :word12)) (s :riscv_state) = s",
    "source=HOL riscv_stepScript.sml:637 Skip = save_thm over Skip_def, and 838/859/861 ADDW/ADDIW/SUBW = arithr/arithi [] over dfn'ADDW/ADDIW/SUBW_def with the rd = 0w companion avoided; per-theorem Thm.hyp captured above; the word forms keep the RV32-exclusion, invalid-selector and rd <> 0w hypotheses, and the ADDW_NOP/ADDIW_NOP/SUBW_NOP companions add rd = 0w",
]


def check(text):
    if text.splitlines() != EXPECTED:
        raise ValueError("original HOL word-arith capture differs from reviewed statements")


if __name__ == "__main__":
    check(Path(__file__).with_name("l3_step_warith_probe.out").read_text())
    print("step_warith: exact original HOL statements, hypotheses and types PASS")
