"""Reject drift in original HOL memory-store evaluated instruction captures."""
from pathlib import Path

EXPECTED = [
    'sd_hypotheses=((s :riscv_state).c_MCSR s.procID).mcpuid.ArchBase ≠ (0w :word2)',
    '((s :riscv_state).c_MCSR s.procID).mcpuid.ArchBase ≠ (1w :word2)',
    '((s :riscv_state).c_MCSR s.procID).mstatus.VM = (0w :word5)',
    'aligned (3 :num)',
    '  (if (rs1 :word5) = (0w :word5) then (sw2sw (offs :word12) :word64)',
    '   else (s :riscv_state).c_gpr s.procID rs1 + (sw2sw offs :word64))',
    "sd_statement=dfn'SD ((rs1 :word5),(rs2 :word5),(offs :word12)) (s :riscv_state) =",
    's with',
    'MEM8 :=',
    '  s.MEM8⦇',
    '    (if rs1 = (0w :word5) then (sw2sw offs :word64)',
    '       else s.c_gpr s.procID rs1 + (sw2sw offs :word64)) ↦',
    '      (if rs2 = (0w :word5) then (0w :word8)',
    '       else (((7 :num) >< (0 :num)) (s.c_gpr s.procID rs2) :word8));',
    '    (if rs1 = (0w :word5) then (sw2sw offs :word64) + (1w :word64)',
    '       else s.c_gpr s.procID rs1 + (sw2sw offs :word64) + (1w :word64)) ↦',
    '      (if rs2 = (0w :word5) then (0w :word8)',
    '       else (((15 :num) >< (8 :num)) (s.c_gpr s.procID rs2) :word8));',
    '    (if rs1 = (0w :word5) then (sw2sw offs :word64) + (2w :word64)',
    '       else s.c_gpr s.procID rs1 + (sw2sw offs :word64) + (2w :word64)) ↦',
    '      (if rs2 = (0w :word5) then (0w :word8)',
    '       else (((23 :num) >< (16 :num)) (s.c_gpr s.procID rs2) :word8));',
    '    (if rs1 = (0w :word5) then (sw2sw offs :word64) + (3w :word64)',
    '       else s.c_gpr s.procID rs1 + (sw2sw offs :word64) + (3w :word64)) ↦',
    '      (if rs2 = (0w :word5) then (0w :word8)',
    '       else (((31 :num) >< (24 :num)) (s.c_gpr s.procID rs2) :word8));',
    '    (if rs1 = (0w :word5) then (sw2sw offs :word64) + (4w :word64)',
    '       else s.c_gpr s.procID rs1 + (sw2sw offs :word64) + (4w :word64)) ↦',
    '      (if rs2 = (0w :word5) then (0w :word8)',
    '       else (((39 :num) >< (32 :num)) (s.c_gpr s.procID rs2) :word8));',
    '    (if rs1 = (0w :word5) then (sw2sw offs :word64) + (5w :word64)',
    '       else s.c_gpr s.procID rs1 + (sw2sw offs :word64) + (5w :word64)) ↦',
    '      (if rs2 = (0w :word5) then (0w :word8)',
    '       else (((47 :num) >< (40 :num)) (s.c_gpr s.procID rs2) :word8));',
    '    (if rs1 = (0w :word5) then (sw2sw offs :word64) + (6w :word64)',
    '       else s.c_gpr s.procID rs1 + (sw2sw offs :word64) + (6w :word64)) ↦',
    '      (if rs2 = (0w :word5) then (0w :word8)',
    '       else (((55 :num) >< (48 :num)) (s.c_gpr s.procID rs2) :word8));',
    '    (if rs1 = (0w :word5) then (sw2sw offs :word64) + (7w :word64)',
    '       else s.c_gpr s.procID rs1 + (sw2sw offs :word64) + (7w :word64)) ↦',
    '      (if rs2 = (0w :word5) then (0w :word8)',
    '       else (((63 :num) >< (56 :num)) (s.c_gpr s.procID rs2) :word8))',
    '  ⦈',
    'sw_hypotheses=((s :riscv_state).c_MCSR s.procID).mstatus.VM = (0w :word5)',
    'aligned (2 :num)',
    '  (if (rs1 :word5) = (0w :word5) then (sw2sw (offs :word12) :word64)',
    '   else (s :riscv_state).c_gpr s.procID rs1 + (sw2sw offs :word64))',
    "sw_statement=dfn'SW ((rs1 :word5),(rs2 :word5),(offs :word12)) (s :riscv_state) =",
    's with',
    'MEM8 :=',
    '  s.MEM8⦇',
    '    (if rs1 = (0w :word5) then (sw2sw offs :word64)',
    '       else s.c_gpr s.procID rs1 + (sw2sw offs :word64)) ↦',
    '      (if rs2 = (0w :word5) then (0w :word8)',
    '       else (((7 :num) >< (0 :num)) (s.c_gpr s.procID rs2) :word8));',
    '    (if rs1 = (0w :word5) then (sw2sw offs :word64) + (1w :word64)',
    '       else s.c_gpr s.procID rs1 + (sw2sw offs :word64) + (1w :word64)) ↦',
    '      (if rs2 = (0w :word5) then (0w :word8)',
    '       else (((15 :num) >< (8 :num)) (s.c_gpr s.procID rs2) :word8));',
    '    (if rs1 = (0w :word5) then (sw2sw offs :word64) + (2w :word64)',
    '       else s.c_gpr s.procID rs1 + (sw2sw offs :word64) + (2w :word64)) ↦',
    '      (if rs2 = (0w :word5) then (0w :word8)',
    '       else (((23 :num) >< (16 :num)) (s.c_gpr s.procID rs2) :word8));',
    '    (if rs1 = (0w :word5) then (sw2sw offs :word64) + (3w :word64)',
    '       else s.c_gpr s.procID rs1 + (sw2sw offs :word64) + (3w :word64)) ↦',
    '      (if rs2 = (0w :word5) then (0w :word8)',
    '       else (((31 :num) >< (24 :num)) (s.c_gpr s.procID rs2) :word8))',
    '  ⦈',
    'sh_hypotheses=((s :riscv_state).c_MCSR s.procID).mstatus.VM = (0w :word5)',
    'aligned (1 :num)',
    '  (if (rs1 :word5) = (0w :word5) then (sw2sw (offs :word12) :word64)',
    '   else (s :riscv_state).c_gpr s.procID rs1 + (sw2sw offs :word64))',
    "sh_statement=dfn'SH ((rs1 :word5),(rs2 :word5),(offs :word12)) (s :riscv_state) =",
    's with',
    'MEM8 :=',
    '  s.MEM8⦇',
    '    (if rs1 = (0w :word5) then (sw2sw offs :word64)',
    '       else s.c_gpr s.procID rs1 + (sw2sw offs :word64)) ↦',
    '      (if rs2 = (0w :word5) then (0w :word8)',
    '       else (((7 :num) >< (0 :num)) (s.c_gpr s.procID rs2) :word8));',
    '    (if rs1 = (0w :word5) then (sw2sw offs :word64) + (1w :word64)',
    '       else s.c_gpr s.procID rs1 + (sw2sw offs :word64) + (1w :word64)) ↦',
    '      (if rs2 = (0w :word5) then (0w :word8)',
    '       else (((15 :num) >< (8 :num)) (s.c_gpr s.procID rs2) :word8))',
    '  ⦈',
    'sb_hypotheses=((s :riscv_state).c_MCSR s.procID).mstatus.VM = (0w :word5)',
    "sb_statement=dfn'SB ((rs1 :word5),(rs2 :word5),(offs :word12)) (s :riscv_state) =",
    's with',
    'MEM8 :=',
    '  s.MEM8⦇',
    '    (if rs1 = (0w :word5) then (sw2sw offs :word64)',
    '       else s.c_gpr s.procID rs1 + (sw2sw offs :word64)) ↦',
    '      (if rs2 = (0w :word5) then (0w :word8)',
    '       else (((7 :num) >< (0 :num)) (s.c_gpr s.procID rs2) :word8))',
    '  ⦈',
    "source=HOL riscv_stepScript.sml:908-915 store = class (rs1,rs2,offs) over dfn'SD/SW/SH/SB_def; SD carries archbase<>0w and aligned_d in its avoid list, SW/SH/SB carry none; per-theorem Thm.hyp captured above; the store factory generates no rd = 0w companion",
]


def check(text):
    if text.splitlines() != EXPECTED:
        raise ValueError("original HOL store capture differs from reviewed statements")


if __name__ == "__main__":
    check(Path(__file__).with_name("l3_step_store_probe.out").read_text())
    print("step_store: exact original HOL statements, hypotheses and types PASS")
