(*
  Direct HOL-EVAL probes for the original Pancake Loop loop_primop.
  Reference: cakeml/pancake/semantics/loopSemScript.sml:242-252.
  The only primitive currently defined there is AddCarry.  The output is
  checked in and regenerated by scripts/hol-probes/regenerate.sh.
*)
load "bossLib";
load "preamble";
load "../semantics/loopSemTheory";
open bossLib;
open HolKernel Parse;
open preamble;
open loopSemTheory;

fun print_eval label q =
  let
    val th = EVAL q
  in
    print (label ^ "=");
    print_term (rconc th);
    print "\n"
  end

val _ = print_eval "valid_no_carry"
  ``loop_primop AddCarry [Word (3w : 64 word); Word (4w : 64 word); Word (0w : 64 word)]``
val _ = print_eval "valid_carry"
  ``loop_primop AddCarry [Word (0xffffffffffffffffw : 64 word); Word (0w : 64 word); Word (1w : 64 word)]``
val _ = print_eval "invalid_arity"
  ``loop_primop AddCarry [Word (3w : 64 word); Word (4w : 64 word)]``
val _ = print_eval "invalid_nonword"
  ``loop_primop AddCarry [wordLang$Loc 0 0; Word (4w : 64 word); Word (0w : 64 word)]``
