load "preamble";
load "panPropsTheory";
open HolKernel Parse bossLib preamble panPropsTheory;
val _ = Globals.linewidth := 1000000;
val full = GEN_ALL pan_sem_is_wrapper;
val _ = if null(hyp full) andalso null(free_vars(concl full)) then () else raise Fail "open theorem";
val _ = print "pan_sem_is_wrapper_statement=";
val _ = print_term(concl full);
val _ = print "\n";
val _ = print("pan_sem_is_wrapper_proved=" ^ term_to_string(rhs(concl(EQT_INTRO full))) ^ "\n");
val _ = print("pan_sem_is_wrapper_types=" ^ String.concatWith ";" (map (fn t => term_to_string t ^ ":" ^ type_to_string(type_of t)) (fst(strip_forall(concl full)))) ^ "\n");
