load "loop_to_wordProofTheory";
load "pan_to_wordProofTheory";
open HolKernel Parse bossLib;
val _ = Globals.linewidth := 1000000;
fun pr_stmt label th = (print (label ^ "="); print_term (concl th); print "\n");
fun pr_hyps label th = (print (label ^ "="); print (Int.toString (length (hyp th))); print "\n");
fun pr_typed label th = (print (label ^ "="); Lib.with_flag (Globals.show_types, true) print_term (concl th); print "\n");
val _ = pr_stmt "loop_to_word_comp_not_created_statement" loop_to_wordProofTheory.loop_to_word_comp_not_created;
val _ = pr_hyps "loop_to_word_comp_not_created_hypotheses" loop_to_wordProofTheory.loop_to_word_comp_not_created;
val _ = pr_typed "loop_to_word_comp_not_created_typed" loop_to_wordProofTheory.loop_to_word_comp_not_created;
val _ = pr_stmt "loop_to_word_comp_func_not_created_statement" loop_to_wordProofTheory.loop_to_word_comp_func_not_created;
val _ = pr_hyps "loop_to_word_comp_func_not_created_hypotheses" loop_to_wordProofTheory.loop_to_word_comp_func_not_created;
val _ = pr_typed "loop_to_word_comp_func_not_created_typed" loop_to_wordProofTheory.loop_to_word_comp_func_not_created;
val _ = pr_stmt "loop_to_word_compile_not_created_statement" loop_to_wordProofTheory.loop_to_word_compile_not_created;
val _ = pr_hyps "loop_to_word_compile_not_created_hypotheses" loop_to_wordProofTheory.loop_to_word_compile_not_created;
val _ = pr_typed "loop_to_word_compile_not_created_typed" loop_to_wordProofTheory.loop_to_word_compile_not_created;
val _ = pr_stmt "loop_compile_no_install_code_statement" loop_to_wordProofTheory.loop_compile_no_install_code;
val _ = pr_hyps "loop_compile_no_install_code_hypotheses" loop_to_wordProofTheory.loop_compile_no_install_code;
val _ = pr_typed "loop_compile_no_install_code_typed" loop_to_wordProofTheory.loop_compile_no_install_code;
val _ = pr_stmt "loop_compile_no_alloc_code_statement" loop_to_wordProofTheory.loop_compile_no_alloc_code;
val _ = pr_hyps "loop_compile_no_alloc_code_hypotheses" loop_to_wordProofTheory.loop_compile_no_alloc_code;
val _ = pr_typed "loop_compile_no_alloc_code_typed" loop_to_wordProofTheory.loop_compile_no_alloc_code;
val _ = pr_stmt "loop_compile_no_mt_code_statement" loop_to_wordProofTheory.loop_compile_no_mt_code;
val _ = pr_hyps "loop_compile_no_mt_code_hypotheses" loop_to_wordProofTheory.loop_compile_no_mt_code;
val _ = pr_typed "loop_compile_no_mt_code_typed" loop_to_wordProofTheory.loop_compile_no_mt_code;
val _ = pr_stmt "pan_to_word_compile_prog_no_install_code_statement" pan_to_wordProofTheory.pan_to_word_compile_prog_no_install_code;
val _ = pr_hyps "pan_to_word_compile_prog_no_install_code_hypotheses" pan_to_wordProofTheory.pan_to_word_compile_prog_no_install_code;
val _ = pr_typed "pan_to_word_compile_prog_no_install_code_typed" pan_to_wordProofTheory.pan_to_word_compile_prog_no_install_code;
val _ = pr_stmt "pan_to_word_compile_prog_no_alloc_code_statement" pan_to_wordProofTheory.pan_to_word_compile_prog_no_alloc_code;
val _ = pr_hyps "pan_to_word_compile_prog_no_alloc_code_hypotheses" pan_to_wordProofTheory.pan_to_word_compile_prog_no_alloc_code;
val _ = pr_typed "pan_to_word_compile_prog_no_alloc_code_typed" pan_to_wordProofTheory.pan_to_word_compile_prog_no_alloc_code;
val _ = pr_stmt "pan_to_word_compile_prog_no_mt_code_statement" pan_to_wordProofTheory.pan_to_word_compile_prog_no_mt_code;
val _ = pr_hyps "pan_to_word_compile_prog_no_mt_code_hypotheses" pan_to_wordProofTheory.pan_to_word_compile_prog_no_mt_code;
val _ = pr_typed "pan_to_word_compile_prog_no_mt_code_typed" pan_to_wordProofTheory.pan_to_word_compile_prog_no_mt_code;
