load "preamble"; load "riscvTheory"; load "asmSemTheory"; load "riscv_targetTheory";
open HolKernel Parse bossLib preamble riscvTheory asmSemTheory riscv_targetTheory;
val _ = Globals.linewidth := 1000000;
fun clause label th = (print(label ^ "="); print_term(concl th); print "\n");
fun hypotheses label th = print(label ^ "=" ^ Int.toString(length(hyp th)) ^ "\n");
fun types label tm = (print(label ^ "="); print_type(type_of tm); print " ;"; if null(free_vars tm) then () else print(" " ^ String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars tm))); print "\n");
val _ = clause "source_reg_imm_clause" asmSemTheory.reg_imm_def;
val _ = hypotheses "source_reg_imm_hypotheses" asmSemTheory.reg_imm_def;
val _ = types "source_reg_imm_types" ``asmSem$reg_imm``;
val _ = clause "source_binop_upd_clause" asmSemTheory.binop_upd_def;
val _ = hypotheses "source_binop_upd_hypotheses" asmSemTheory.binop_upd_def;
val _ = types "source_binop_upd_types" ``asmSem$binop_upd``;
val _ = clause "source_arith_upd_clause" asmSemTheory.arith_upd_def;
val _ = hypotheses "source_arith_upd_hypotheses" asmSemTheory.arith_upd_def;
val _ = types "source_arith_upd_types" ``asmSem$arith_upd``;
val _ = clause "source_asm_step_clause" asmSemTheory.asm_step_def;
val _ = hypotheses "source_asm_step_hypotheses" asmSemTheory.asm_step_def;
val _ = types "source_asm_step_types" ``asmSem$asm_step``;
val _ = clause "source_bop_r_clause" riscv_targetTheory.riscv_bop_r_def;
val _ = hypotheses "source_bop_r_hypotheses" riscv_targetTheory.riscv_bop_r_def;
val _ = types "source_bop_r_types" ``riscv_target$riscv_bop_r``;
val native_add_term = ``riscv$Run (ArithR (ADD (rdv,rs1v,rs2v))) stv``;
val native_add_th = SIMP_CONV (srw_ss()) [Run_def, dfn'ADD_def] native_add_term;
val _ = clause "native_add_clause" native_add_th;
val _ = hypotheses "native_add_hypotheses" native_add_th;
val _ = types "native_add_types" native_add_term;
val native_sub_term = ``riscv$Run (ArithR (SUB (rdv,rs1v,rs2v))) stv``;
val native_sub_th = SIMP_CONV (srw_ss()) [Run_def, dfn'SUB_def] native_sub_term;
val _ = clause "native_sub_clause" native_sub_th;
val _ = hypotheses "native_sub_hypotheses" native_sub_th;
val _ = types "native_sub_types" native_sub_term;
val native_and_term = ``riscv$Run (ArithR (AND (rdv,rs1v,rs2v))) stv``;
val native_and_th = SIMP_CONV (srw_ss()) [Run_def, dfn'AND_def] native_and_term;
val _ = clause "native_and_clause" native_and_th;
val _ = hypotheses "native_and_hypotheses" native_and_th;
val _ = types "native_and_types" native_and_term;
val native_or_term = ``riscv$Run (ArithR (OR (rdv,rs1v,rs2v))) stv``;
val native_or_th = SIMP_CONV (srw_ss()) [Run_def, dfn'OR_def] native_or_term;
val _ = clause "native_or_clause" native_or_th;
val _ = hypotheses "native_or_hypotheses" native_or_th;
val _ = types "native_or_types" native_or_term;
val native_xor_term = ``riscv$Run (ArithR (XOR (rdv,rs1v,rs2v))) stv``;
val native_xor_th = SIMP_CONV (srw_ss()) [Run_def, dfn'XOR_def] native_xor_term;
val _ = clause "native_xor_clause" native_xor_th;
val _ = hypotheses "native_xor_hypotheses" native_xor_th;
val _ = types "native_xor_types" native_xor_term;
val _ = OS.Process.exit OS.Process.success;
