load "preamble"; load "riscvTheory";
open HolKernel Parse bossLib preamble riscvTheory;
val _ = computeLib.add_funs [Encode_def,Itype_def,Rtype_def,opc_def,Decode_def,boolify32_def];
val _ = Globals.linewidth := 1000000;
val _ = (print "sll_decode_zero="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SLL (0w,0w,0w)))) = Shift (SLL (0w,0w,0w))``))); print "\n");
val _ = (print "sll_decode_all_ones="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SLL (31w,31w,31w)))) = Shift (SLL (31w,31w,31w))``))); print "\n");
val _ = (print "sll_decode_high_bit="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SLL (1w,0w,16w)))) = Shift (SLL (1w,0w,16w))``))); print "\n");
val _ = (print "sll_decode_alias="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SLL (7w,7w,7w)))) = Shift (SLL (7w,7w,7w))``))); print "\n");
val sll_term = ``Encode (Shift (SLL (rdv,rs1v,rs2v)))``;
val sll_source = SIMP_CONV (srw_ss()) [Encode_def] sll_term;
val _ = (print "sll_encode_source_clause="; print_term(concl sll_source); print "\n");
val _ = (print "sll_carrier_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars sll_term))); print "\n");
val _ = (print "sll_symbolic_query="; print_term ``Decode (Encode (Shift (SLL (rdv,rs1v,rs2v)))) = Shift (SLL (rdv,rs1v,rs2v))``; print "\n");
val _ = print ("sll_source_hypotheses=" ^ Int.toString(length(hyp sll_source)) ^ "\n");
val _ = (print "srl_decode_zero="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SRL (0w,0w,0w)))) = Shift (SRL (0w,0w,0w))``))); print "\n");
val _ = (print "srl_decode_all_ones="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SRL (31w,31w,31w)))) = Shift (SRL (31w,31w,31w))``))); print "\n");
val _ = (print "srl_decode_high_bit="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SRL (1w,0w,16w)))) = Shift (SRL (1w,0w,16w))``))); print "\n");
val _ = (print "srl_decode_alias="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SRL (7w,7w,7w)))) = Shift (SRL (7w,7w,7w))``))); print "\n");
val srl_term = ``Encode (Shift (SRL (rdv,rs1v,rs2v)))``;
val srl_source = SIMP_CONV (srw_ss()) [Encode_def] srl_term;
val _ = (print "srl_encode_source_clause="; print_term(concl srl_source); print "\n");
val _ = (print "srl_carrier_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars srl_term))); print "\n");
val _ = (print "srl_symbolic_query="; print_term ``Decode (Encode (Shift (SRL (rdv,rs1v,rs2v)))) = Shift (SRL (rdv,rs1v,rs2v))``; print "\n");
val _ = print ("srl_source_hypotheses=" ^ Int.toString(length(hyp srl_source)) ^ "\n");
val _ = (print "sra_decode_zero="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SRA (0w,0w,0w)))) = Shift (SRA (0w,0w,0w))``))); print "\n");
val _ = (print "sra_decode_all_ones="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SRA (31w,31w,31w)))) = Shift (SRA (31w,31w,31w))``))); print "\n");
val _ = (print "sra_decode_high_bit="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SRA (1w,0w,16w)))) = Shift (SRA (1w,0w,16w))``))); print "\n");
val _ = (print "sra_decode_alias="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SRA (7w,7w,7w)))) = Shift (SRA (7w,7w,7w))``))); print "\n");
val sra_term = ``Encode (Shift (SRA (rdv,rs1v,rs2v)))``;
val sra_source = SIMP_CONV (srw_ss()) [Encode_def] sra_term;
val _ = (print "sra_encode_source_clause="; print_term(concl sra_source); print "\n");
val _ = (print "sra_carrier_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars sra_term))); print "\n");
val _ = (print "sra_symbolic_query="; print_term ``Decode (Encode (Shift (SRA (rdv,rs1v,rs2v)))) = Shift (SRA (rdv,rs1v,rs2v))``; print "\n");
val _ = print ("sra_source_hypotheses=" ^ Int.toString(length(hyp sra_source)) ^ "\n");
val _ = (print "srli_decode_zero="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SRLI (0w,0w,0w)))) = Shift (SRLI (0w,0w,0w))``))); print "\n");
val _ = (print "srli_decode_all_ones="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SRLI (31w,31w,63w)))) = Shift (SRLI (31w,31w,63w))``))); print "\n");
val _ = (print "srli_decode_high_bit="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SRLI (1w,0w,32w)))) = Shift (SRLI (1w,0w,32w))``))); print "\n");
val _ = (print "srli_decode_alias="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SRLI (7w,7w,1w)))) = Shift (SRLI (7w,7w,1w))``))); print "\n");
val srli_term = ``Encode (Shift (SRLI (rdv,rs1v,amtv)))``;
val srli_source = SIMP_CONV (srw_ss()) [Encode_def] srli_term;
val _ = (print "srli_encode_source_clause="; print_term(concl srli_source); print "\n");
val _ = (print "srli_carrier_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars srli_term))); print "\n");
val _ = (print "srli_symbolic_query="; print_term ``Decode (Encode (Shift (SRLI (rdv,rs1v,amtv)))) = Shift (SRLI (rdv,rs1v,amtv))``; print "\n");
val _ = print ("srli_source_hypotheses=" ^ Int.toString(length(hyp srli_source)) ^ "\n");
val _ = (print "srai_decode_zero="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SRAI (0w,0w,0w)))) = Shift (SRAI (0w,0w,0w))``))); print "\n");
val _ = (print "srai_decode_all_ones="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SRAI (31w,31w,63w)))) = Shift (SRAI (31w,31w,63w))``))); print "\n");
val _ = (print "srai_decode_high_bit="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SRAI (1w,0w,32w)))) = Shift (SRAI (1w,0w,32w))``))); print "\n");
val _ = (print "srai_decode_alias="; print_term(rhs(concl(EVAL ``Decode (Encode (Shift (SRAI (7w,7w,1w)))) = Shift (SRAI (7w,7w,1w))``))); print "\n");
val srai_term = ``Encode (Shift (SRAI (rdv,rs1v,amtv)))``;
val srai_source = SIMP_CONV (srw_ss()) [Encode_def] srai_term;
val _ = (print "srai_encode_source_clause="; print_term(concl srai_source); print "\n");
val _ = (print "srai_carrier_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars srai_term))); print "\n");
val _ = (print "srai_symbolic_query="; print_term ``Decode (Encode (Shift (SRAI (rdv,rs1v,amtv)))) = Shift (SRAI (rdv,rs1v,amtv))``; print "\n");
val _ = print ("srai_source_hypotheses=" ^ Int.toString(length(hyp srai_source)) ^ "\n");
val _ = OS.Process.exit OS.Process.success;
