load "preamble"; load "riscv_targetProofTheory";
open HolKernel Parse bossLib preamble riscvTheory asmSemTheory riscv_targetTheory;
val _ = Globals.linewidth := 1000000;
val source_shift_term = ``arith_upd (asm$Shift op rd rs (ri:64 reg_imm)) (src:64 asm_state)``;
val source_shift_clause = SIMP_CONV (srw_ss()) [arith_upd_def] source_shift_term;
val _ = (print "source_shift_clause="; print_term(concl source_shift_clause); print "\n");
val _ = (print "source_shift_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars source_shift_term))); print "\n");
val _ = print ("source_shift_hypotheses=" ^ Int.toString(length(hyp source_shift_clause)) ^ "\n");
val target_ok_term = ``riscv_ok ms``;
val target_ok_clause = SIMP_CONV (srw_ss()) [riscv_ok_def] target_ok_term;
val _ = (print "target_ok_clause="; print_term(concl target_ok_clause); print "\n");
val _ = (print "target_ok_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars target_ok_term))); print "\n");
val _ = print ("target_ok_hypotheses=" ^ Int.toString(length(hyp target_ok_clause)) ^ "\n");
val run_sll_term = ``Run (riscv$Shift (SLL (rdv,rs1v,rs2v))) ms``;
val run_sll_clause = SIMP_CONV (srw_ss()) [Run_def, dfn'SLL_def] run_sll_term;
val _ = (print "run_sll_clause="; print_term(concl run_sll_clause); print "\n");
val _ = (print "run_sll_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars run_sll_term))); print "\n");
val _ = print ("run_sll_hypotheses=" ^ Int.toString(length(hyp run_sll_clause)) ^ "\n");
val run_srl_term = ``Run (riscv$Shift (SRL (rdv,rs1v,rs2v))) ms``;
val run_srl_clause = SIMP_CONV (srw_ss()) [Run_def, dfn'SRL_def] run_srl_term;
val _ = (print "run_srl_clause="; print_term(concl run_srl_clause); print "\n");
val _ = (print "run_srl_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars run_srl_term))); print "\n");
val _ = print ("run_srl_hypotheses=" ^ Int.toString(length(hyp run_srl_clause)) ^ "\n");
val run_sra_term = ``Run (riscv$Shift (SRA (rdv,rs1v,rs2v))) ms``;
val run_sra_clause = SIMP_CONV (srw_ss()) [Run_def, dfn'SRA_def] run_sra_term;
val _ = (print "run_sra_clause="; print_term(concl run_sra_clause); print "\n");
val _ = (print "run_sra_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars run_sra_term))); print "\n");
val _ = print ("run_sra_hypotheses=" ^ Int.toString(length(hyp run_sra_clause)) ^ "\n");
val run_slli_term = ``Run (riscv$Shift (SLLI (rdv,rs1v,amtv))) ms``;
val run_slli_clause = SIMP_CONV (srw_ss()) [Run_def, dfn'SLLI_def] run_slli_term;
val _ = (print "run_slli_clause="; print_term(concl run_slli_clause); print "\n");
val _ = (print "run_slli_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars run_slli_term))); print "\n");
val _ = print ("run_slli_hypotheses=" ^ Int.toString(length(hyp run_slli_clause)) ^ "\n");
val run_srli_term = ``Run (riscv$Shift (SRLI (rdv,rs1v,amtv))) ms``;
val run_srli_clause = SIMP_CONV (srw_ss()) [Run_def, dfn'SRLI_def] run_srli_term;
val _ = (print "run_srli_clause="; print_term(concl run_srli_clause); print "\n");
val _ = (print "run_srli_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars run_srli_term))); print "\n");
val _ = print ("run_srli_hypotheses=" ^ Int.toString(length(hyp run_srli_clause)) ^ "\n");
val run_srai_term = ``Run (riscv$Shift (SRAI (rdv,rs1v,amtv))) ms``;
val run_srai_clause = SIMP_CONV (srw_ss()) [Run_def, dfn'SRAI_def] run_srai_term;
val _ = (print "run_srai_clause="; print_term(concl run_srai_clause); print "\n");
val _ = (print "run_srai_types="; print (String.concatWith ", " (map (fn v => term_to_string v ^ " : " ^ type_to_string(type_of v)) (free_vars run_srai_term))); print "\n");
val _ = print ("run_srai_hypotheses=" ^ Int.toString(length(hyp run_srai_clause)) ^ "\n");
val _ = OS.Process.exit OS.Process.success;
