load "preamble"; load "stack_to_labProofTheory";
open HolKernel Parse bossLib preamble;
val _ = Globals.linewidth := 1000000;
fun checked label th =
  (if null (hyp th) then () else raise Fail "open HOL hypotheses";
   print (label ^ "="); print_term (concl th); print "\n");
fun typed_statement label th =
  (show_types := true;
   print (label ^ "="); print_term (concl th); print "\n";
   show_types := false);
fun type_list label th =
  (show_types := true;
   print (label ^ "=");
   app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";"))
     (fst (strip_forall (concl th)) @ free_vars (concl th));
   print "\n";
   show_types := false);

(* Exported originals of stack_to_labProofScript.sml:4987-5209. *)
val _ = checked "stack_rawcall_comp_no_install_statement" stack_to_labProofTheory.stack_rawcall_comp_no_install;
val _ = typed_statement "stack_rawcall_comp_no_install_statement_typed" stack_to_labProofTheory.stack_rawcall_comp_no_install;
val _ = type_list "stack_rawcall_comp_no_install_statement_types" stack_to_labProofTheory.stack_rawcall_comp_no_install;
val _ = checked "stack_rawcall_comp_top_no_install_statement" stack_to_labProofTheory.stack_rawcall_comp_top_no_install;
val _ = typed_statement "stack_rawcall_comp_top_no_install_statement_typed" stack_to_labProofTheory.stack_rawcall_comp_top_no_install;
val _ = type_list "stack_rawcall_comp_top_no_install_statement_types" stack_to_labProofTheory.stack_rawcall_comp_top_no_install;
val _ = checked "stack_rawcall_compile_no_install_statement" stack_to_labProofTheory.stack_rawcall_compile_no_install;
val _ = typed_statement "stack_rawcall_compile_no_install_statement_typed" stack_to_labProofTheory.stack_rawcall_compile_no_install;
val _ = type_list "stack_rawcall_compile_no_install_statement_types" stack_to_labProofTheory.stack_rawcall_compile_no_install;
val _ = checked "stack_alloc_comp_no_install_statement" stack_to_labProofTheory.stack_alloc_comp_no_install;
val _ = typed_statement "stack_alloc_comp_no_install_statement_typed" stack_to_labProofTheory.stack_alloc_comp_no_install;
val _ = type_list "stack_alloc_comp_no_install_statement_types" stack_to_labProofTheory.stack_alloc_comp_no_install;
val _ = checked "stack_alloc_prog_comp_no_install_statement" stack_to_labProofTheory.stack_alloc_prog_comp_no_install;
val _ = typed_statement "stack_alloc_prog_comp_no_install_statement_typed" stack_to_labProofTheory.stack_alloc_prog_comp_no_install;
val _ = type_list "stack_alloc_prog_comp_no_install_statement_types" stack_to_labProofTheory.stack_alloc_prog_comp_no_install;
val _ = checked "stack_alloc_compile_no_install_statement" stack_to_labProofTheory.stack_alloc_compile_no_install;
val _ = typed_statement "stack_alloc_compile_no_install_statement_typed" stack_to_labProofTheory.stack_alloc_compile_no_install;
val _ = type_list "stack_alloc_compile_no_install_statement_types" stack_to_labProofTheory.stack_alloc_compile_no_install;
val _ = checked "upshift_no_install_statement" stack_to_labProofTheory.upshift_no_install;
val _ = typed_statement "upshift_no_install_statement_typed" stack_to_labProofTheory.upshift_no_install;
val _ = type_list "upshift_no_install_statement_types" stack_to_labProofTheory.upshift_no_install;
val _ = checked "downshift_no_install_statement" stack_to_labProofTheory.downshift_no_install;
val _ = typed_statement "downshift_no_install_statement_typed" stack_to_labProofTheory.downshift_no_install;
val _ = type_list "downshift_no_install_statement_types" stack_to_labProofTheory.downshift_no_install;
val _ = checked "stack_free_no_install_statement" stack_to_labProofTheory.stack_free_no_install;
val _ = typed_statement "stack_free_no_install_statement_typed" stack_to_labProofTheory.stack_free_no_install;
val _ = type_list "stack_free_no_install_statement_types" stack_to_labProofTheory.stack_free_no_install;
val _ = checked "stack_alloc_no_install_statement" stack_to_labProofTheory.stack_alloc_no_install;
val _ = typed_statement "stack_alloc_no_install_statement_typed" stack_to_labProofTheory.stack_alloc_no_install;
val _ = type_list "stack_alloc_no_install_statement_types" stack_to_labProofTheory.stack_alloc_no_install;
val _ = checked "stack_remove_comp_no_install_statement" stack_to_labProofTheory.stack_remove_comp_no_install;
val _ = typed_statement "stack_remove_comp_no_install_statement_typed" stack_to_labProofTheory.stack_remove_comp_no_install;
val _ = type_list "stack_remove_comp_no_install_statement_types" stack_to_labProofTheory.stack_remove_comp_no_install;
val _ = checked "stack_remove_prog_comp_no_install_statement" stack_to_labProofTheory.stack_remove_prog_comp_no_install;
val _ = typed_statement "stack_remove_prog_comp_no_install_statement_typed" stack_to_labProofTheory.stack_remove_prog_comp_no_install;
val _ = type_list "stack_remove_prog_comp_no_install_statement_types" stack_to_labProofTheory.stack_remove_prog_comp_no_install;
val _ = checked "stack_remove_compile_no_install_statement" stack_to_labProofTheory.stack_remove_compile_no_install;
val _ = typed_statement "stack_remove_compile_no_install_statement_typed" stack_to_labProofTheory.stack_remove_compile_no_install;
val _ = type_list "stack_remove_compile_no_install_statement_types" stack_to_labProofTheory.stack_remove_compile_no_install;
val _ = checked "stack_names_comp_no_install_statement" stack_to_labProofTheory.stack_names_comp_no_install;
val _ = typed_statement "stack_names_comp_no_install_statement_typed" stack_to_labProofTheory.stack_names_comp_no_install;
val _ = type_list "stack_names_comp_no_install_statement_types" stack_to_labProofTheory.stack_names_comp_no_install;
val _ = checked "stack_names_prog_comp_no_install_statement" stack_to_labProofTheory.stack_names_prog_comp_no_install;
val _ = typed_statement "stack_names_prog_comp_no_install_statement_typed" stack_to_labProofTheory.stack_names_prog_comp_no_install;
val _ = type_list "stack_names_prog_comp_no_install_statement_types" stack_to_labProofTheory.stack_names_prog_comp_no_install;
val _ = checked "stack_names_compile_no_install_statement" stack_to_labProofTheory.stack_names_compile_no_install;
val _ = typed_statement "stack_names_compile_no_install_statement_typed" stack_to_labProofTheory.stack_names_compile_no_install;
val _ = type_list "stack_names_compile_no_install_statement_types" stack_to_labProofTheory.stack_names_compile_no_install;
val _ = checked "flatten_no_install_statement" stack_to_labProofTheory.flatten_no_install;
val _ = typed_statement "flatten_no_install_statement_typed" stack_to_labProofTheory.flatten_no_install;
val _ = type_list "flatten_no_install_statement_types" stack_to_labProofTheory.flatten_no_install;
val _ = checked "asm_fetch_aux_no_install_CONS_statement" stack_to_labProofTheory.asm_fetch_aux_no_install_CONS;
val _ = typed_statement "asm_fetch_aux_no_install_CONS_statement_typed" stack_to_labProofTheory.asm_fetch_aux_no_install_CONS;
val _ = type_list "asm_fetch_aux_no_install_CONS_statement_types" stack_to_labProofTheory.asm_fetch_aux_no_install_CONS;
val _ = checked "prog_to_section_no_install_statement" stack_to_labProofTheory.prog_to_section_no_install;
val _ = typed_statement "prog_to_section_no_install_statement_typed" stack_to_labProofTheory.prog_to_section_no_install;
val _ = type_list "prog_to_section_no_install_statement_types" stack_to_labProofTheory.prog_to_section_no_install;
val _ = checked "stack_to_lab_compile_no_install_statement" stack_to_labProofTheory.stack_to_lab_compile_no_install;
val _ = typed_statement "stack_to_lab_compile_no_install_statement_typed" stack_to_labProofTheory.stack_to_lab_compile_no_install;
val _ = type_list "stack_to_lab_compile_no_install_statement_types" stack_to_labProofTheory.stack_to_lab_compile_no_install;
