load "preamble"; load "word_to_wordTheory";
open HolKernel Parse bossLib preamble wordLangTheory word_to_wordTheory asmTheory;
val _ = Globals.linewidth := 1000000;
val _ = show_types := true;
fun checked label th = (if null(hyp th) then () else raise Fail label;
  print(label ^ "="); print_term(concl th); print "\n");
val _ = checked "compile_single_definition" compile_single_def;
val _ = checked "full_compile_single_definition" full_compile_single_def;
val _ = checked "compile_definition" compile_def;
val _ = show_types := false;
val cfg = ``(ARB : 64 asm_config) with <| ISA := RISC_V;
 valid_imm := (\b i. -2048w <= i /\ i <= 2047w);
 addr_offset := (-2048w,2047w); hw_offset := (-2048w,2047w);
 byte_offset := (-2048w,2047w); two_reg_arith := F;
 reg_count := 32; avoid_regs := [0;2;3;4;31]; link_reg := NONE |>``;
fun evald label term = let val th = EVAL term in
 if null(hyp th) then rhs(concl th) else raise Fail label end;
val _ = (print "skip_alg0="; print_term(evald "skip_alg0" ``full_compile_single F 22 0 ^cfg ((7,1,(Skip : 64 wordLang$prog)),NONE)``); print "\n");
val _ = (print "skip_alg2="; print_term(evald "skip_alg2" ``full_compile_single F 22 2 ^cfg ((7,1,(Skip : 64 wordLang$prog)),NONE)``); print "\n");
val _ = (print "return_alg0="; print_term(evald "return_alg0" ``full_compile_single F 22 0 ^cfg ((7,1,(Return 0 [0] : 64 wordLang$prog)),NONE)``); print "\n");
val _ = (print "return_alg2="; print_term(evald "return_alg2" ``full_compile_single F 22 2 ^cfg ((7,1,(Return 0 [0] : 64 wordLang$prog)),NONE)``); print "\n");
val _ = (print "assign_return_alg0="; print_term(evald "assign_return_alg0" ``full_compile_single F 22 0 ^cfg ((7,1,(Seq (Assign 2 (Op Add [Var 0; Const 7w])) (Return 2 [2]) : 64 wordLang$prog)),NONE)``); print "\n");
val _ = (print "assign_return_alg2="; print_term(evald "assign_return_alg2" ``full_compile_single F 22 2 ^cfg ((7,1,(Seq (Assign 2 (Op Add [Var 0; Const 7w])) (Return 2 [2]) : 64 wordLang$prog)),NONE)``); print "\n");
val _ = (print "must_terminate_alg0="; print_term(evald "must_terminate_alg0" ``full_compile_single F 22 0 ^cfg ((7,1,(MustTerminate (Return 0 [0]) : 64 wordLang$prog)),NONE)``); print "\n");
val _ = (print "must_terminate_alg2="; print_term(evald "must_terminate_alg2" ``full_compile_single F 22 2 ^cfg ((7,1,(MustTerminate (Return 0 [0]) : 64 wordLang$prog)),NONE)``); print "\n");
val _ = (print "tail_call_alg0="; print_term(evald "tail_call_alg0" ``full_compile_single F 22 0 ^cfg ((7,1,(Call NONE (SOME 9) [0] NONE : 64 wordLang$prog)),NONE)``); print "\n");
val _ = (print "tail_call_alg2="; print_term(evald "tail_call_alg2" ``full_compile_single F 22 2 ^cfg ((7,1,(Call NONE (SOME 9) [0] NONE : 64 wordLang$prog)),NONE)``); print "\n");
val _ = (print "branch_alg0="; print_term(evald "branch_alg0" ``full_compile_single F 22 0 ^cfg ((7,1,(If Equal 0 (Imm 0w) (Return 0 [0]) (Raise 0) : 64 wordLang$prog)),NONE)``); print "\n");
val _ = (print "branch_alg2="; print_term(evald "branch_alg2" ``full_compile_single F 22 2 ^cfg ((7,1,(If Equal 0 (Imm 0w) (Return 0 [0]) (Raise 0) : 64 wordLang$prog)),NONE)``); print "\n");
val _ = (print "empty="; print_term(evald "empty" ``word_to_word$compile <|reg_alg := 0; col_oracle := []|> ^cfg ([] : (num # num # 64 wordLang$prog) list)``); print "\n");
val _ = (print "oracle_remainder="; print_term(evald "oracle_remainder" ``word_to_word$compile <|reg_alg := 0; col_oracle := [NONE;SOME LN]|> ^cfg ([(7,0,Skip)] : (num # num # 64 wordLang$prog) list)``); print "\n");
val _ = (print "oracle_short="; print_term(evald "oracle_short" ``word_to_word$compile <|reg_alg := 0; col_oracle := [SOME LN]|> ^cfg ([(7,0,Skip);(9,0,Skip)] : (num # num # 64 wordLang$prog) list)``); print "\n");
