load "word_to_wordProofTheory";
open HolKernel Parse bossLib word_to_wordProofTheory;
val _ = Globals.linewidth := 1000000;
fun pr_stmt label th = (print (label ^ "="); print_term (concl th); print "\n");
fun pr_hyps label th = (print (label ^ "="); print (Int.toString (length (hyp th))); print "\n");
fun pr_typed label th = (print (label ^ "="); Lib.with_flag (Globals.show_types, true) print_term (concl th); print "\n");
val _ = pr_stmt "panLang_compile_word_to_word_thm_statement" panLang_compile_word_to_word_thm;
val _ = pr_hyps "panLang_compile_word_to_word_thm_hypotheses" panLang_compile_word_to_word_thm;
val _ = pr_typed "panLang_compile_word_to_word_thm_typed" panLang_compile_word_to_word_thm;
val _ = pr_stmt "word_to_word_compile_semantics_statement" word_to_word_compile_semantics;
val _ = pr_hyps "word_to_word_compile_semantics_hypotheses" word_to_word_compile_semantics;
val _ = pr_typed "word_to_word_compile_semantics_typed" word_to_word_compile_semantics;
