load "wordConvsProofTheory";
open HolKernel Parse bossLib wordConvsProofTheory;
val _ = Globals.linewidth := 1000000;
val _ = (print "extract_labels_word_common_subexp_elim_statement="; print_term(concl extract_labels_word_common_subexp_elim));
val _ = print("extract_labels_word_common_subexp_elim_hypotheses=" ^ Int.toString(length(hyp extract_labels_word_common_subexp_elim)) ^ "\n");
val _ = (print "flat_exp_conventions_word_common_subexp_elim_statement="; print_term(concl flat_exp_conventions_word_common_subexp_elim));
val _ = print("flat_exp_conventions_word_common_subexp_elim_hypotheses=" ^ Int.toString(length(hyp flat_exp_conventions_word_common_subexp_elim)) ^ "\n");
val _ = (print "wf_cutsets_word_common_subexp_elim_statement="; print_term(concl wf_cutsets_word_common_subexp_elim));
val _ = print("wf_cutsets_word_common_subexp_elim_hypotheses=" ^ Int.toString(length(hyp wf_cutsets_word_common_subexp_elim)) ^ "\n");
val _ = (print "wf_cutsets_copy_prop_statement="; print_term(concl wf_cutsets_copy_prop));
val _ = print("wf_cutsets_copy_prop_hypotheses=" ^ Int.toString(length(hyp wf_cutsets_copy_prop)) ^ "\n");
val _ = (print "every_inst_distinct_tar_reg_copy_prop_statement="; print_term(concl every_inst_distinct_tar_reg_copy_prop));
val _ = print("every_inst_distinct_tar_reg_copy_prop_hypotheses=" ^ Int.toString(length(hyp every_inst_distinct_tar_reg_copy_prop)) ^ "\n");
val _ = (print "extract_labels_copy_prop_statement="; print_term(concl extract_labels_copy_prop));
val _ = print("extract_labels_copy_prop_hypotheses=" ^ Int.toString(length(hyp extract_labels_copy_prop)) ^ "\n");
val _ = (print "flat_exp_conventions_copy_prop_statement="; print_term(concl flat_exp_conventions_copy_prop));
val _ = print("flat_exp_conventions_copy_prop_hypotheses=" ^ Int.toString(length(hyp flat_exp_conventions_copy_prop)) ^ "\n");
val _ = (print "pre_alloc_conventions_copy_prop_statement="; print_term(concl pre_alloc_conventions_copy_prop));
val _ = print("pre_alloc_conventions_copy_prop_hypotheses=" ^ Int.toString(length(hyp pre_alloc_conventions_copy_prop)) ^ "\n");
val _ = (print "full_inst_ok_less_copy_prop_statement="; print_term(concl full_inst_ok_less_copy_prop));
val _ = print("full_inst_ok_less_copy_prop_hypotheses=" ^ Int.toString(length(hyp full_inst_ok_less_copy_prop)) ^ "\n");
val _ = (print "three_to_two_reg_prog_wf_cutsets_statement="; print_term(concl three_to_two_reg_prog_wf_cutsets));
val _ = print("three_to_two_reg_prog_wf_cutsets_hypotheses=" ^ Int.toString(length(hyp three_to_two_reg_prog_wf_cutsets)) ^ "\n");
val _ = (print "wf_cutsets_remove_unreach_statement="; print_term(concl wf_cutsets_remove_unreach));
val _ = print("wf_cutsets_remove_unreach_hypotheses=" ^ Int.toString(length(hyp wf_cutsets_remove_unreach)) ^ "\n");
val _ = (print "full_ssa_cc_trans_wf_cutsets_statement="; print_term(concl full_ssa_cc_trans_wf_cutsets));
val _ = print("full_ssa_cc_trans_wf_cutsets_hypotheses=" ^ Int.toString(length(hyp full_ssa_cc_trans_wf_cutsets)) ^ "\n");
val _ = (print "pre_alloc_conventions_copy_prop_typed="; Lib.with_flag (Globals.show_types, true) print_term (concl pre_alloc_conventions_copy_prop));
val _ = (print "full_ssa_cc_trans_wf_cutsets_typed="; Lib.with_flag (Globals.show_types, true) print_term (concl full_ssa_cc_trans_wf_cutsets));
