load "word_cseProofTheory";
open HolKernel Parse bossLib word_cseProofTheory;
val _ = Globals.linewidth := 1000000;
val _ = (print "data_inv_merge_l_statement="; print_term(concl data_inv_merge_l));
val _ = print("data_inv_merge_l_hypotheses=" ^ Int.toString(length(hyp data_inv_merge_l)) ^ "\n");
val _ = (print "data_inv_merge_r_statement="; print_term(concl data_inv_merge_r));
val _ = print("data_inv_merge_r_hypotheses=" ^ Int.toString(length(hyp data_inv_merge_r)) ^ "\n");
val _ = (print "data_inv_insert_to_canonical_statement="; print_term(concl data_inv_insert_to_canonical));
val _ = print("data_inv_insert_to_canonical_hypotheses=" ^ Int.toString(length(hyp data_inv_insert_to_canonical)) ^ "\n");
val _ = (print "data_inv_insert_to_latest_statement="; print_term(concl data_inv_insert_to_latest));
val _ = print("data_inv_insert_to_latest_hypotheses=" ^ Int.toString(length(hyp data_inv_insert_to_latest)) ^ "\n");
val _ = (print "data_inv_set_store_statement="; print_term(concl data_inv_set_store));
val _ = print("data_inv_set_store_hypotheses=" ^ Int.toString(length(hyp data_inv_set_store)) ^ "\n");
val _ = (print "empty_data_loads_wipe_statement="; print_term(concl empty_data_loads_wipe));
val _ = print("empty_data_loads_wipe_hypotheses=" ^ Int.toString(length(hyp empty_data_loads_wipe)) ^ "\n");
val _ = (print "lookup_empty_data_statement="; print_term(concl lookup_empty_data));
val _ = print("lookup_empty_data_hypotheses=" ^ Int.toString(length(hyp lookup_empty_data)) ^ "\n");
val _ = (print "data_inv_register_read_statement="; print_term(concl data_inv_register_read));
val _ = print("data_inv_register_read_hypotheses=" ^ Int.toString(length(hyp data_inv_register_read)) ^ "\n");
val _ = (print "data_inv_register_reads_statement="; print_term(concl data_inv_register_reads));
val _ = print("data_inv_register_reads_hypotheses=" ^ Int.toString(length(hyp data_inv_register_reads)) ^ "\n");
val _ = (print "data_inv_set_fp_var_statement="; print_term(concl data_inv_set_fp_var));
val _ = print("data_inv_set_fp_var_hypotheses=" ^ Int.toString(length(hyp data_inv_set_fp_var)) ^ "\n");
val _ = (print "data_inv_set_vars_statement="; print_term(concl data_inv_set_vars));
val _ = print("data_inv_set_vars_hypotheses=" ^ Int.toString(length(hyp data_inv_set_vars)) ^ "\n");
val _ = (print "evaluate_Move1_statement="; print_term(concl evaluate_Move1));
val _ = print("evaluate_Move1_hypotheses=" ^ Int.toString(length(hyp evaluate_Move1)) ^ "\n");
val _ = (print "data_inv_set_store_typed="; Lib.with_flag (Globals.show_types, true) print_term (concl data_inv_set_store));
