load "word_to_wordProofTheory";
load "wordPropsTheory";
open HolKernel Parse bossLib word_to_wordProofTheory;
val _ = Globals.linewidth := 1000000;
fun pr_stmt label th = (print (label ^ "="); print_term (concl th); print "\n");
fun pr_hyps label th = (print (label ^ "="); print (Int.toString (length (hyp th))); print "\n");
fun pr_typed label th = (print (label ^ "="); Lib.with_flag (Globals.show_types, true) print_term (concl th); print "\n");
val _ = pr_stmt "cond16bit_inst_select_exp_prime_statement" cond16bit_inst_select_exp';
val _ = pr_hyps "cond16bit_inst_select_exp_prime_hypotheses" cond16bit_inst_select_exp';
val _ = pr_typed "cond16bit_inst_select_exp_prime_typed" cond16bit_inst_select_exp';
val _ = pr_stmt "cond16bit_inst_select_statement" cond16bit_inst_select;
val _ = pr_hyps "cond16bit_inst_select_hypotheses" cond16bit_inst_select;
val _ = pr_typed "cond16bit_inst_select_typed" cond16bit_inst_select;
val _ = pr_stmt "remove_must_terminate_no_share_inst_statement" remove_must_terminate_no_share_inst;
val _ = pr_hyps "remove_must_terminate_no_share_inst_hypotheses" remove_must_terminate_no_share_inst;
val _ = pr_typed "remove_must_terminate_no_share_inst_typed" remove_must_terminate_no_share_inst;
val _ = pr_stmt "full_compile_single_no_share_inst_statement" full_compile_single_no_share_inst;
val _ = pr_hyps "full_compile_single_no_share_inst_hypotheses" full_compile_single_no_share_inst;
val _ = pr_typed "full_compile_single_no_share_inst_typed" full_compile_single_no_share_inst;
val _ = pr_stmt "code_rel_not_created_subprogs_statement" code_rel_not_created_subprogs;
val _ = pr_hyps "code_rel_not_created_subprogs_hypotheses" code_rel_not_created_subprogs;
val _ = pr_typed "code_rel_not_created_subprogs_typed" code_rel_not_created_subprogs;
val _ = pr_stmt "no_mt_remove_must_terminate_const_statement" no_mt_remove_must_terminate_const;
val _ = pr_hyps "no_mt_remove_must_terminate_const_hypotheses" no_mt_remove_must_terminate_const;
val _ = pr_typed "no_mt_remove_must_terminate_const_typed" no_mt_remove_must_terminate_const;
val _ = pr_stmt "no_mt_full_compile_single_statement" no_mt_full_compile_single;
val _ = pr_hyps "no_mt_full_compile_single_hypotheses" no_mt_full_compile_single;
val _ = pr_typed "no_mt_full_compile_single_typed" no_mt_full_compile_single;
val _ = pr_stmt "no_mt_code_full_compile_single_statement" no_mt_code_full_compile_single;
val _ = pr_hyps "no_mt_code_full_compile_single_hypotheses" no_mt_code_full_compile_single;
val _ = pr_typed "no_mt_code_full_compile_single_typed" no_mt_code_full_compile_single;
val _ = pr_stmt "code_rel_ext_def_statement" code_rel_ext_def;
val _ = pr_hyps "code_rel_ext_def_hypotheses" code_rel_ext_def;
val _ = pr_typed "code_rel_ext_def_typed" code_rel_ext_def;
val _ = pr_stmt "code_rel_ext_word_to_word_statement" code_rel_ext_word_to_word;
val _ = pr_hyps "code_rel_ext_word_to_word_hypotheses" code_rel_ext_word_to_word;
val _ = pr_typed "code_rel_ext_word_to_word_typed" code_rel_ext_word_to_word;
val _ = pr_stmt "no_mt_code_rel_ext_statement" no_mt_code_rel_ext;
val _ = pr_hyps "no_mt_code_rel_ext_hypotheses" no_mt_code_rel_ext;
val _ = pr_typed "no_mt_code_rel_ext_typed" no_mt_code_rel_ext;
val _ = pr_stmt "code_rel_no_share_inst_statement" code_rel_no_share_inst;
val _ = pr_hyps "code_rel_no_share_inst_hypotheses" code_rel_no_share_inst;
val _ = pr_typed "code_rel_no_share_inst_typed" code_rel_no_share_inst;
val _ = pr_stmt "no_mt_code_def_statement" wordPropsTheory.no_mt_code_def;
val _ = pr_hyps "no_mt_code_def_hypotheses" wordPropsTheory.no_mt_code_def;
val _ = pr_typed "no_mt_code_def_typed" wordPropsTheory.no_mt_code_def;
