load "preamble"; load "word_gcFunctionsTheory";
open HolKernel Parse bossLib preamble word_gcFunctionsTheory;
val _ = Globals.linewidth := 1000000;
fun checked label th =
  (if null (hyp th) then () else raise Fail "open HOL hypotheses";
   print (label ^ "="); print_term (concl th); print "\n");
fun typed_statement label th =
  (show_types := true;
   print (label ^ "="); print_term (concl th); print "\n";
   show_types := false);
fun type_list label th =
  (show_types := true;
   print (label ^ "=");
   app (fn v => print (term_to_string v ^ ":" ^ type_to_string (type_of v) ^ ";"))
     (fst (strip_forall (concl th)) @ free_vars (concl th));
   print "\n";
   show_types := false);

(* Exported originals of word_gcFunctionsScript.sml:598-792. *)
val _ = checked "word_gc_fun_assum_has_fp_ops_statement" word_gc_fun_assum_has_fp_ops;
val _ = typed_statement "word_gc_fun_assum_has_fp_ops_statement_typed" word_gc_fun_assum_has_fp_ops;
val _ = type_list "word_gc_fun_assum_has_fp_ops_statement_types" word_gc_fun_assum_has_fp_ops;
val _ = checked "word_gc_move_has_fp_ops_statement" word_gc_move_has_fp_ops;
val _ = typed_statement "word_gc_move_has_fp_ops_statement_typed" word_gc_move_has_fp_ops;
val _ = type_list "word_gc_move_has_fp_ops_statement_types" word_gc_move_has_fp_ops;
val _ = checked "word_gen_gc_move_has_fp_ops_statement" word_gen_gc_move_has_fp_ops;
val _ = typed_statement "word_gen_gc_move_has_fp_ops_statement_typed" word_gen_gc_move_has_fp_ops;
val _ = type_list "word_gen_gc_move_has_fp_ops_statement_types" word_gen_gc_move_has_fp_ops;
val _ = checked "word_gen_gc_partial_move_has_fp_ops_statement" word_gen_gc_partial_move_has_fp_ops;
val _ = typed_statement "word_gen_gc_partial_move_has_fp_ops_statement_typed" word_gen_gc_partial_move_has_fp_ops;
val _ = type_list "word_gen_gc_partial_move_has_fp_ops_statement_types" word_gen_gc_partial_move_has_fp_ops;
val _ = checked "word_gc_move_list_has_fp_ops_statement" word_gc_move_list_has_fp_ops;
val _ = typed_statement "word_gc_move_list_has_fp_ops_statement_typed" word_gc_move_list_has_fp_ops;
val _ = type_list "word_gc_move_list_has_fp_ops_statement_types" word_gc_move_list_has_fp_ops;
val _ = checked "word_gen_gc_move_list_has_fp_ops_statement" word_gen_gc_move_list_has_fp_ops;
val _ = typed_statement "word_gen_gc_move_list_has_fp_ops_statement_typed" word_gen_gc_move_list_has_fp_ops;
val _ = type_list "word_gen_gc_move_list_has_fp_ops_statement_types" word_gen_gc_move_list_has_fp_ops;
val _ = checked "word_gen_gc_partial_move_list_has_fp_ops_statement" word_gen_gc_partial_move_list_has_fp_ops;
val _ = typed_statement "word_gen_gc_partial_move_list_has_fp_ops_statement_typed" word_gen_gc_partial_move_list_has_fp_ops;
val _ = type_list "word_gen_gc_partial_move_list_has_fp_ops_statement_types" word_gen_gc_partial_move_list_has_fp_ops;
val _ = checked "word_gc_move_roots_has_fp_ops_statement" word_gc_move_roots_has_fp_ops;
val _ = typed_statement "word_gc_move_roots_has_fp_ops_statement_typed" word_gc_move_roots_has_fp_ops;
val _ = type_list "word_gc_move_roots_has_fp_ops_statement_types" word_gc_move_roots_has_fp_ops;
val _ = checked "word_gen_gc_move_roots_has_fp_ops_statement" word_gen_gc_move_roots_has_fp_ops;
val _ = typed_statement "word_gen_gc_move_roots_has_fp_ops_statement_typed" word_gen_gc_move_roots_has_fp_ops;
val _ = type_list "word_gen_gc_move_roots_has_fp_ops_statement_types" word_gen_gc_move_roots_has_fp_ops;
val _ = checked "word_gen_gc_partial_move_roots_has_fp_ops_statement" word_gen_gc_partial_move_roots_has_fp_ops;
val _ = typed_statement "word_gen_gc_partial_move_roots_has_fp_ops_statement_typed" word_gen_gc_partial_move_roots_has_fp_ops;
val _ = type_list "word_gen_gc_partial_move_roots_has_fp_ops_statement_types" word_gen_gc_partial_move_roots_has_fp_ops;
val _ = checked "word_gc_move_loop_has_fp_ops_statement" word_gc_move_loop_has_fp_ops;
val _ = typed_statement "word_gc_move_loop_has_fp_ops_statement_typed" word_gc_move_loop_has_fp_ops;
val _ = type_list "word_gc_move_loop_has_fp_ops_statement_types" word_gc_move_loop_has_fp_ops;
val _ = checked "word_gen_gc_partial_move_data_has_fp_ops_statement" word_gen_gc_partial_move_data_has_fp_ops;
val _ = typed_statement "word_gen_gc_partial_move_data_has_fp_ops_statement_typed" word_gen_gc_partial_move_data_has_fp_ops;
val _ = type_list "word_gen_gc_partial_move_data_has_fp_ops_statement_types" word_gen_gc_partial_move_data_has_fp_ops;
val _ = checked "word_gen_gc_move_data_has_fp_ops_statement" word_gen_gc_move_data_has_fp_ops;
val _ = typed_statement "word_gen_gc_move_data_has_fp_ops_statement_typed" word_gen_gc_move_data_has_fp_ops;
val _ = type_list "word_gen_gc_move_data_has_fp_ops_statement_types" word_gen_gc_move_data_has_fp_ops;
val _ = checked "word_gen_gc_move_refs_has_fp_ops_statement" word_gen_gc_move_refs_has_fp_ops;
val _ = typed_statement "word_gen_gc_move_refs_has_fp_ops_statement_typed" word_gen_gc_move_refs_has_fp_ops;
val _ = type_list "word_gen_gc_move_refs_has_fp_ops_statement_types" word_gen_gc_move_refs_has_fp_ops;
val _ = checked "word_gen_gc_partial_move_ref_list_has_fp_ops_statement" word_gen_gc_partial_move_ref_list_has_fp_ops;
val _ = typed_statement "word_gen_gc_partial_move_ref_list_has_fp_ops_statement_typed" word_gen_gc_partial_move_ref_list_has_fp_ops;
val _ = type_list "word_gen_gc_partial_move_ref_list_has_fp_ops_statement_types" word_gen_gc_partial_move_ref_list_has_fp_ops;
val _ = checked "word_gen_gc_move_loop_has_fp_ops_statement" word_gen_gc_move_loop_has_fp_ops;
val _ = typed_statement "word_gen_gc_move_loop_has_fp_ops_statement_typed" word_gen_gc_move_loop_has_fp_ops;
val _ = type_list "word_gen_gc_move_loop_has_fp_ops_statement_types" word_gen_gc_move_loop_has_fp_ops;
val _ = checked "word_full_gc_has_fp_ops_statement" word_full_gc_has_fp_ops;
val _ = typed_statement "word_full_gc_has_fp_ops_statement_typed" word_full_gc_has_fp_ops;
val _ = type_list "word_full_gc_has_fp_ops_statement_types" word_full_gc_has_fp_ops;
val _ = checked "word_gen_gc_partial_full_has_fp_ops_statement" word_gen_gc_partial_full_has_fp_ops;
val _ = typed_statement "word_gen_gc_partial_full_has_fp_ops_statement_typed" word_gen_gc_partial_full_has_fp_ops;
val _ = type_list "word_gen_gc_partial_full_has_fp_ops_statement_types" word_gen_gc_partial_full_has_fp_ops;
val _ = checked "word_gen_gc_has_fp_ops_statement" word_gen_gc_has_fp_ops;
val _ = typed_statement "word_gen_gc_has_fp_ops_statement_typed" word_gen_gc_has_fp_ops;
val _ = type_list "word_gen_gc_has_fp_ops_statement_types" word_gen_gc_has_fp_ops;
val _ = checked "glob_real_has_fp_ops_statement" glob_real_has_fp_ops;
val _ = typed_statement "glob_real_has_fp_ops_statement_typed" glob_real_has_fp_ops;
val _ = type_list "glob_real_has_fp_ops_statement_types" glob_real_has_fp_ops;
val _ = checked "word_gc_fun_has_fp_ops_statement" word_gc_fun_has_fp_ops;
val _ = typed_statement "word_gc_fun_has_fp_ops_statement_typed" word_gc_fun_has_fp_ops;
val _ = type_list "word_gc_fun_has_fp_ops_statement_types" word_gc_fun_has_fp_ops;
