load "word_cseProofTheory";
open HolKernel Parse bossLib word_cseProofTheory;
val _ = Globals.linewidth := 1000000;
val _ = (print "firstRegOfArith_canonicalArith_statement="; print_term(concl firstRegOfArith_canonicalArith));
val _ = print("firstRegOfArith_canonicalArith_hypotheses=" ^ Int.toString(length(hyp firstRegOfArith_canonicalArith)) ^ "\n");
val _ = (print "lookup_listCmp_empty_statement="; print_term(concl lookup_listCmp_empty));
val _ = print("lookup_listCmp_empty_hypotheses=" ^ Int.toString(length(hyp lookup_listCmp_empty)) ^ "\n");
val _ = (print "invariant_listCmp_empty_statement="; print_term(concl invariant_listCmp_empty));
val _ = print("invariant_listCmp_empty_hypotheses=" ^ Int.toString(length(hyp invariant_listCmp_empty)) ^ "\n");
val _ = (print "lookup_insert_listCmp_statement="; print_term(concl lookup_insert_listCmp));
val _ = print("lookup_insert_listCmp_hypotheses=" ^ Int.toString(length(hyp lookup_insert_listCmp)) ^ "\n");
val _ = (print "register_read_simps_statement="; print_term(concl register_read_simps));
val _ = print("register_read_simps_hypotheses=" ^ Int.toString(length(hyp register_read_simps)) ^ "\n");
val _ = (print "register_reads_simps_statement="; print_term(concl register_reads_simps));
val _ = print("register_reads_simps_hypotheses=" ^ Int.toString(length(hyp register_reads_simps)) ^ "\n");
val _ = (print "lookup_register_read_statement="; print_term(concl lookup_register_read));
val _ = print("lookup_register_read_hypotheses=" ^ Int.toString(length(hyp lookup_register_read)) ^ "\n");
val _ = (print "lookup_register_reads_statement="; print_term(concl lookup_register_reads));
val _ = print("lookup_register_reads_hypotheses=" ^ Int.toString(length(hyp lookup_register_reads)) ^ "\n");
val _ = (print "lookup_insert_listCmp_typed="; Lib.with_flag (Globals.show_types, true) print_term (concl lookup_insert_listCmp));
