load "word_cseProofTheory";
open HolKernel Parse bossLib word_cseProofTheory;
val _ = Globals.linewidth := 1000000;
val _ = (print "canonicalArith_correct_statement="; print_term(concl canonicalArith_correct));
val _ = print("canonicalArith_correct_hypotheses=" ^ Int.toString(length(hyp canonicalArith_correct)) ^ "\n");
val _ = (print "data_inv_locals_statement="; print_term(concl data_inv_locals));
val _ = print("data_inv_locals_hypotheses=" ^ Int.toString(length(hyp data_inv_locals)) ^ "\n");
val _ = (print "wf_data_untracked_statement="; print_term(concl wf_data_untracked));
val _ = print("wf_data_untracked_hypotheses=" ^ Int.toString(length(hyp wf_data_untracked)) ^ "\n");
val _ = (print "data_inv_set_var_statement="; print_term(concl data_inv_set_var));
val _ = print("data_inv_set_var_hypotheses=" ^ Int.toString(length(hyp data_inv_set_var)) ^ "\n");
val _ = (print "data_inv_unset_var_statement="; print_term(concl data_inv_unset_var));
val _ = print("data_inv_unset_var_hypotheses=" ^ Int.toString(length(hyp data_inv_unset_var)) ^ "\n");
val _ = (print "not_seen_data_inv_alist_insert_statement="; print_term(concl not_seen_data_inv_alist_insert));
val _ = print("not_seen_data_inv_alist_insert_hypotheses=" ^ Int.toString(length(hyp not_seen_data_inv_alist_insert)) ^ "\n");
val _ = (print "data_inv_memory_statement="; print_term(concl data_inv_memory));
val _ = print("data_inv_memory_hypotheses=" ^ Int.toString(length(hyp data_inv_memory)) ^ "\n");
val _ = (print "data_inv_state_agree_statement="; print_term(concl data_inv_state_agree));
val _ = print("data_inv_state_agree_hypotheses=" ^ Int.toString(length(hyp data_inv_state_agree)) ^ "\n");
val _ = (print "data_inv_state_agree_typed="; Lib.with_flag (Globals.show_types, true) print_term (concl data_inv_state_agree));
