load "word_cseProofTheory";
open HolKernel Parse bossLib word_cseProofTheory;
val _ = Globals.linewidth := 1000000;
val _ = (print "wf_data_empty_statement="; print_term(concl wf_data_empty));
val _ = print("wf_data_empty_hypotheses=" ^ Int.toString(length(hyp wf_data_empty)) ^ "\n");
val _ = (print "wf_data_loads_wipe_statement="; print_term(concl wf_data_loads_wipe));
val _ = print("wf_data_loads_wipe_hypotheses=" ^ Int.toString(length(hyp wf_data_loads_wipe)) ^ "\n");
val _ = (print "wf_data_invalidate_statement="; print_term(concl wf_data_invalidate));
val _ = print("wf_data_invalidate_hypotheses=" ^ Int.toString(length(hyp wf_data_invalidate)) ^ "\n");
val _ = (print "wf_data_invalidate_regs_statement="; print_term(concl wf_data_invalidate_regs));
val _ = print("wf_data_invalidate_regs_hypotheses=" ^ Int.toString(length(hyp wf_data_invalidate_regs)) ^ "\n");
val _ = (print "wf_data_insert_to_canonical_statement="; print_term(concl wf_data_insert_to_canonical));
val _ = print("wf_data_insert_to_canonical_hypotheses=" ^ Int.toString(length(hyp wf_data_insert_to_canonical)) ^ "\n");
val _ = (print "wf_data_insert_to_latest_statement="; print_term(concl wf_data_insert_to_latest));
val _ = print("wf_data_insert_to_latest_hypotheses=" ^ Int.toString(length(hyp wf_data_insert_to_latest)) ^ "\n");
val _ = (print "wf_data_register_read_statement="; print_term(concl wf_data_register_read));
val _ = print("wf_data_register_read_hypotheses=" ^ Int.toString(length(hyp wf_data_register_read)) ^ "\n");
val _ = (print "wf_data_register_reads_statement="; print_term(concl wf_data_register_reads));
val _ = print("wf_data_register_reads_hypotheses=" ^ Int.toString(length(hyp wf_data_register_reads)) ^ "\n");
val _ = (print "wf_add_to_data_aux_statement="; print_term(concl wf_add_to_data_aux));
val _ = print("wf_add_to_data_aux_hypotheses=" ^ Int.toString(length(hyp wf_add_to_data_aux)) ^ "\n");
val _ = (print "wf_add_to_data_const_statement="; print_term(concl wf_add_to_data_const));
val _ = print("wf_add_to_data_const_hypotheses=" ^ Int.toString(length(hyp wf_add_to_data_const)) ^ "\n");
val _ = (print "wf_add_to_load_aux_statement="; print_term(concl wf_add_to_load_aux));
val _ = print("wf_add_to_load_aux_hypotheses=" ^ Int.toString(length(hyp wf_add_to_load_aux)) ^ "\n");
val _ = (print "wf_data_merge_statement="; print_term(concl wf_data_merge));
val _ = print("wf_data_merge_hypotheses=" ^ Int.toString(length(hyp wf_data_merge)) ^ "\n");
val _ = (print "wf_canonicalMoveRegs_statement="; print_term(concl wf_canonicalMoveRegs));
val _ = print("wf_canonicalMoveRegs_hypotheses=" ^ Int.toString(length(hyp wf_canonicalMoveRegs)) ^ "\n");
val _ = (print "wf_add_to_data_aux_typed="; Lib.with_flag (Globals.show_types, true) print_term (concl wf_add_to_data_aux));
