load "preamble"; load "word_to_stackProofTheory";
open HolKernel Parse bossLib preamble word_to_stackProofTheory;
val _ = Globals.linewidth := 1000000;
val fpLess_result = GEN_ALL (Q.SPEC `(asm$FP (asm$FPLess r d1 d2) : 'a asm$inst)` word_to_stackProofTheory.evaluate_wInst);
val _ = if null(hyp fpLess_result) andalso null(free_vars(concl fpLess_result)) then () else raise Fail "open fpLess case";
val _ = (print "fpLess_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl fpLess_result); print "\n");
val _ = print("fpLess_proved=" ^ term_to_string(rhs(concl(EQT_INTRO fpLess_result))) ^ "\n");
val _ = print("fpLess_hypotheses=" ^ Int.toString(length(hyp fpLess_result)) ^ "\n");
val fpLessEqual_result = GEN_ALL (Q.SPEC `(asm$FP (asm$FPLessEqual r d1 d2) : 'a asm$inst)` word_to_stackProofTheory.evaluate_wInst);
val _ = if null(hyp fpLessEqual_result) andalso null(free_vars(concl fpLessEqual_result)) then () else raise Fail "open fpLessEqual case";
val _ = (print "fpLessEqual_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl fpLessEqual_result); print "\n");
val _ = print("fpLessEqual_proved=" ^ term_to_string(rhs(concl(EQT_INTRO fpLessEqual_result))) ^ "\n");
val _ = print("fpLessEqual_hypotheses=" ^ Int.toString(length(hyp fpLessEqual_result)) ^ "\n");
val fpEqual_result = GEN_ALL (Q.SPEC `(asm$FP (asm$FPEqual r d1 d2) : 'a asm$inst)` word_to_stackProofTheory.evaluate_wInst);
val _ = if null(hyp fpEqual_result) andalso null(free_vars(concl fpEqual_result)) then () else raise Fail "open fpEqual case";
val _ = (print "fpEqual_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl fpEqual_result); print "\n");
val _ = print("fpEqual_proved=" ^ term_to_string(rhs(concl(EQT_INTRO fpEqual_result))) ^ "\n");
val _ = print("fpEqual_hypotheses=" ^ Int.toString(length(hyp fpEqual_result)) ^ "\n");
val fpMov_result = GEN_ALL (Q.SPEC `(asm$FP (asm$FPMov d1 d2) : 'a asm$inst)` word_to_stackProofTheory.evaluate_wInst);
val _ = if null(hyp fpMov_result) andalso null(free_vars(concl fpMov_result)) then () else raise Fail "open fpMov case";
val _ = (print "fpMov_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl fpMov_result); print "\n");
val _ = print("fpMov_proved=" ^ term_to_string(rhs(concl(EQT_INTRO fpMov_result))) ^ "\n");
val _ = print("fpMov_hypotheses=" ^ Int.toString(length(hyp fpMov_result)) ^ "\n");
val fpAbs_result = GEN_ALL (Q.SPEC `(asm$FP (asm$FPAbs d1 d2) : 'a asm$inst)` word_to_stackProofTheory.evaluate_wInst);
val _ = if null(hyp fpAbs_result) andalso null(free_vars(concl fpAbs_result)) then () else raise Fail "open fpAbs case";
val _ = (print "fpAbs_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl fpAbs_result); print "\n");
val _ = print("fpAbs_proved=" ^ term_to_string(rhs(concl(EQT_INTRO fpAbs_result))) ^ "\n");
val _ = print("fpAbs_hypotheses=" ^ Int.toString(length(hyp fpAbs_result)) ^ "\n");
val fpNeg_result = GEN_ALL (Q.SPEC `(asm$FP (asm$FPNeg d1 d2) : 'a asm$inst)` word_to_stackProofTheory.evaluate_wInst);
val _ = if null(hyp fpNeg_result) andalso null(free_vars(concl fpNeg_result)) then () else raise Fail "open fpNeg case";
val _ = (print "fpNeg_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl fpNeg_result); print "\n");
val _ = print("fpNeg_proved=" ^ term_to_string(rhs(concl(EQT_INTRO fpNeg_result))) ^ "\n");
val _ = print("fpNeg_hypotheses=" ^ Int.toString(length(hyp fpNeg_result)) ^ "\n");
val fpSqrt_result = GEN_ALL (Q.SPEC `(asm$FP (asm$FPSqrt d1 d2) : 'a asm$inst)` word_to_stackProofTheory.evaluate_wInst);
val _ = if null(hyp fpSqrt_result) andalso null(free_vars(concl fpSqrt_result)) then () else raise Fail "open fpSqrt case";
val _ = (print "fpSqrt_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl fpSqrt_result); print "\n");
val _ = print("fpSqrt_proved=" ^ term_to_string(rhs(concl(EQT_INTRO fpSqrt_result))) ^ "\n");
val _ = print("fpSqrt_hypotheses=" ^ Int.toString(length(hyp fpSqrt_result)) ^ "\n");
val fpAdd_result = GEN_ALL (Q.SPEC `(asm$FP (asm$FPAdd d1 d2 d3) : 'a asm$inst)` word_to_stackProofTheory.evaluate_wInst);
val _ = if null(hyp fpAdd_result) andalso null(free_vars(concl fpAdd_result)) then () else raise Fail "open fpAdd case";
val _ = (print "fpAdd_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl fpAdd_result); print "\n");
val _ = print("fpAdd_proved=" ^ term_to_string(rhs(concl(EQT_INTRO fpAdd_result))) ^ "\n");
val _ = print("fpAdd_hypotheses=" ^ Int.toString(length(hyp fpAdd_result)) ^ "\n");
val fpSub_result = GEN_ALL (Q.SPEC `(asm$FP (asm$FPSub d1 d2 d3) : 'a asm$inst)` word_to_stackProofTheory.evaluate_wInst);
val _ = if null(hyp fpSub_result) andalso null(free_vars(concl fpSub_result)) then () else raise Fail "open fpSub case";
val _ = (print "fpSub_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl fpSub_result); print "\n");
val _ = print("fpSub_proved=" ^ term_to_string(rhs(concl(EQT_INTRO fpSub_result))) ^ "\n");
val _ = print("fpSub_hypotheses=" ^ Int.toString(length(hyp fpSub_result)) ^ "\n");
val fpMul_result = GEN_ALL (Q.SPEC `(asm$FP (asm$FPMul d1 d2 d3) : 'a asm$inst)` word_to_stackProofTheory.evaluate_wInst);
val _ = if null(hyp fpMul_result) andalso null(free_vars(concl fpMul_result)) then () else raise Fail "open fpMul case";
val _ = (print "fpMul_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl fpMul_result); print "\n");
val _ = print("fpMul_proved=" ^ term_to_string(rhs(concl(EQT_INTRO fpMul_result))) ^ "\n");
val _ = print("fpMul_hypotheses=" ^ Int.toString(length(hyp fpMul_result)) ^ "\n");
val fpDiv_result = GEN_ALL (Q.SPEC `(asm$FP (asm$FPDiv d1 d2 d3) : 'a asm$inst)` word_to_stackProofTheory.evaluate_wInst);
val _ = if null(hyp fpDiv_result) andalso null(free_vars(concl fpDiv_result)) then () else raise Fail "open fpDiv case";
val _ = (print "fpDiv_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl fpDiv_result); print "\n");
val _ = print("fpDiv_proved=" ^ term_to_string(rhs(concl(EQT_INTRO fpDiv_result))) ^ "\n");
val _ = print("fpDiv_hypotheses=" ^ Int.toString(length(hyp fpDiv_result)) ^ "\n");
val fpFma_result = GEN_ALL (Q.SPEC `(asm$FP (asm$FPFma d1 d2 d3) : 'a asm$inst)` word_to_stackProofTheory.evaluate_wInst);
val _ = if null(hyp fpFma_result) andalso null(free_vars(concl fpFma_result)) then () else raise Fail "open fpFma case";
val _ = (print "fpFma_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl fpFma_result); print "\n");
val _ = print("fpFma_proved=" ^ term_to_string(rhs(concl(EQT_INTRO fpFma_result))) ^ "\n");
val _ = print("fpFma_hypotheses=" ^ Int.toString(length(hyp fpFma_result)) ^ "\n");
val fpMovToReg_result = GEN_ALL (Q.SPEC `(asm$FP (asm$FPMovToReg r1 r2 d) : 'a asm$inst)` word_to_stackProofTheory.evaluate_wInst);
val _ = if null(hyp fpMovToReg_result) andalso null(free_vars(concl fpMovToReg_result)) then () else raise Fail "open fpMovToReg case";
val _ = (print "fpMovToReg_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl fpMovToReg_result); print "\n");
val _ = print("fpMovToReg_proved=" ^ term_to_string(rhs(concl(EQT_INTRO fpMovToReg_result))) ^ "\n");
val _ = print("fpMovToReg_hypotheses=" ^ Int.toString(length(hyp fpMovToReg_result)) ^ "\n");
val fpMovFromReg_result = GEN_ALL (Q.SPEC `(asm$FP (asm$FPMovFromReg d r1 r2) : 'a asm$inst)` word_to_stackProofTheory.evaluate_wInst);
val _ = if null(hyp fpMovFromReg_result) andalso null(free_vars(concl fpMovFromReg_result)) then () else raise Fail "open fpMovFromReg case";
val _ = (print "fpMovFromReg_typed="; Lib.with_flag (Globals.show_types,true) print_term (concl fpMovFromReg_result); print "\n");
val _ = print("fpMovFromReg_proved=" ^ term_to_string(rhs(concl(EQT_INTRO fpMovFromReg_result))) ^ "\n");
val _ = print("fpMovFromReg_hypotheses=" ^ Int.toString(length(hyp fpMovFromReg_result)) ^ "\n");
