load "bossLib"; load "preamble"; load "word_to_wordTheory";
open bossLib HolKernel Parse preamble word_to_wordTheory;
val th = DB.fetch "word_to_word" "compile_single_def";
val _ = show_types := false;
val _ = print "compile_single=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = show_types := true;
val _ = print "compile_single_typed=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print ("compile_single_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val th = DB.fetch "word_to_word" "full_compile_single_def";
val _ = show_types := false;
val _ = print "full_compile_single=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = show_types := true;
val _ = print "full_compile_single_typed=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print ("full_compile_single_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
val th = DB.fetch "word_to_word" "compile_def";
val _ = show_types := false;
val _ = print "compile=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = show_types := true;
val _ = print "compile_typed=";
val _ = print_term (concl th);
val _ = print "\n";
val _ = print ("compile_hypotheses=" ^ Int.toString (length (hyp th)) ^ "\n");
