load "preamble"; load "word_to_stackProofTheory";
open HolKernel Parse bossLib preamble word_to_stackProofTheory;
val _ = Globals.linewidth := 1000000;
val result = GEN_ALL (Q.SPEC `(asm$Mem asm$Store store_value_register (asm$Addr store_base store_offset) : 'a asm$inst)` word_to_stackProofTheory.evaluate_wInst);
val _ = if null(hyp result) andalso null(free_vars(concl result)) then () else raise Fail "open memory-store case";
val _ = (print "memoryStore_typed="; Lib.with_flag (Globals.show_types,true) print_term(concl result));
val _ = print("memoryStore_proved=" ^ term_to_string(rhs(concl(EQT_INTRO result))) ^ "\n");
val _ = print("memoryStore_hypotheses=" ^ Int.toString(length(hyp result)) ^ "\n");
val result = GEN_ALL (Q.SPEC `(asm$Mem asm$Store8 store_value_register (asm$Addr store_base store_offset) : 'a asm$inst)` word_to_stackProofTheory.evaluate_wInst);
val _ = if null(hyp result) andalso null(free_vars(concl result)) then () else raise Fail "open memory-store case";
val _ = (print "memoryStore8_typed="; Lib.with_flag (Globals.show_types,true) print_term(concl result));
val _ = print("memoryStore8_proved=" ^ term_to_string(rhs(concl(EQT_INTRO result))) ^ "\n");
val _ = print("memoryStore8_hypotheses=" ^ Int.toString(length(hyp result)) ^ "\n");
val result = GEN_ALL (Q.SPEC `(asm$Mem asm$Store32 store_value_register (asm$Addr store_base store_offset) : 'a asm$inst)` word_to_stackProofTheory.evaluate_wInst);
val _ = if null(hyp result) andalso null(free_vars(concl result)) then () else raise Fail "open memory-store case";
val _ = (print "memoryStore32_typed="; Lib.with_flag (Globals.show_types,true) print_term(concl result));
val _ = print("memoryStore32_proved=" ^ term_to_string(rhs(concl(EQT_INTRO result))) ^ "\n");
val _ = print("memoryStore32_hypotheses=" ^ Int.toString(length(hyp result)) ^ "\n");
