import Flapjack.CrepeTemporaryAssignmentCorrectness

/-!
Correctness infrastructure for the compiler-owned global payload area.

`compileProg` lowers a raised structured value by evaluating temporary locals
and then running `storeGlobals` on the corresponding `.var` expressions.  The
word and two-word raise proofs previously unfolded this sequence manually;
these lemmas provide the list-shaped fact needed by the arbitrary-payload
Raise branch.
-/

namespace Flapjack

/-! A direct recursive form is useful when the address list is generated by
`storeGlobals`; it avoids introducing any algebraic assumptions about word
addresses beyond the evaluator's existing `Add` operation. -/
def updateMemoryListAt [BEq α] [Add α]
    (memory : α → Option α) (address stride : α) : List α → α → Option α
  | [], current => memory current
  | value :: values, current =>
      updateMemoryListAt (updateMemory memory address value)
        (address + stride) stride values current

theorem updateMemoryListAt_nil [BEq α] [Add α]
    (memory : α → Option α) (address stride : α) :
    updateMemoryListAt memory address stride [] = memory := by
  simp [updateMemoryListAt]

theorem updateMemoryListAt_cons [BEq α] [Add α]
    (memory : α → Option α) (address stride value : α) (values : List α) :
    updateMemoryListAt memory address stride (value :: values) =
      updateMemoryListAt (updateMemory memory address value)
        (address + stride) stride values := by
  simp [updateMemoryListAt]

def storeAddresses [Add α] (address stride : α) : Nat → List α
  | 0 => []
  | count + 1 => address :: storeAddresses (address + stride) stride count

def readMemoryListAt [Add α]
    (memory : α → Option α) (address stride : α) : Nat → Option (List α)
  | 0 => some []
  | count + 1 => do
      let value ← memory address
      let values ← readMemoryListAt memory (address + stride) stride count
      pure (value :: values)

theorem updateMemoryListAt_preserve_of_not_mem
    [BEq α] [LawfulBEq α] [Add α]
    (memory : α → Option α) (address stride : α)
    (values : List α) (current : α)
    (hnot : current ∉ storeAddresses address stride values.length) :
    updateMemoryListAt memory address stride values current = memory current := by
  induction values generalizing memory address current with
  | nil => simp [updateMemoryListAt]
  | cons value values ih =>
      rw [updateMemoryListAt_cons]
      have hhead : current ≠ address := by
        intro heq
        apply hnot
        simp [storeAddresses, heq]
      have htail : current ∉
          storeAddresses (address + stride) stride values.length := by
        intro hmem
        apply hnot
        simp [storeAddresses, hmem]
      calc
        updateMemoryListAt (updateMemory memory address value)
            (address + stride) stride values current =
            updateMemory memory address value current :=
          ih (memory := updateMemory memory address value)
            (address := address + stride) (current := current) htail
        _ = memory current := by simp [updateMemory, hhead]

theorem readMemoryListAt_updateMemoryListAt
    [BEq α] [LawfulBEq α] [Add α]
    (memory : α → Option α) (address stride : α)
    (values : List α)
    (hdistinct : List.Pairwise (fun left right : α => left ≠ right)
      (storeAddresses address stride values.length)) :
    readMemoryListAt
        (updateMemoryListAt memory address stride values)
        address stride values.length = some values := by
  induction values generalizing memory address with
  | nil => simp [readMemoryListAt, updateMemoryListAt]
  | cons value values ih =>
      rw [updateMemoryListAt_cons]
      change List.Pairwise (fun left right : α => left ≠ right)
        (address :: storeAddresses (address + stride) stride values.length)
        at hdistinct
      simp only [List.pairwise_cons] at hdistinct
      have hheadPreserve :
          updateMemoryListAt (updateMemory memory address value)
              (address + stride) stride values address =
            updateMemory memory address value address :=
        updateMemoryListAt_preserve_of_not_mem
          (updateMemory memory address value) (address + stride) stride values
          address (by
            intro hmem
            exact (hdistinct.1 address hmem) rfl)
      have hhead :
          updateMemoryListAt (updateMemory memory address value)
              (address + stride) stride values address = some value := by
        rw [hheadPreserve]
        simp [updateMemory]
      have htail := ih (memory := updateMemory memory address value)
        (address := address + stride) hdistinct.2
      simp [readMemoryListAt, hhead, htail]

/-! Stateful counterpart of the existing compact nested-declaration stability
lemma.  This is the exact witness constructor used when the declaration body
performs global stores, so converting through the compact evaluator would lose
the very state component that the Raise proof must observe. -/
theorem crepNestedDecsStateEval_of_evalExps_stable
    [BEq α] [OfNat α 0] [OfNat α 1] [Add α] [Mul α]
    [Sub α] [AndOp α] [OrOp α] [HXor α α α]
    [ShiftLeft α] [ShiftRight α] [LT α]
    [DecidableRel (fun left right : α => left < right)] [PanCmp α]
    (functions : List (CompiledFunction α))
    (primitive : CrepPrimitiveHandler α) (ffi : CrepFfiHandler α)
    (sharedMem : CrepSharedMemHandler α)
    (baseAddress topAddress : α) (fuel : Nat)
    (state : CrepState α) (names : List Nat)
    (expressions : List (CrepExp α)) (body : CrepProg α)
    (result : CrepControlResult α) (values : List α)
    (hlength : names.length = expressions.length)
    (hnot : ∀ name ∈ names, ∀ expression ∈ expressions,
      name ∉ crepExpVars expression)
    (heval : evalCrepFullExpsState state baseAddress topAddress expressions =
      some values)
    (hbody : evalCrepFullProgState functions primitive ffi sharedMem
      baseAddress topAddress fuel
      { state with locals := updateCrepLocalList state.locals names values } body =
      some result) :
    CrepNestedDecsStateEval functions primitive ffi sharedMem
      baseAddress topAddress fuel state names expressions body result := by
  induction names generalizing state expressions values with
  | nil =>
      cases expressions with
      | nil =>
          cases values with
          | nil =>
              simpa [CrepNestedDecsStateEval, updateCrepLocalList] using hbody
          | cons value values =>
              simp [evalCrepFullExpsState] at heval
      | cons expression expressions =>
          simp at hlength
  | cons name names ih =>
      cases expressions with
      | nil =>
          simp at hlength
      | cons expression expressions =>
          cases values with
          | nil =>
              cases hhead : evalCrepFullExpState state
                  baseAddress topAddress expression with
              | none => simp [evalCrepFullExpsState, hhead] at heval
              | some headValue =>
                  cases htail : evalCrepFullExpsState state
                      baseAddress topAddress expressions with
                  | none => simp [evalCrepFullExpsState, hhead, htail] at heval
                  | some tailValues =>
                      simp [evalCrepFullExpsState, hhead, htail] at heval
          | cons value values =>
              have hlengthTail : names.length = expressions.length := by
                simp at hlength
                exact hlength
              cases hhead : evalCrepFullExpState state
                  baseAddress topAddress expression with
              | none =>
                  simp [evalCrepFullExpsState, hhead] at heval
              | some headValue =>
                  cases htail : evalCrepFullExpsState state
                      baseAddress topAddress expressions with
                  | none =>
                      simp [evalCrepFullExpsState, hhead, htail] at heval
                  | some tailValues =>
                      have hvalues : headValue :: tailValues = value :: values := by
                        simpa [evalCrepFullExpsState, hhead, htail] using heval
                      cases hvalues
                      have htailStable :
                          evalCrepFullExpsState
                            { state with locals :=
                                updateCrepLocal state.locals name value }
                            baseAddress topAddress expressions = some values := by
                        exact evalCrepFullExpsState_update_of_forall_not_mem
                          state baseAddress topAddress expressions name value
                          (fun current hcurrent =>
                            hnot name (by simp) current (by simp [hcurrent]))
                          values htail
                      have hnotTail : ∀ current ∈ names,
                          ∀ currentExpression ∈ expressions,
                            current ∉ crepExpVars currentExpression := by
                        intro current hcurrent currentExpression hcurrentExpression
                        exact hnot current (by simp [hcurrent]) currentExpression
                          (by simp [hcurrentExpression])
                      have hbodyTail :
                          evalCrepFullProgState functions primitive ffi sharedMem
                            baseAddress topAddress fuel
                            { state with locals := updateCrepLocalList (updateCrepLocal state.locals name value) names values }
                            body = some result := by
                        simpa [updateCrepLocalList] using hbody
                      refine ⟨value, hhead, ?_⟩
                      exact ih (state := { state with
                          locals := updateCrepLocal state.locals name value })
                        (expressions := expressions) (values := values)
                        hlengthTail hnotTail htailStable hbodyTail

/-! State-aware specialization of Cake
    `pan_to_crepProps$evaluate_nested_decs_load_globals`.  Unlike the compact
    evaluator, this form obtains each generated value from `state.globals`. -/
theorem crepNestedDecsStateEval_loadGlobals_of_evalExps
    [BEq α] [OfNat α 0] [OfNat α 1] [Add α] [Mul α]
    [Sub α] [AndOp α] [OrOp α] [HXor α α α]
    [ShiftLeft α] [ShiftRight α] [LT α]
    [DecidableRel (fun left right : α => left < right)] [PanCmp α]
    (functions : List (CompiledFunction α))
    (primitive : CrepPrimitiveHandler α) (ffi : CrepFfiHandler α)
    (sharedMem : CrepSharedMemHandler α)
    (baseAddress topAddress address stride : α) (fuel : Nat)
    (state : CrepState α) (names : List Nat) (count : Nat)
    (body : CrepProg α) (result : CrepControlResult α) (values : List α)
    (hcount : names.length = count)
    (heval : evalCrepFullExpsState state
      baseAddress topAddress (loadGlobals address stride count) = some values)
    (hbody : evalCrepFullProgState functions primitive ffi sharedMem
      baseAddress topAddress fuel
      { state with locals := updateCrepLocalList state.locals names values } body =
      some result) :
    CrepNestedDecsStateEval functions primitive ffi sharedMem
      baseAddress topAddress fuel state names
      (loadGlobals address stride count) body result := by
  apply crepNestedDecsStateEval_of_evalExps_stable
  · exact hcount.trans (loadGlobals_length address stride count).symm
  · intro name hname expression hexpression hvariable
    have hmem : name ∈ (loadGlobals address stride count).flatMap crepExpVars :=
      List.mem_flatMap.mpr ⟨expression, hexpression, hvariable⟩
    rw [loadGlobals_crepExpVars_empty] at hmem
    simp at hmem
  · exact heval
  · exact hbody

theorem evalCrepFullProgState_nestedDecs_loadGlobals_of_evalExps
    [BEq α] [OfNat α 0] [OfNat α 1] [Add α] [Mul α]
    [Sub α] [AndOp α] [OrOp α] [HXor α α α]
    [ShiftLeft α] [ShiftRight α] [LT α]
    [DecidableRel (fun left right : α => left < right)] [PanCmp α]
    (functions : List (CompiledFunction α))
    (primitive : CrepPrimitiveHandler α) (ffi : CrepFfiHandler α)
    (sharedMem : CrepSharedMemHandler α)
    (baseAddress topAddress address stride : α) (fuel : Nat)
    (state : CrepState α) (names : List Nat) (count : Nat)
    (body : CrepProg α) (result : CrepControlResult α) (values : List α)
    (hcount : names.length = count)
    (hdistinct : CrepDistinctNames names)
    (heval : evalCrepFullExpsState state
      baseAddress topAddress (loadGlobals address stride count) = some values)
    (hbody : evalCrepFullProgState functions primitive ffi sharedMem
      baseAddress topAddress fuel
      { state with locals := updateCrepLocalList state.locals names values } body =
      some result) :
    evalCrepFullProgState functions primitive ffi sharedMem
      baseAddress topAddress (fuel + names.length) state
      (nestedDecs names (loadGlobals address stride count) body) =
      some (restoreCrepResultList state.locals names result) := by
  have hnested := crepNestedDecsStateEval_loadGlobals_of_evalExps
    functions primitive ffi sharedMem baseAddress topAddress address stride fuel
    state names count body result values hcount heval hbody
  exact evalCrepFullProgState_nestedDecs_of_eval
    functions primitive ffi sharedMem baseAddress topAddress fuel state names
    (loadGlobals address stride count) body result hdistinct hnested

set_option linter.unusedSimpArgs false in
theorem evalCrepFullProgState_storeGlobals_vars
    [BEq α] [LawfulBEq α] [OfNat α 0] [OfNat α 1] [Add α] [Mul α]
    [Sub α] [AndOp α] [OrOp α] [HXor α α α] [ShiftLeft α] [ShiftRight α]
    [LT α] [DecidableRel (fun left right : α => left < right)] [PanCmp α]
    (functions : List (CompiledFunction α))
    (primitive : CrepPrimitiveHandler α) (ffi : CrepFfiHandler α)
    (sharedMem : CrepSharedMemHandler α)
    (baseAddress topAddress : α) (state : CrepState α)
    (address stride : α) (names : List Nat) (values : List α)
    (hlength : names.length = values.length)
    (hvalues : evalCrepFullExpsState state baseAddress topAddress
      (names.map (fun name => .var name)) = some values) :
    evalCrepFullProgState functions primitive ffi sharedMem
      baseAddress topAddress (values.length + 1) state
      (crepNestedSeq (storeGlobals address stride
        (names.map (fun name => .var name)))) =
      some (.normal { state with
        globals := updateMemoryListAt state.globals address stride values }) := by
  induction names generalizing state address values with
  | nil =>
      cases values with
      | nil =>
          simp [crepNestedSeq, storeGlobals, evalCrepFullProgState,
            evalCrepFullExpsState, updateMemoryListAt]
      | cons value values =>
          simp at hlength
  | cons name names ih =>
      cases values with
      | nil =>
          simp at hlength
      | cons value values =>
          simp only [List.map_cons, evalCrepFullExpsState] at hvalues
          cases hname : evalCrepFullExpState state baseAddress topAddress
              (.var name) with
          | none => simp [hname] at hvalues
          | some nameValue =>
              cases htail : evalCrepFullExpsState state baseAddress topAddress
                  (names.map (fun name => .var name)) with
              | none => simp [hname, htail] at hvalues
              | some tailValues =>
                  have hpair : nameValue :: tailValues = value :: values :=
                    Option.some.inj (by simpa [hname, htail] using hvalues)
                  cases hpair
                  have hlength' : names.length = values.length := by
                    exact Nat.succ.inj hlength
                  have htailEval : evalCrepFullExpsState state baseAddress topAddress
                      (names.map (fun name => .var name)) = some values := by
                    exact htail
                  have hnameEval : evalCrepFullExpState state
                      baseAddress topAddress (.var name) = some value := by
                    exact hname
                  let nextState : CrepState α :=
                    { state with globals := updateMemory state.globals address value }
                  have htailEval' : evalCrepFullExpsState nextState
                      baseAddress topAddress
                      (names.map (fun name => .var name)) = some values := by
                    have hvars : ∀ (current : CrepState α),
                        current.locals = state.locals →
                        ∀ (currentNames : List Nat),
                        evalCrepFullExpsState current baseAddress topAddress
                            (currentNames.map (fun name => .var name)) =
                          evalCrepFullExpsState state baseAddress topAddress
                            (currentNames.map (fun name => .var name)) := by
                      intro current hlocals currentNames
                      induction currentNames with
                      | nil => simp [evalCrepFullExpsState]
                      | cons currentName currentNames ih =>
                          simp [evalCrepFullExpsState, evalCrepFullExpState,
                            ih, hlocals]
                    rw [hvars nextState rfl]
                    exact htailEval
                  have htailResult := ih (state := nextState)
                    (address := address + stride) (values := values)
                    hlength' htailEval'
                  simp [crepNestedSeq, storeGlobals, evalCrepFullProgState,
                    evalCrepFullExpState, hnameEval, htailResult,
                    updateMemoryListAt, nextState, Nat.add_assoc]

theorem evalCrepFullProgState_storeGlobals_vars_of_fuel
    [BEq α] [LawfulBEq α] [OfNat α 0] [OfNat α 1] [Add α] [Mul α]
    [Sub α] [AndOp α] [OrOp α] [HXor α α α] [ShiftLeft α] [ShiftRight α]
    [LT α] [DecidableRel (fun left right : α => left < right)] [PanCmp α]
    (functions : List (CompiledFunction α))
    (primitive : CrepPrimitiveHandler α) (ffi : CrepFfiHandler α)
    (sharedMem : CrepSharedMemHandler α)
    (baseAddress topAddress : α) (fuel : Nat) (state : CrepState α)
    (address stride : α) (names : List Nat) (values : List α)
    (hfuel : values.length + 1 ≤ fuel)
    (hlength : names.length = values.length)
    (hvalues : evalCrepFullExpsState state baseAddress topAddress
      (names.map (fun name => .var name)) = some values) :
    evalCrepFullProgState functions primitive ffi sharedMem
      baseAddress topAddress fuel state
      (crepNestedSeq (storeGlobals address stride
        (names.map (fun name => .var name)))) =
      some (.normal { state with
        globals := updateMemoryListAt state.globals address stride values }) := by
  induction names generalizing state address values fuel with
  | nil =>
      cases values with
      | nil =>
          cases fuel with
          | zero => omega
          | succ fuel =>
              simp [crepNestedSeq, storeGlobals, evalCrepFullProgState,
                updateMemoryListAt]
      | cons value values =>
          simp at hlength
  | cons name names ih =>
      cases values with
      | nil =>
          simp at hlength
      | cons value values =>
          cases fuel with
          | zero => omega
          | succ fuel =>
              simp only [List.map_cons, evalCrepFullExpsState] at hvalues
              cases hname : evalCrepFullExpState state baseAddress topAddress
                  (.var name) with
              | none => simp [hname] at hvalues
              | some nameValue =>
                  cases htail : evalCrepFullExpsState state baseAddress topAddress
                      (names.map (fun name => .var name)) with
                  | none => simp [hname, htail] at hvalues
                  | some tailValues =>
                      have hpair : nameValue :: tailValues = value :: values :=
                        Option.some.inj (by simpa [hname, htail] using hvalues)
                      cases hpair
                      have hlength' : names.length = values.length := by
                        exact Nat.succ.inj hlength
                      simp only [List.length_cons] at hfuel
                      have hfuel' : values.length + 1 ≤ fuel := by
                        omega
                      have htailEval :
                          evalCrepFullExpsState state baseAddress topAddress
                            (names.map (fun name => .var name)) = some values := by
                        exact htail
                      have hnameEval : evalCrepFullExpState state
                          baseAddress topAddress (.var name) = some value := by
                        exact hname
                      let nextState : CrepState α :=
                        { state with globals := updateMemory state.globals address value }
                      have htailEval' :
                          evalCrepFullExpsState nextState baseAddress topAddress
                            (names.map (fun name => .var name)) = some values := by
                        have hvars : ∀ (current : CrepState α),
                            current.locals = state.locals →
                            ∀ (currentNames : List Nat),
                            evalCrepFullExpsState current baseAddress topAddress
                                (currentNames.map (fun name => .var name)) =
                              evalCrepFullExpsState state baseAddress topAddress
                                (currentNames.map (fun name => .var name)) := by
                          intro current hlocals currentNames
                          induction currentNames with
                          | nil => simp [evalCrepFullExpsState]
                          | cons currentName currentNames ih =>
                              simp [evalCrepFullExpsState, evalCrepFullExpState,
                                ih, hlocals]
                        rw [hvars nextState rfl]
                        exact htailEval
                      cases fuel with
                      | zero => omega
                      | succ fuel =>
                          have htailResult := ih (state := nextState)
                            (address := address + stride) (values := values)
                            (fuel := fuel + 1) hfuel' hlength' htailEval'
                          simp [crepNestedSeq, storeGlobals, evalCrepFullProgState,
                            hnameEval, htailResult,
                            updateMemoryListAt, nextState, Nat.add_assoc]

end Flapjack
