import Flapjack.CrepeTemporaryAssignmentCorrectness

/-!
Correctness infrastructure for the compiler-owned global payload area.

`compileProg` lowers a raised structured value by evaluating temporary locals
and then running `storeGlobals` on the corresponding `.var` expressions.  The
word and two-word raise proofs previously unfolded this sequence manually;
these lemmas provide the list-shaped fact needed by the arbitrary-payload
Raise branch.
-/

namespace Flapjack

/-! A direct recursive form is useful when the address list is generated by
`storeGlobals`; it avoids introducing any algebraic assumptions about word
addresses beyond the evaluator's existing `Add` operation. -/
def updateMemoryListAt [BEq α] [Add α]
    (memory : α → Option α) (address stride : α) : List α → α → Option α
  | [], current => memory current
  | value :: values, current =>
      updateMemoryListAt (updateMemory memory address value)
        (address + stride) stride values current

theorem updateMemoryListAt_nil [BEq α] [Add α]
    (memory : α → Option α) (address stride : α) :
    updateMemoryListAt memory address stride [] = memory := by
  simp [updateMemoryListAt]

theorem updateMemoryListAt_cons [BEq α] [Add α]
    (memory : α → Option α) (address stride value : α) (values : List α) :
    updateMemoryListAt memory address stride (value :: values) =
      updateMemoryListAt (updateMemory memory address value)
        (address + stride) stride values := by
  simp [updateMemoryListAt]

set_option linter.unusedSimpArgs false in
theorem evalCrepFullProgState_storeGlobals_vars
    [BEq α] [LawfulBEq α] [OfNat α 0] [OfNat α 1] [Add α] [Mul α]
    [Sub α] [AndOp α] [OrOp α] [HXor α α α] [ShiftLeft α] [ShiftRight α]
    [LT α] [DecidableRel (fun left right : α => left < right)] [PanCmp α]
    (functions : List (CompiledFunction α))
    (primitive : CrepPrimitiveHandler α) (ffi : CrepFfiHandler α)
    (sharedMem : CrepSharedMemHandler α)
    (baseAddress topAddress : α) (state : CrepState α)
    (address stride : α) (names : List Nat) (values : List α)
    (hlength : names.length = values.length)
    (hvalues : evalCrepFullExpsState state baseAddress topAddress
      (names.map (fun name => .var name)) = some values) :
    evalCrepFullProgState functions primitive ffi sharedMem
      baseAddress topAddress (values.length + 1) state
      (crepNestedSeq (storeGlobals address stride
        (names.map (fun name => .var name)))) =
      some (.normal { state with
        globals := updateMemoryListAt state.globals address stride values }) := by
  induction names generalizing state address values with
  | nil =>
      cases values with
      | nil =>
          simp [crepNestedSeq, storeGlobals, evalCrepFullProgState,
            evalCrepFullExpsState, updateMemoryListAt]
      | cons value values =>
          simp at hlength
  | cons name names ih =>
      cases values with
      | nil =>
          simp at hlength
      | cons value values =>
          simp only [List.map_cons, evalCrepFullExpsState] at hvalues
          cases hname : evalCrepFullExpState state baseAddress topAddress
              (.var name) with
          | none => simp [hname] at hvalues
          | some nameValue =>
              cases htail : evalCrepFullExpsState state baseAddress topAddress
                  (names.map (fun name => .var name)) with
              | none => simp [hname, htail] at hvalues
              | some tailValues =>
                  have hpair : nameValue :: tailValues = value :: values :=
                    Option.some.inj (by simpa [hname, htail] using hvalues)
                  cases hpair
                  have hlength' : names.length = values.length := by
                    exact Nat.succ.inj hlength
                  have htailEval : evalCrepFullExpsState state baseAddress topAddress
                      (names.map (fun name => .var name)) = some values := by
                    exact htail
                  have hnameEval : evalCrepFullExpState state
                      baseAddress topAddress (.var name) = some value := by
                    exact hname
                  let nextState : CrepState α :=
                    { state with globals := updateMemory state.globals address value }
                  have htailEval' : evalCrepFullExpsState nextState
                      baseAddress topAddress
                      (names.map (fun name => .var name)) = some values := by
                    have hvars : ∀ (current : CrepState α),
                        current.locals = state.locals →
                        ∀ (currentNames : List Nat),
                        evalCrepFullExpsState current baseAddress topAddress
                            (currentNames.map (fun name => .var name)) =
                          evalCrepFullExpsState state baseAddress topAddress
                            (currentNames.map (fun name => .var name)) := by
                      intro current hlocals currentNames
                      induction currentNames with
                      | nil => simp [evalCrepFullExpsState]
                      | cons currentName currentNames ih =>
                          simp [evalCrepFullExpsState, evalCrepFullExpState,
                            ih, hlocals]
                    rw [hvars nextState rfl]
                    exact htailEval
                  have htailResult := ih (state := nextState)
                    (address := address + stride) (values := values)
                    hlength' htailEval'
                  simp [crepNestedSeq, storeGlobals, evalCrepFullProgState,
                    evalCrepFullExpState, hnameEval, htailResult,
                    updateMemoryListAt, nextState, Nat.add_assoc]

end Flapjack
