import Flapjack.SourceCompiledFunctionCalleeEntry

/-!
Compiled-table form of the source callee-entry relation.

The compiler correctness theorem is usually parameterized by an already
constructed compiled function table.  This boundary rewrites the table
against `compileToCrepe` and exposes the exact body context generated by
`compileFunDecl`.
-/

namespace Flapjack

theorem sourceCompiledCalleeEntry_of_lookup
    [LawfulBEq String] [BEq α] [OfNat α 0] [Add α]
    (structs : StructContext) (context : CompileContext α)
    (declarations : List (Decl α))
    (functions : List (CompiledFunction α))
    (name : FunName) (sourceParams : List VarName) (sourceBody : Prog α)
    (sourceGlobals : VarName → Option (PanValue α))
    (sourceMemory : α → Option (PanValue α))
    (crepMemory : α → Option α)
    (values : List (PanValue α))
    (hlookup : lookupPanFunction name (sourceFunctionEntries declarations) =
      some (sourceParams, sourceBody))
    (hfunctions : functions = compileToCrepe context declarations)
    (hvaluesLength : sourceParams.length = values.length)
    (hglobals : sourceGlobals = (fun _ => none))
    (hmemory : panValueWordMemory sourceMemory = crepMemory)
    (hcontext : context.vars = [])
    (hnames : sourceParams.Nodup)
    (hshape : ∀ (parameters : List (VarName × Shape)) (returnShape : Shape),
      lookupInfo name (functionInfos declarations) =
        some (parameters, returnShape) →
      ∀ parameter ∈ compileCalleeParameterList parameters values 0,
        panShapeMatches (panValueShape structs parameter.value) parameter.shape = true)
    (hparameterLength : ∀ (parameters : List (VarName × Shape)) (returnShape : Shape),
      lookupInfo name (functionInfos declarations) =
        some (parameters, returnShape) →
      ∀ parameter ∈ compileCalleeParameterList parameters values 0,
        parameter.slots.length = parameter.values.length) :
    ∃ declaration : FunDecl α,
      declaration.name = name ∧
      declaration.params.map Prod.fst = sourceParams ∧
      declaration.body = sourceBody ∧
      lookupInfo name (functionInfos declarations) =
        some (declaration.params, declaration.returnShape) ∧
      lookupCompiledFunction name functions =
        some ((compileFunDecl
          { context with functions := functionInfos declarations } declaration).params,
          (compileFunDecl
            { context with functions := functionInfos declarations } declaration).body) ∧
      compileProg
          { context with
              functions := functionInfos declarations
              vars := (compileParamVars declaration.params 0).1
              maxVar := (compileParamVars declaration.params 0).2.2 }
          declaration.body =
        (compileFunDecl
          { context with functions := functionInfos declarations } declaration).body ∧
      panValueCrepStateRel structs
        { context with
            functions := functionInfos declarations
            vars := (compileParamVars declaration.params 0).1 }
        (foldCalleeParameterSource (fun _ => none)
          (compileCalleeParameterList declaration.params values 0))
        sourceGlobals sourceMemory
        { locals := foldCalleeParameterLocals (fun _ => none)
            (compileCalleeParameterList declaration.params values 0),
          memory := crepMemory } := by
  obtain ⟨declaration, hname, hparams, hbody, hinfo, hcompiled, hstate⟩ :=
    sourceFunctionCalleeEntry_compileToCrepe_of_lookup
      structs context declarations name sourceParams sourceBody sourceGlobals
      sourceMemory crepMemory values hlookup hvaluesLength hglobals hmemory hcontext
      hnames hshape hparameterLength
  refine ⟨declaration, hname, hparams, hbody, hinfo, ?_, ?_, ?_⟩
  · simpa [hfunctions] using hcompiled
  · exact compileFunDecl_body_eq_compileProg_parameter_context
      { context with functions := functionInfos declarations } declaration
  · exact hstate

end Flapjack
