import Flapjack.Test.Source
import Flapjack.Test.Parser
import Flapjack.Test.DisplayParity
import Flapjack.Test.ParserStaticExamples
import Flapjack.Test.ParserParseDefParity
import Flapjack.Test.PanSteppedSemantics
import Flapjack.Test.Backend
import Flapjack.Test.CompileFunctionDistinct
import Flapjack.Test.Runtime
import Flapjack.Test.CollectorSemantics
import Flapjack.Test.SpillAllocation
import Flapjack.Test.StepCorrectness
import Flapjack.Test.OracleAllocator
import Flapjack.Test.AllocatorDriver
import Flapjack.Test.Heuristics
import Flapjack.Test.HeuristicsFastParity
import Flapjack.Test.SpillCosts
import Flapjack.Test.HeuristicDriver
import Flapjack.Test.HeuristicStackPipeline
import Flapjack.RiscV.CorrectnessHeuristicStack
import Flapjack.Test.RiscVEncoding
import Flapjack.Test.RiscVConstantParity
import Flapjack.RiscV.CorrectnessGraphLocations
import Flapjack.Test.LongDivSemantics
import Flapjack.Test.LocValueAnalysis
import Flapjack.Test.LocValueLowering
import Flapjack.Test.LocValueMachine
import Flapjack.Test.LocValueFrameMachine
import Flapjack.Test.LocValueRiscV
import Flapjack.Test.GraphLocations
import Flapjack.Test.LinearScan
import Flapjack.Test.LinearScanSource
import Flapjack.Test.PanMemoryModel
import Flapjack.Test.CrepeMemorySemantics
import Flapjack.Test.PanValueFfiSemantics
import Flapjack.Test.PanValueFfiFuel
import Flapjack.Test.PanValueFfiClockSemantics
import Flapjack.Test.PanValueWfParity
import Flapjack.Test.PanSemStateEvalParity
import Flapjack.Test.PanCost
import Flapjack.Test.SourceSemanticsOps
import Flapjack.Test.PanToCrepExceptionRelation
import Flapjack.Test.PanToCrepRelationsParity
import Flapjack.Test.PanToCrepCodeRelParity
import Flapjack.Test.PanToCrepContextExactParity
import Flapjack.Test.PanCommonParity
import Flapjack.Test.SemanticsPropsParity
/- These legacy Crep-to-Loop theorem fixtures still assume identity variable
   resolution; source parity coverage remains in `Test.SourceToLoop`. -/
import Flapjack.Test.StaticGlobalVarParity
import Flapjack.Test.StaticRedecVarParity
import Flapjack.Test.StaticExportParamsParity
import Flapjack.Test.StaticOperandsParity
import Flapjack.Test.StaticFuncArgsParity
import Flapjack.Test.StaticStructFieldsParity
import Flapjack.Test.StaticShapeParity
import Flapjack.Test.StaticIdShapesParity
import Flapjack.Test.StaticExpParity
import Flapjack.Test.StaticProgParity
import Flapjack.Test.StaticProgsParity
import Flapjack.Test.StaticDeclsParity
import Flapjack.Test.StaticNamesParity
import Flapjack.Test.StaticOverallParity
import Flapjack.Test.FrameMachineCalls
import Flapjack.Test.StackMachineCalls
import Flapjack.Test.WordCallEquations
import Flapjack.Test.WordToStack.CompilerFfi
import Flapjack.Test.WordToStack.HandlerLowering
import Flapjack.Test.WordToStack.StatefulFfi
import Flapjack.Test.WordToStack.StatefulFfiCorrectness
import Flapjack.Test.WordToStack.StatefulSequence
import Flapjack.Test.WordToStack.StatefulIte
import Flapjack.Test.WordToStack.StatefulLoop
import Flapjack.Test.WordToStack.HeapLowering
import Flapjack.Test.WordToStack.ControlLeaves
import Flapjack.Test.WordToStack.ReturnCopy
import Flapjack.Test.WordToStack.Special
import Flapjack.Test.PipelineDiagnostics
import Flapjack.Test.FullSsa
import Flapjack.Test.PanValueMemoryFfi
import Flapjack.Test.PanValueAcceleratorFfi
import Flapjack.Test.PanValueFfiClockMemoryFfi
import Flapjack.Test.CrepeArith
import Flapjack.Test.CrepeArithLookupCodeParity
import Flapjack.Test.CrepeExpressionStabilityParity
import Flapjack.Test.CrepeInline
import Flapjack.Test.CrepeInlineRewrite
import Flapjack.Test.CrepeInlinePass
import Flapjack.RiscV.CorrectnessSpill
import Flapjack.Test.SpillRelation
import Flapjack.Test.LocationMoveRelation
import Flapjack.Test.StackParallelMoveRelation
import Flapjack.Test.CakeStackAlloc
import Flapjack.Test.StackToLab
import Flapjack.Test.LabProps
import Flapjack.Test.StackFunctionEntryRelation
import Flapjack.Test.StackFunctionSpillRelation
import Flapjack.Test.StackParallelMoveAcyclic
import Flapjack.Test.StackParallelMoveEvaluator
import Flapjack.RiscV.CorrectnessBinarySpill
import Flapjack.Test.BinarySpillRelation
import Flapjack.RiscV.CorrectnessShiftSpill
import Flapjack.Test.ShiftSpillRelation
import Flapjack.RiscV.CorrectnessLoadSpill
import Flapjack.Test.LoadSpillRelation
import Flapjack.RiscV.CorrectnessStoreSpill
import Flapjack.Test.StoreSpillRelation
import Flapjack.RiscV.CorrectnessConstSpill
import Flapjack.Test.ConstSpillRelation
import Flapjack.RiscV.CorrectnessLookupSpill
import Flapjack.Test.LookupSpillRelation
import Flapjack.RiscV.CorrectnessSetSpill
import Flapjack.Test.SetSpillRelation
import Flapjack.RiscV.CorrectnessSharedLoadSpill
import Flapjack.Test.SharedLoadSpillRelation
import Flapjack.RiscV.CorrectnessDivSpill
import Flapjack.Test.DivSpillRelation
import Flapjack.RiscV.CorrectnessGetSpill
import Flapjack.Test.GetSpillRelation
import Flapjack.RiscV.CorrectnessMemorySpill
import Flapjack.Test.MemorySpillRelation
import Flapjack.RiscV.CorrectnessDirectSet
import Flapjack.Test.DirectSetRelation
import Flapjack.RiscV.CorrectnessDirectDiv
import Flapjack.Test.DirectDivRelation
import Flapjack.RiscV.CorrectnessDirectMemory
import Flapjack.Test.DirectMemoryRelation
import Flapjack.RiscV.CorrectnessDirectSharedLoad
import Flapjack.Test.DirectSharedLoadRelation
import Flapjack.RiscV.CorrectnessDirectSharedStore
import Flapjack.Test.DirectSharedStoreRelation
import Flapjack.RiscV.CorrectnessDirectMove
import Flapjack.Test.DirectMoveRelation
import Flapjack.RiscV.CorrectnessAddCarrySpill
import Flapjack.Test.AddCarrySpillRelation
import Flapjack.RiscV.CorrectnessDirectAddCarry
import Flapjack.Test.DirectAddCarryRelation
import Flapjack.RiscV.CorrectnessLongMulSpill
import Flapjack.Test.LongMulSpillRelation
import Flapjack.RiscV.CorrectnessDirectLongMul
import Flapjack.RiscV.CorrectnessLongMulRegister
import Flapjack.Test.LongMulRegisterRelation
import Flapjack.RiscV.CorrectnessDirectLongMulRegister
import Flapjack.RiscV.CorrectnessAddCarryRegister
import Flapjack.Test.AddCarryRegisterRelation
import Flapjack.RiscV.CorrectnessDirectAddCarryRegister
import Flapjack.RiscV.CorrectnessLongMulMixed
import Flapjack.Test.LongMulMixedRelation
import Flapjack.RiscV.CorrectnessDirectLongMulMixed
import Flapjack.Test.PanValueFfiClockFuel
import Flapjack.Test.WordToStackBitsParity
import Flapjack.Test.MlStringParity
import Flapjack.Test.MlStringBridgeParity
import Flapjack.Test.PanLangShapeHOLParity
import Flapjack.Test.PanLangExpHOLParity
import Flapjack.Test.PanLangProgHOLParity
import Flapjack.Test.PanLangDeclHOLParity
import Flapjack.Test.CrepLookupCodeHOLParity
import Flapjack.Test.CrepExpHOLParity
import Flapjack.Test.CrepProgHOLParity
import Flapjack.Test.CrepHolStateParity
import Flapjack.Test.ParserByteNamesParity
import Flapjack.Test.ParserByteRangedParity
import Flapjack.Test.ParserKeywordParity
import Flapjack.Test.PanGlobalsNameByteRangedParity

/-!
# Flapjack regression tests

The tests are split by compiler layer under `Flapjack.Test`; importing this
module runs the complete regression suite while keeping each file reviewable.
-/
