import Flapjack.Test.Source
import Flapjack.Test.Backend
import Flapjack.Test.Correctness
import Flapjack.Test.Runtime
import Flapjack.Test.CollectorSemantics
import Flapjack.Test.SpillAllocation
import Flapjack.Test.CorrectnessBackend
import Flapjack.Test.OracleAllocator
import Flapjack.Test.AllocatorDriver
import Flapjack.Test.Heuristics
import Flapjack.Test.SpillCosts
import Flapjack.Test.HeuristicDriver
import Flapjack.Test.HeuristicPipeline
import Flapjack.Test.LinearScan
import Flapjack.Test.LinearScanSource
import Flapjack.Test.LinearScanDriver
import Flapjack.Test.AllocationModePipeline
import Flapjack.Test.CorrectnessCondition
import Flapjack.Test.CorrectnessCode
import Flapjack.Test.SourceToLoop
import Flapjack.Test.SourceToLoopCalls
import Flapjack.Test.SourceToLoopFfi
import Flapjack.Test.SourceToLoopMemory
import Flapjack.Test.SourceToLoopHandlers
import Flapjack.Test.SourceToCrepeHandlers
import Flapjack.Test.SourceToCrepeFfi
import Flapjack.Test.CorrectnessConditional
import Flapjack.Test.CorrectnessColour
import Flapjack.Test.FrameMachineCalls
import Flapjack.Test.StackMachineCalls
import Flapjack.Test.WordCallEquations
import Flapjack.Test.WordToStack.CompilerFfi
import Flapjack.Test.WordToStack.HandlerLowering
import Flapjack.Test.WordToStack.StatefulFfi
import Flapjack.Test.WordToStack.StatefulFfiCorrectness
import Flapjack.Test.WordToStack.StatefulSequence
import Flapjack.Test.WordToStack.StatefulIte
import Flapjack.Test.WordToStack.StatefulLoop
import Flapjack.Test.WordToStack.HeapLowering
import Flapjack.Test.WordToStack.ControlLeaves
import Flapjack.Test.StatefulPipeline
import Flapjack.Test.CorrectnessFfiRiscVLoop
import Flapjack.Test.FullSsa
import Flapjack.Test.FullSsaPipeline
import Flapjack.Test.FullSsaBitmaps
import Flapjack.Test.RuntimeLinking
import Flapjack.Test.CallEntry
import Flapjack.RiscV.CorrectnessSpill
import Flapjack.Test.SpillRelation
import Flapjack.RiscV.CorrectnessBinarySpill
import Flapjack.Test.BinarySpillRelation
import Flapjack.RiscV.CorrectnessShiftSpill
import Flapjack.Test.ShiftSpillRelation
import Flapjack.RiscV.CorrectnessLoadSpill
import Flapjack.Test.LoadSpillRelation
import Flapjack.RiscV.CorrectnessStoreSpill
import Flapjack.Test.StoreSpillRelation
import Flapjack.RiscV.CorrectnessConstSpill
import Flapjack.Test.ConstSpillRelation
import Flapjack.RiscV.CorrectnessLookupSpill
import Flapjack.Test.LookupSpillRelation
import Flapjack.RiscV.CorrectnessSetSpill
import Flapjack.Test.SetSpillRelation
import Flapjack.RiscV.CorrectnessSharedLoadSpill
import Flapjack.Test.SharedLoadSpillRelation
import Flapjack.RiscV.CorrectnessDivSpill
import Flapjack.Test.DivSpillRelation
import Flapjack.RiscV.CorrectnessGetSpill
import Flapjack.Test.GetSpillRelation
import Flapjack.RiscV.CorrectnessMemorySpill
import Flapjack.Test.MemorySpillRelation
import Flapjack.RiscV.CorrectnessDirectSet
import Flapjack.Test.DirectSetRelation
import Flapjack.RiscV.CorrectnessDirectDiv
import Flapjack.Test.DirectDivRelation
import Flapjack.RiscV.CorrectnessDirectMemory
import Flapjack.Test.DirectMemoryRelation
import Flapjack.RiscV.CorrectnessDirectSharedLoad
import Flapjack.Test.DirectSharedLoadRelation
import Flapjack.RiscV.CorrectnessDirectSharedStore
import Flapjack.Test.DirectSharedStoreRelation
import Flapjack.RiscV.CorrectnessDirectMove
import Flapjack.Test.DirectMoveRelation
import Flapjack.RiscV.CorrectnessAddCarrySpill
import Flapjack.Test.AddCarrySpillRelation
import Flapjack.RiscV.CorrectnessDirectAddCarry
import Flapjack.Test.DirectAddCarryRelation
import Flapjack.RiscV.CorrectnessLongMulSpill
import Flapjack.Test.LongMulSpillRelation
import Flapjack.RiscV.CorrectnessDirectLongMul
import Flapjack.RiscV.CorrectnessLongMulRegister
import Flapjack.Test.LongMulRegisterRelation
import Flapjack.RiscV.CorrectnessDirectLongMulRegister
import Flapjack.RiscV.CorrectnessAddCarryRegister
import Flapjack.Test.AddCarryRegisterRelation
import Flapjack.RiscV.CorrectnessDirectAddCarryRegister
import Flapjack.RiscV.CorrectnessLongMulMixed
import Flapjack.Test.LongMulMixedRelation
import Flapjack.RiscV.CorrectnessDirectLongMulMixed

/-!
# Flapjack regression tests

The tests are split by compiler layer under `Flapjack.Test`; importing this
module runs the complete regression suite while keeping each file reviewable.
-/
