import Flapjack.HolRef
import Flapjack.Pancake.CrepLang
import Flapjack.Pancake.PanToCrep
import Flapjack.Pancake.PanToCrep.Compile
import Flapjack.Pancake.PanCommon
import Flapjack.Pancake.Semantics.PanCommonProps

/-!
The exact compiler-expression bound lemma from
`cakeml/pancake/proofs/pan_to_crepProofScript.sml`.
-/

namespace Flapjack

/-- Flapjack-specific recursion bridge: successful head extraction retains
    each chosen expression in the concatenated input lists. HOL has no
    separate lemma with this Lean list-helper statement. -/
private theorem cexpHeads_mem_flatten
    {inputs : List (List (CrepExp α))} {heads : List (CrepExp α)}
    (h : cexpHeads inputs = some heads) :
    ∀ expression ∈ heads, expression ∈ inputs.flatten := by
  induction inputs generalizing heads with
  | nil =>
      simp [cexpHeads] at h
      subst heads
      simp
  | cons expressions inputs ih =>
      cases expressions with
      | nil => simp [cexpHeads] at h
      | cons head tail =>
          simp only [cexpHeads] at h
          cases htail : cexpHeads inputs with
          | none => simp [htail] at h
          | some headsTail =>
              simp [htail] at h
              subst heads
              intro expression hmem
              simp only [List.mem_cons] at hmem
              rcases hmem with rfl | hmem
              · simp [List.flatten]
              · have hmemTail := ih htail expression hmem
                exact List.mem_append.mpr (Or.inr hmemTail)

/-- Flapjack-specific local copy of the field-selection helper used to avoid
    an import cycle through the parent proof module. Its HOL port is the
    public `compileField_mem_or_zero` declaration in that module. -/
private theorem compileField_output_mem_or_input_or_zero
    [OfNat α 0] (index : Nat) (shapes : List Shape)
    (expressions : List (CrepExp α)) (output : CrepExp α)
    (houtput : output ∈ (compileField index shapes expressions).1) :
    output ∈ expressions ∨ output = .const 0 := by
  induction shapes generalizing index expressions with
  | nil =>
      simp [compileField] at houtput
      exact Or.inr houtput
  | cons shape shapes ih =>
      cases index with
      | zero => exact Or.inl (List.mem_of_mem_take houtput)
      | succ index =>
          have htail : output ∈
              (compileField index shapes (expressions.drop (Shape.shapeSize shape))).1 := by
            simpa [compileField] using houtput
          rcases ih index (expressions.drop (Shape.shapeSize shape)) htail with
            hinput | hzero
          · exact Or.inl (List.mem_of_mem_drop hinput)
          · exact Or.inr hzero

/-- Flapjack-specific membership characterization for the recursive Lean
    helper generated by `crepExpVars`; HOL uses its own `var_cexp` definition
    and has no separate declaration matching this helper. -/
private theorem crepExpVarsList_mem_iff
    (expressions : List (CrepExp α)) (name : Nat) :
    name ∈ crepExpVars.crepExpVarsList expressions ↔
      ∃ expression ∈ expressions, name ∈ crepExpVars expression := by
  induction expressions with
  | nil => simp [crepExpVars.crepExpVarsList]
  | cons expression expressions ih =>
      simp [crepExpVars.crepExpVarsList, List.mem_append, ih]

/-! Source review of HOL `eval_var_cexp_present_ctxt`
    (`cakeml/pancake/proofs/pan_to_crepProofScript.sml:693`) finds no exact Lean
    port in this module. Its conclusion says that each name appearing in
    `FLAT (MAP var_cexp es)` is present in some `ct.vars` binding's `ns` list,
    under the exact `state_rel`, successful source `eval`, `code_rel`,
    `locals_rel`, `localised_exp`, and `compile_exp` premises. The helper below
    proves only that names emitted by `compileExpHOL` are bounded by `vmax`;
    that is a different conclusion and does not establish the context lookup
    result, so it must not receive the theorem's `@[hol]` tag.

    `EvalFinite.lean` now provides the fifteen `eval_def` clauses over
    `PanSemStateFiniteExact`, but it remains untagged pending its body/qualifier
    review and does not port Pan-to-Crep's `state_rel`, `code_rel`, or
    `locals_rel`. The available cross-pass `stateRel` in `PanToCrep.lean` is
    documented there as Flapjack-specific: it uses production
    `PanSemState`/`CrepRuntimeState`, String-backed identifiers, optional
    `PanValue` memory, and a target relation that is not HOL's direct `word_lab`
    state relation. These are carrier and premise-shape mismatches, not a
    missing proof hint. A faithful port needs the reviewed finite-support
    evaluator and exact Pan-to-Crep context/state/local relations; the open
    prerequisites are tracked by `flapjack-pxn.18.3.7.1.3.1.1.2.5` and
    `flapjack-pxn.18.3.5.8.8`. Keep bead `flapjack-4ac.5.21` open until that
    exact statement can be assembled and proved. -/

/-- Flapjack-specific induction invariant for the HOL theorem below, split
    into list and expression compiler cases so Lean's compiler recursor can
    discharge its structural branches. It has no separate HOL declaration. -/
private theorem compileExpHOL_outputs_vars_bounded
    [BEq α] [OfNat α 0] [Add α] [CrepBytesInWord α]
    (context : PanToCrepHOLContext α)
    (hmax : ctxtMax context.vmax context.vars) :
    ∀ expression, (∀ output ∈ (compileExpHOL context expression).1,
        ∀ name ∈ crepExpVars output, name ≤ context.vmax) := by
  let listBound (expressions : List (Exp α)) :=
    ∀ output ∈ (compileExpHOL.compileExpListHOL context expressions).flatMap Prod.fst,
      ∀ name ∈ crepExpVars output, name ≤ context.vmax
  let expBound (expression : Exp α) :=
    ∀ output ∈ (compileExpHOL context expression).1,
      ∀ name ∈ crepExpVars output, name ≤ context.vmax
  apply compileExpHOL.induct (context := context)
    (motive1 := listBound) (motive2 := expBound)
  · intro output houtput name hname
    simp only [compileExpHOL.compileExpListHOL, List.flatMap_nil,
      List.not_mem_nil] at houtput
  · intro expression expressions ihExpression ihExpressions output houtput name hname
    simp only [compileExpHOL.compileExpListHOL, List.flatMap_cons] at houtput
    rcases List.mem_append.mp houtput with hhead | htail
    · exact ihExpression output hhead name hname
    · exact ihExpressions output htail name hname
  · intro value output houtput name hname
    simp only [compileExpHOL, List.mem_singleton] at houtput
    subst output
    simp at hname
  · intro name shape slots hlookup output houtput index hindex
    simp only [compileExpHOL, hlookup] at houtput
    simp only [List.mem_map] at houtput
    rcases houtput with ⟨slot, hslot, rfl⟩
    simp only [crepExpVars_var, List.mem_singleton] at hindex
    subst index
    exact hmax.2 name shape slots hlookup slot hslot
  · intro name hlookup output houtput index hindex
    simp only [compileExpHOL, hlookup, List.mem_singleton] at houtput
    subst output
    simp at hindex
  · intro name output houtput index hindex
    simp only [compileExpHOL, List.mem_singleton] at houtput
    subst output
    simp at hindex
  · intro expressions ihExpressions output houtput name hname
    exact ihExpressions output (by simpa [compileExpHOL] using houtput) name hname
  · intro index expression compiled shapes hshape ihExpression output houtput name hname
    simp only [compileExpHOL] at houtput
    have hcompiled : compileExpHOL context expression = compiled := rfl
    rw [hcompiled, hshape] at houtput
    rcases compileField_output_mem_or_input_or_zero index shapes compiled.1 output houtput with
      hinput | hzero
    · have hinput' : output ∈ (compileExpHOL context expression).1 := by
        simpa only [compiled] using hinput
      exact ihExpression output hinput' name hname
    · subst output
      simp at hname
  · intro index expression compiled hnot ihExpression output houtput name hname
    cases hcompiled : compileExpHOL context expression with
    | mk expressions shape =>
        cases shape with
        | one =>
            simp only [compileExpHOL, hcompiled, List.mem_singleton] at houtput
            subst output
            simp at hname
        | comb shapes =>
            exact (hnot shapes (by simp [compiled, hcompiled])).elim
        | named namedShape =>
            simp only [compileExpHOL, hcompiled, List.mem_singleton] at houtput
            subst output
            simp at hname
  · intro name fields output houtput index hindex
    simp only [compileExpHOL, List.mem_singleton] at houtput
    subst output
    simp at hindex
  · intro name value output houtput index hindex
    simp only [compileExpHOL, List.mem_singleton] at houtput
    subst output
    simp at hindex
  · intro shape expression head tail outputShape hcompile ihExpression output houtput name hname
    have hload : output ∈ loadShape 0 CrepBytesInWord.bytesInWord
        (Shape.shapeSize shape) head := by
      simpa only [compileExpHOL, hcompile] using houtput
    have hvars := crepExpVars_of_mem_loadShape
      0 CrepBytesInWord.bytesInWord (Shape.shapeSize shape) head output hload
    rw [hvars] at hname
    have hhead : head ∈ (compileExpHOL context expression).1 := by
      rw [hcompile]
      simp
    exact ihExpression head hhead name hname
  · intro shape expression hnot ihExpression output houtput name hname
    rcases hcompiled : compileExpHOL context expression with ⟨expressions, shape'⟩
    cases expressions with
    | nil =>
        simp only [compileExpHOL, hcompiled, List.mem_singleton] at houtput
        subst output
        simp at hname
    | cons head tail => exact (hnot head tail shape' hcompiled).elim
  · intro expression head tail hcompile ihExpression output houtput name hname
    simp only [compileExpHOL, hcompile, List.mem_singleton] at houtput
    subst output
    simp only [crepExpVars] at hname
    have hhead : head ∈ (compileExpHOL context expression).1 := by
      rw [hcompile]
      simp
    exact ihExpression head hhead name hname
  · intro expression hnot ihExpression output houtput name hname
    rcases hcompiled : compileExpHOL context expression with ⟨expressions, shape⟩
    cases expressions with
    | nil =>
        simp only [compileExpHOL, hcompiled, List.mem_singleton] at houtput
        subst output
        simp at hname
    | cons head tail =>
        cases shape with
        | one => exact (hnot head tail hcompiled).elim
        | comb shapes =>
            simp only [compileExpHOL, hcompiled, List.mem_singleton] at houtput
            subst output
            simp at hname
        | named namedShape =>
            simp only [compileExpHOL, hcompiled, List.mem_singleton] at houtput
            subst output
            simp at hname
  · intro expression head tail hcompile ihExpression output houtput name hname
    simp only [compileExpHOL, hcompile, List.mem_singleton] at houtput
    subst output
    simp only [crepExpVars] at hname
    have hhead : head ∈ (compileExpHOL context expression).1 := by
      rw [hcompile]
      simp
    exact ihExpression head hhead name hname
  · intro expression hnot ihExpression output houtput name hname
    rcases hcompiled : compileExpHOL context expression with ⟨expressions, shape⟩
    cases expressions with
    | nil =>
        simp only [compileExpHOL, hcompiled, List.mem_singleton] at houtput
        subst output
        simp at hname
    | cons head tail =>
        cases shape with
        | one => exact (hnot head tail hcompiled).elim
        | comb shapes =>
            simp only [compileExpHOL, hcompiled, List.mem_singleton] at houtput
            subst output
            simp at hname
        | named namedShape =>
            simp only [compileExpHOL, hcompiled, List.mem_singleton] at houtput
            subst output
            simp at hname
  · intro operator expressions heads hheads ihExpressions output houtput name hname
    simp only [compileExpHOL, hheads, List.mem_singleton] at houtput
    subst output
    have hname' : ∃ head, head ∈ heads ∧ name ∈ crepExpVars head := by
      simpa only [crepExpVars, crepExpVarsList_mem_iff] using hname
    have hbound : ∀ head ∈ heads, ∀ n ∈ crepExpVars head, n ≤ context.vmax := by
      intro head hhead n hn
      apply ihExpressions head ?_ n hn
      have hheadInputs := cexpHeads_mem_flatten hheads head hhead
      simpa [List.flatten] using hheadInputs
    rcases hname' with ⟨head, hhead, hn⟩
    exact hbound head hhead name hn
  · intro operator expressions hheads ihExpressions output houtput name hname
    simp only [compileExpHOL, hheads, List.mem_singleton] at houtput
    subst output
    simp at hname
  · intro operator expressions heads hheads ihExpressions output houtput name hname
    simp only [compileExpHOL, hheads, List.mem_singleton] at houtput
    subst output
    have hname' : ∃ head, head ∈ heads ∧ name ∈ crepExpVars head := by
      simpa only [crepExpVars, crepExpVarsList_mem_iff] using hname
    have hbound : ∀ head ∈ heads, ∀ n ∈ crepExpVars head, n ≤ context.vmax := by
      intro head hhead n hn
      apply ihExpressions head ?_ n hn
      have hheadInputs := cexpHeads_mem_flatten hheads head hhead
      simpa [List.flatten] using hheadInputs
    rcases hname' with ⟨head, hhead, hn⟩
    exact hbound head hhead name hn
  · intro operator expressions hheads ihExpressions output houtput name hname
    simp only [compileExpHOL, hheads, List.mem_singleton] at houtput
    subst output
    simp at hname
  · intro operator left right leftHead leftTail leftShape rightHead rightTail rightShape
      hright hleft ihLeft ihRight output houtput name hname
    simp only [compileExpHOL, hleft, hright, List.mem_singleton] at houtput
    subst output
    simp only [crepExpVars, List.mem_append] at hname
    rcases hname with hleftName | hrightName
    · have hhead : leftHead ∈ (compileExpHOL context left).1 := by
        rw [hleft]
        simp
      exact ihLeft leftHead hhead name hleftName
    · have hhead : rightHead ∈ (compileExpHOL context right).1 := by
        rw [hright]
        simp
      exact ihRight rightHead hhead name hrightName
  · intro operator left right hnot ihLeft ihRight output houtput name hname
    rcases hleft : compileExpHOL context left with ⟨leftExpressions, leftShape⟩
    rcases hright : compileExpHOL context right with ⟨rightExpressions, rightShape⟩
    cases leftExpressions with
    | nil =>
        simp only [compileExpHOL, hleft, hright, List.mem_singleton] at houtput
        subst output
        simp at hname
    | cons leftHead leftTail =>
      cases rightExpressions with
      | nil =>
          simp only [compileExpHOL, hleft, hright, List.mem_singleton] at houtput
          subst output
          simp at hname
      | cons rightHead rightTail =>
          exact (hnot leftHead leftTail leftShape rightHead rightTail rightShape hleft hright).elim
  · intro operator left right leftHead leftTail leftShape rightHead rightTail rightShape
      hright hleft ihLeft ihRight output houtput name hname
    simp only [compileExpHOL, hleft, hright, List.mem_singleton] at houtput
    subst output
    simp only [crepExpVars, List.mem_append] at hname
    rcases hname with hleftName | hrightName
    · have hhead : leftHead ∈ (compileExpHOL context left).1 := by
        rw [hleft]
        simp
      exact ihLeft leftHead hhead name hleftName
    · have hhead : rightHead ∈ (compileExpHOL context right).1 := by
        rw [hright]
        simp
      exact ihRight rightHead hhead name hrightName
  · intro operator left right hnot ihLeft ihRight output houtput name hname
    rcases hleft : compileExpHOL context left with ⟨leftExpressions, leftShape⟩
    rcases hright : compileExpHOL context right with ⟨rightExpressions, rightShape⟩
    cases leftExpressions with
    | nil =>
        simp only [compileExpHOL, hleft, hright, List.mem_singleton] at houtput
        subst output
        simp at hname
    | cons leftHead leftTail =>
      cases rightExpressions with
      | nil =>
          simp only [compileExpHOL, hleft, hright, List.mem_singleton] at houtput
          subst output
          simp at hname
      | cons rightHead rightTail =>
          exact (hnot leftHead leftTail leftShape rightHead rightTail rightShape hleft hright).elim
  · intro output houtput name hname
    simp only [compileExpHOL, List.mem_singleton] at houtput
    subst output
    simp [crepExpVars] at hname
  · intro output houtput name hname
    simp only [compileExpHOL, List.mem_singleton] at houtput
    subst output
    simp [crepExpVars] at hname
  · intro output houtput name hname
    simp only [compileExpHOL, List.mem_singleton] at houtput
    subst output
    simp at hname

/-- Flapjack statement of HOL `MEM_compile_exp_vmax`: a Crepe variable produced
    by `compile_exp` is bounded by the source context's `vmax` whenever the
    context satisfies `ctxt_max`.

    NOT TAGGED `@[hol]`. The declaration is generic in the element type `α`
    carrying `[BEq α] [OfNat α 0] [Add α] [CrepBytesInWord α]` and calls the
    generic-`α` tag `compileExpHOL`. HOL's `compile_exp`/`context` are indexed by
    the word type `'a word` (`pan_to_crepScript.sml:10-16,39-101`) with HOL
    equality and no typeclass side conditions. As with the generic
    `loadShapeBytes` versus the exact width-indexed `loadShapeBytesW`
    (`Flapjack/Pancake/CrepLang.lean:210-228`), the exact Lean statement needs a
    width-indexed (`BitVec width`, `[NeZero width]`) carrier; that is
    `memCompileExpVmaxW` below. This generic-`α` form is retained as Flapjack
    support. -/
theorem memCompileExpVmax [BEq α] [OfNat α 0] [Add α] [CrepBytesInWord α]
    (context : PanToCrepHOLContext α) (expression : Exp α) (name : Nat)
    (output : CrepExp α)
    (hmax : ctxtMax context.vmax context.vars)
    (hvar : name ∈ crepExpVars output)
    (houtput : output ∈ (compileExpHOL context expression).1) :
    name ≤ context.vmax := by
  exact compileExpHOL_outputs_vars_bounded context hmax expression output houtput name hvar

/-- Exact port of HOL `MEM_compile_exp_vmax`
    (`cakeml/pancake/proofs/pan_to_crepProofScript.sml:410`): a Crepe variable
    produced by `compile_exp` is bounded by the source context's `vmax` whenever
    the context satisfies `ctxt_max`. Width-indexed (`BitVec width`,
    `[NeZero width]`) carrier matching HOL's `'a word`, mirroring the
    `loadShapeBytesW` standard (`Flapjack/Pancake/CrepLang.lean:210-228`).  The
    conclusion is stated through the exact width-indexed tag `compileExpHOLW`, so
    the recursive HOL `compile_exp` dependency is explicit. -/
@[hol "cakeml/pancake/proofs/pan_to_crepProofScript.sml" "MEM_compile_exp_vmax"]
theorem memCompileExpVmaxW {width : Nat} [NeZero width]
    (context : PanToCrepHOLContext (BitVec width)) (expression : Exp (BitVec width))
    (name : Nat) (output : CrepExp (BitVec width))
    (hmax : ctxtMax context.vmax context.vars)
    (hvar : name ∈ crepExpVars output)
    (houtput : output ∈ (compileExpHOLW context expression).1) :
    name ≤ context.vmax :=
  memCompileExpVmax context expression name output hmax hvar houtput

/-- Flapjack statement of HOL `genlist_vmax_distinct_lists_compiled_exps`
    (`cakeml/pancake/proofs/pan_to_crepProofScript.sml:3094`).

    NOT TAGGED `@[hol]`. The conclusion is the exact Boolean `distinctListsHol`
    and `List.range count` is HOL's `GENLIST (λx. SUC x + ctxt.vmax) count`, but
    the declaration is generic in the element type `α` carrying
    `[DecidableEq α] [BEq α]` and calls the generic-`α` tag `compileExpHOL`. HOL's
    `compile_exp`/`context` are indexed by the word type `'a word`
    (`pan_to_crepScript.sml:10-16,39-101`) with HOL equality and no typeclass
    side conditions. As with the generic `loadShapeBytes` versus the exact
    width-indexed `loadShapeBytesW` (`Flapjack/Pancake/CrepLang.lean:210-228`),
    the exact Lean statement needs a width-indexed (`BitVec width`, `[NeZero
    width]`) carrier. The generic-`α` form is retained as Flapjack support; the
    faithful width-indexed port is `genlistVmaxDistinctListsCompiledExpsW`
    below. Direct HOL/Lean oracle rows live in
    `scripts/hol-probes/pan_common_distinct_lists_probe.out`. -/
theorem genlistVmaxDistinctListsCompiledExps
    [DecidableEq α] [BEq α] [OfNat α 0] [Add α] [CrepBytesInWord α]
    (context : PanToCrepHOLContext α) (count : Nat)
    (argExpressions : List (Exp α))
    (hmax : ctxtMax context.vmax context.vars) :
    distinctListsHol
      ((List.range count).map (fun i => i + 1 + context.vmax))
      ((argExpressions.map (compileExpHOL context)).flatMap
        (fun compiled => compiled.1.flatMap crepExpVars)) = true := by
  rw [distinctListsHol_eq_true_iff_listDisjoint]
  apply listDisjoint_range_add count context.vmax _
  intro name hname
  simp only [List.mem_flatMap] at hname
  rcases hname with ⟨compiled, hcompiled, hvars⟩
  simp only [List.mem_map] at hcompiled
  rcases hcompiled with ⟨expression, _hexpression, rfl⟩
  rcases hvars with ⟨output, houtput, hvar⟩
  exact compileExpHOL_outputs_vars_bounded context hmax expression output
    houtput name hvar

/-- Exact width-indexed port of HOL `genlist_vmax_distinct_lists_compiled_exps`
    (`cakeml/pancake/proofs/pan_to_crepProofScript.sml:3094`).

    HOL's `compile_exp` and `context` are indexed by the word type `'a word`
    (`pan_to_crepScript.sml:10-16,39-101`) with HOL equality and no typeclass
    side conditions.  Following the `loadShapeBytes` versus `loadShapeBytesW`
    standard (`Flapjack/Pancake/CrepLang.lean:210-231`), the faithful statement
    fixes the carrier to `BitVec width` with `[NeZero width]`; the only side
    condition is HOL's `ctxt_max ctxt.vmax ctxt.vars`, rendered as `ctxtMax`.
    The generic-`α` form above is retained as Flapjack support.  The conclusion is
    stated through the exact width-indexed tag `compileExpHOLW`, so the recursive
    HOL `compile_exp` dependency is explicit. -/
@[hol "cakeml/pancake/proofs/pan_to_crepProofScript.sml" "genlist_vmax_distinct_lists_compiled_exps"]
theorem genlistVmaxDistinctListsCompiledExpsW {width : Nat} [NeZero width]
    (context : PanToCrepHOLContext (BitVec width)) (count : Nat)
    (argExpressions : List (Exp (BitVec width)))
    (hmax : ctxtMax context.vmax context.vars) :
    distinctListsHol
      ((List.range count).map (fun i => i + 1 + context.vmax))
      ((argExpressions.map (compileExpHOLW context)).flatMap
        (fun compiled => compiled.1.flatMap crepExpVars)) = true :=
  genlistVmaxDistinctListsCompiledExps context count argExpressions hmax

end Flapjack
