import Flapjack.HolRef
import Flapjack.Pancake.Semantics.PanProps

/-!
# `localised_exp_simps`

Exact port of HOL `panProps$localised_exp_simps`
(`cakeml/pancake/semantics/panPropsScript.sml:1366`).  HOL derives this
`LIST_CONJ` from `exp_cons_patterns` (the constructor patterns of `panLang$exp`
from `exp_nchotomy`) by evaluating `localised_exp` on each pattern and rewriting
with the converse of `localised_exp_real_def`: it is exactly the collection of
one equation per `exp` constructor, universally quantified over the pattern
variables, with right-hand sides given recursively in terms of `localised_exp`.

`localisedExpHOL` is the exact port of
`localised_exp = every_exp (\e. case e of Var tp _ => tp = Local | _ => T)`
(`panPropsScript.sml:1362`, tagged `localised_exp_real_def` in `PanProps.lean`).
`localisedExpPredHOL` below names the lambda `\e. case e of Var tp _ => tp = Local
| _ => T` so that the right-hand sides can be written with the repository's
rendering of HOL's `EVERY` folds (`everyExpListHOL`, `everyExpFieldListHOL`),
matching the `every_exp_def` port.
-/

namespace Flapjack

open Flapjack.Pancake.PanLang

/-- The predicate `\e. case e of Var tp _ => tp = Local | _ => T` from HOL
    `localised_exp_real_def` (`panPropsScript.sml:1363`), named so that the
    `localised_exp_simps` right-hand sides read as `EVERY localised_exp`. -/
def localisedExpPredHOL {width : Nat} [NeZero width] : ExpHOL width → Bool
  | .var .local _ => true
  | .var .global _ => false
  | _ => true

/-- HOL `panProps$localised_exp_simps` (`panPropsScript.sml:1366`): the
    constructor equations of `localised_exp` generated by `EVAL` from
    `exp_cons_patterns`.  Each conjunct is the `every_exp` unfolding at one
    `ExpHOL width` constructor, with `P` instantiated to
    `\e. case e of Var tp _ => tp = Local | _ => T` and `EVERY` folds rendered
    as `everyExpListHOL`/`everyExpFieldListHOL`. -/
@[hol "cakeml/pancake/semantics/panPropsScript.sml" "localised_exp_simps"]
theorem localisedExpSimpsHOL {width : Nat} [NeZero width] :
    (∀ (w : BitVec width), localisedExpHOL (.const w) = true) ∧
    (∀ (vk : VarKind) (v : MlS),
      localisedExpHOL (width := width) (.var vk v) = decide (vk = VarKind.local)) ∧
    (∀ (es : List (ExpHOL width)),
      localisedExpHOL (.rstruct es) = everyExpListHOL localisedExpPredHOL es) ∧
    (∀ (i : Nat) (e : ExpHOL width), localisedExpHOL (.rfield i e) = localisedExpHOL e) ∧
    (∀ (nm : MlS) (es : List (MlS × ExpHOL width)), localisedExpHOL (.nstruct nm es) =
      everyExpFieldListHOL localisedExpPredHOL es) ∧
    (∀ (i : MlS) (e : ExpHOL width), localisedExpHOL (.nfield i e) = localisedExpHOL e) ∧
    (∀ (sh : ShapeHOL) (e : ExpHOL width), localisedExpHOL (.load sh e) = localisedExpHOL e) ∧
    (∀ (e : ExpHOL width), localisedExpHOL (.load32 e) = localisedExpHOL e) ∧
    (∀ (e : ExpHOL width), localisedExpHOL (.loadByte e) = localisedExpHOL e) ∧
    (∀ (bop : BinOp) (es : List (ExpHOL width)),
      localisedExpHOL (.op bop es) = everyExpListHOL localisedExpPredHOL es) ∧
    (∀ (op : PanOp) (es : List (ExpHOL width)),
      localisedExpHOL (.panop op es) = everyExpListHOL localisedExpPredHOL es) ∧
    (∀ (c : Cmp) (e1 e2 : ExpHOL width),
      localisedExpHOL (.cmp c e1 e2) = (localisedExpHOL e1 && localisedExpHOL e2)) ∧
    (∀ (sh : Shift) (e1 e2 : ExpHOL width),
      localisedExpHOL (.shift sh e1 e2) = (localisedExpHOL e1 && localisedExpHOL e2)) ∧
    localisedExpHOL (width := width) .baseAddr = true ∧
    localisedExpHOL (width := width) .topAddr = true ∧
    localisedExpHOL (width := width) .bytesInWord = true := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · intro w; rfl
  · intro vk v; cases vk <;> rfl
  all_goals (intros; rfl)

end Flapjack
