import Flapjack.HolRef
import Flapjack.Pancake.Semantics.PanProps

/-!
# `nameless_exp_simps`

Exact port of HOL `panProps$nameless_exp_simps`
(`cakeml/pancake/semantics/panPropsScript.sml:1375`).  HOL derives this
`LIST_CONJ` from `exp_cons_patterns` (the constructor patterns of `panLang$exp`
from `exp_nchotomy`) by evaluating `nameless_exp` on each pattern and rewriting
with the converse of `nameless_exp_real_def`: it is exactly the collection of
one equation per `exp` constructor, universally quantified over the pattern
variables, with right-hand sides given recursively in terms of `nameless_exp`.

`namelessExpHOL` is the exact port of
`nameless_exp = every_exp (\e. case e of NStruct _ _ => F | NField _ _ => F |
_ => T)` (`panPropsScript.sml:1371`, tagged `nameless_exp_real_def` in
`PanProps.lean`).  `namelessExpPredHOL` below names that lambda so that the
right-hand sides can be written with the repository's rendering of HOL's `EVERY`
folds (`everyExpListHOL`, `everyExpFieldListHOL`), matching the `every_exp_def`
port.  The two rejecting constructors `NStruct`/`NField` give the constant
`false` right-hand sides that `EVAL` produces.
-/

namespace Flapjack

open Flapjack.Pancake.PanLang

/-- The predicate `\e. case e of NStruct _ _ => F | NField _ _ => F | _ => T`
    from HOL `nameless_exp_real_def` (`panPropsScript.sml:1372`), named so that
    the `nameless_exp_simps` right-hand sides read as `EVERY nameless_exp`. -/
def namelessExpPredHOL {width : Nat} [NeZero width] : ExpHOL width → Bool
  | .nstruct _ _ => false
  | .nfield _ _ => false
  | _ => true

/-- HOL `panProps$nameless_exp_simps` (`panPropsScript.sml:1375`): the
    constructor equations of `nameless_exp` generated by `EVAL` from
    `exp_cons_patterns`.  Each conjunct is the `every_exp` unfolding at one
    `ExpHOL width` constructor, with `P` instantiated to
    `\e. case e of NStruct _ _ => F | NField _ _ => F | _ => T` and `EVERY`
    folds rendered as `everyExpListHOL`/`everyExpFieldListHOL`. -/
@[hol "cakeml/pancake/semantics/panPropsScript.sml" "nameless_exp_simps"]
theorem namelessExpSimpsHOL {width : Nat} [NeZero width] :
    (∀ (w : BitVec width), namelessExpHOL (.const w) = true) ∧
    (∀ (vk : VarKind) (v : MlS),
      namelessExpHOL (width := width) (.var vk v) = true) ∧
    (∀ (es : List (ExpHOL width)),
      namelessExpHOL (.rstruct es) = everyExpListHOL namelessExpPredHOL es) ∧
    (∀ (i : Nat) (e : ExpHOL width), namelessExpHOL (.rfield i e) = namelessExpHOL e) ∧
    (∀ (nm : MlS) (es : List (MlS × ExpHOL width)),
      namelessExpHOL (.nstruct nm es) = false) ∧
    (∀ (i : MlS) (e : ExpHOL width), namelessExpHOL (.nfield i e) = false) ∧
    (∀ (sh : ShapeHOL) (e : ExpHOL width), namelessExpHOL (.load sh e) = namelessExpHOL e) ∧
    (∀ (e : ExpHOL width), namelessExpHOL (.load32 e) = namelessExpHOL e) ∧
    (∀ (e : ExpHOL width), namelessExpHOL (.loadByte e) = namelessExpHOL e) ∧
    (∀ (bop : BinOp) (es : List (ExpHOL width)),
      namelessExpHOL (.op bop es) = everyExpListHOL namelessExpPredHOL es) ∧
    (∀ (op : PanOp) (es : List (ExpHOL width)),
      namelessExpHOL (.panop op es) = everyExpListHOL namelessExpPredHOL es) ∧
    (∀ (c : Cmp) (e1 e2 : ExpHOL width),
      namelessExpHOL (.cmp c e1 e2) = (namelessExpHOL e1 && namelessExpHOL e2)) ∧
    (∀ (sh : Shift) (e1 e2 : ExpHOL width),
      namelessExpHOL (.shift sh e1 e2) = (namelessExpHOL e1 && namelessExpHOL e2)) ∧
    namelessExpHOL (width := width) .baseAddr = true ∧
    namelessExpHOL (width := width) .topAddr = true ∧
    namelessExpHOL (width := width) .bytesInWord = true := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  all_goals (intros; rfl)

end Flapjack
