name: Lean Action CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: leanprover/lean-action@v1

      - name: Check for new native_decide uses
        run: ./scripts/check-native-decide.sh

      - name: Check the build is warning-free
        run: ./scripts/check-warnings.sh
